/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.merchantmanagement.v1.api;

import com.fasterxml.jackson.databind.ObjectMapper;

import id.dana.invoker.ApiClient;
import id.dana.invoker.model.exception.DanaException;

import retrofit2.Call;
import retrofit2.Response;
import retrofit2.http.*;

import okhttp3.OkHttpClient;
import okhttp3.ResponseBody;

import id.dana.merchantmanagement.v1.model.CreateDivisionRequest;
import id.dana.merchantmanagement.v1.model.CreateDivisionResponse;
import id.dana.merchantmanagement.v1.model.CreateShopRequest;
import id.dana.merchantmanagement.v1.model.CreateShopResponse;
import id.dana.merchantmanagement.v1.model.QueryDivisionRequest;
import id.dana.merchantmanagement.v1.model.QueryDivisionResponse;
import id.dana.merchantmanagement.v1.model.QueryMerchantResourceRequest;
import id.dana.merchantmanagement.v1.model.QueryMerchantResourceResponse;
import id.dana.merchantmanagement.v1.model.QueryShopRequest;
import id.dana.merchantmanagement.v1.model.QueryShopResponse;
import id.dana.merchantmanagement.v1.model.UpdateDivisionRequest;
import id.dana.merchantmanagement.v1.model.UpdateDivisionResponse;
import id.dana.merchantmanagement.v1.model.UpdateShopRequest;
import id.dana.merchantmanagement.v1.model.UpdateShopResponse;

import java.io.IOException;

interface MerchantManagementApiService {

  /**
   * Create Division
   * This API is used to create a new division
   * @param createDivisionRequest  (required)
   * @return Call<CreateDivisionResponse>
   */
  @Headers({
    "Content-Type:application/json",
    "X-API-TYPE:OPEN_API",
    "X-API-VERSION:2.0",
    "X-API-FUNCTION:dana.merchant.division.createDivision"
  })
  @POST("dana/merchant/division/createDivision.htm")
  Call<CreateDivisionResponse> createDivision(
    @retrofit2.http.Body CreateDivisionRequest createDivisionRequest
  );

  /**
   * Member – Create Shop
   * Create shop under merchant or division
   * @param createShopRequest  (required)
   * @return Call<CreateShopResponse>
   */
  @Headers({
    "Content-Type:application/json",
    "X-API-TYPE:OPEN_API",
    "X-API-VERSION:2.0",
    "X-API-FUNCTION:dana.merchant.shop.createShop"
  })
  @POST("dana/merchant/shop/createShop.htm")
  Call<CreateShopResponse> createShop(
    @retrofit2.http.Body CreateShopRequest createShopRequest
  );

  /**
   * Query Division
   * This API is used to obtain information of division
   * @param queryDivisionRequest  (required)
   * @return Call<QueryDivisionResponse>
   */
  @Headers({
    "Content-Type:application/json",
    "X-API-TYPE:OPEN_API",
    "X-API-VERSION:2.0",
    "X-API-FUNCTION:dana.merchant.division.queryDivision"
  })
  @POST("dana/merchant/division/queryDivision.htm")
  Call<QueryDivisionResponse> queryDivision(
    @retrofit2.http.Body QueryDivisionRequest queryDivisionRequest
  );

  /**
   * Member – Merchant Open API Check Disbursement Account
   * The interface is check merchant resource info (account balance merchant)
   * @param queryMerchantResourceRequest  (required)
   * @return Call<QueryMerchantResourceResponse>
   */
  @Headers({
    "Content-Type:application/json",
    "X-API-TYPE:OPEN_API",
    "X-API-VERSION:2.0",
    "X-API-FUNCTION:dana.merchant.queryMerchantResource"
  })
  @POST("dana/merchant/queryMerchantResource.htm")
  Call<QueryMerchantResourceResponse> queryMerchantResource(
    @retrofit2.http.Body QueryMerchantResourceRequest queryMerchantResourceRequest
  );

  /**
   * Member – Query Shop
   * This API is used to obtain information of shop information
   * @param queryShopRequest  (required)
   * @return Call<QueryShopResponse>
   */
  @Headers({
    "Content-Type:application/json",
    "X-API-TYPE:OPEN_API",
    "X-API-VERSION:2.0",
    "X-API-FUNCTION:dana.merchant.shop.queryShop"
  })
  @POST("dana/merchant/shop/queryShop.htm")
  Call<QueryShopResponse> queryShop(
    @retrofit2.http.Body QueryShopRequest queryShopRequest
  );

  /**
   * Update Division
   * This API is used to update the division information
   * @param updateDivisionRequest  (required)
   * @return Call<UpdateDivisionResponse>
   */
  @Headers({
    "Content-Type:application/json",
    "X-API-TYPE:OPEN_API",
    "X-API-VERSION:2.0",
    "X-API-FUNCTION:dana.merchant.division.updateDivision"
  })
  @POST("dana/merchant/division/updateDivision.htm")
  Call<UpdateDivisionResponse> updateDivision(
    @retrofit2.http.Body UpdateDivisionRequest updateDivisionRequest
  );

  /**
   * Update Shop
   * This API is used to update the shop information
   * @param updateShopRequest  (required)
   * @return Call<UpdateShopResponse>
   */
  @Headers({
    "Content-Type:application/json",
    "X-API-TYPE:OPEN_API",
    "X-API-VERSION:2.0",
    "X-API-FUNCTION:dana.merchant.shop.updateShop"
  })
  @POST("dana/merchant/shop/updateShop.htm")
  Call<UpdateShopResponse> updateShop(
    @retrofit2.http.Body UpdateShopRequest updateShopRequest
  );

}

public class MerchantManagementApi {

  private static final ObjectMapper objectMapper = new ObjectMapper();

  private final MerchantManagementApiService service;

  public MerchantManagementApi(OkHttpClient client) {
    this.service = new ApiClient(client).createService(MerchantManagementApiService.class);
  }

  /**
   * Create Division
   * This API is used to create a new division
   * @param createDivisionRequest  (required)
   * @return CreateDivisionResponse
   */
  public CreateDivisionResponse createDivision(
    @retrofit2.http.Body CreateDivisionRequest createDivisionRequest
  ) {
    // Run custom validations (e.g., validUpTo date validation)
    // This validation runs even when structs are created directly (bypassing setters)
    try {
      String packageName = "id.dana.merchantmanagement.v1.api";
      String customValidationPackage = packageName.replace(".api", "");
      Class<?> customValidationClass = Class.forName(customValidationPackage + ".CustomValidation");
      java.lang.reflect.Method customValidationMethod = customValidationClass.getMethod("customValidation", Object.class);
      customValidationMethod.invoke(null, createDivisionRequest);
    } catch (ClassNotFoundException | NoClassDefFoundError e) {
      // If CustomValidation doesn't exist for this domain, skip it
      // This allows the template to work for all domains
    } catch (Exception e) {
      // Re-throw other exceptions (validation errors, etc.)
      if (e instanceof java.lang.reflect.InvocationTargetException) {
        Throwable cause = ((java.lang.reflect.InvocationTargetException) e).getTargetException();
        if (cause instanceof DanaException) {
          throw (DanaException) cause;
        }
        if (cause instanceof RuntimeException) {
          throw (RuntimeException) cause;
        }
      }
      throw new DanaException("Custom validation error", e);
    }
    try {
      Response<CreateDivisionResponse> response = service.createDivision(createDivisionRequest).execute();
      if (response.isSuccessful()) {
        return response.body();
      } else {
        try (ResponseBody errorBody = response.errorBody()) {
          if (errorBody != null) {
            String errorBodyString = errorBody.string();
            try {
              return objectMapper.readValue(errorBodyString, CreateDivisionResponse.class);
            } catch (Exception jsonException) {
              throw new DanaException("API Error: " + errorBodyString);
            }
          } else {
            throw new DanaException("Empty error body");
          }
        }
      }
    } catch (IOException e) {
      throw new DanaException("Network error", e);
    }
  }

  /**
   * Member – Create Shop
   * Create shop under merchant or division
   * @param createShopRequest  (required)
   * @return CreateShopResponse
   */
  public CreateShopResponse createShop(
    @retrofit2.http.Body CreateShopRequest createShopRequest
  ) {
    // Run custom validations (e.g., validUpTo date validation)
    // This validation runs even when structs are created directly (bypassing setters)
    try {
      String packageName = "id.dana.merchantmanagement.v1.api";
      String customValidationPackage = packageName.replace(".api", "");
      Class<?> customValidationClass = Class.forName(customValidationPackage + ".CustomValidation");
      java.lang.reflect.Method customValidationMethod = customValidationClass.getMethod("customValidation", Object.class);
      customValidationMethod.invoke(null, createShopRequest);
    } catch (ClassNotFoundException | NoClassDefFoundError e) {
      // If CustomValidation doesn't exist for this domain, skip it
      // This allows the template to work for all domains
    } catch (Exception e) {
      // Re-throw other exceptions (validation errors, etc.)
      if (e instanceof java.lang.reflect.InvocationTargetException) {
        Throwable cause = ((java.lang.reflect.InvocationTargetException) e).getTargetException();
        if (cause instanceof DanaException) {
          throw (DanaException) cause;
        }
        if (cause instanceof RuntimeException) {
          throw (RuntimeException) cause;
        }
      }
      throw new DanaException("Custom validation error", e);
    }
    try {
      Response<CreateShopResponse> response = service.createShop(createShopRequest).execute();
      if (response.isSuccessful()) {
        return response.body();
      } else {
        try (ResponseBody errorBody = response.errorBody()) {
          if (errorBody != null) {
            String errorBodyString = errorBody.string();
            try {
              return objectMapper.readValue(errorBodyString, CreateShopResponse.class);
            } catch (Exception jsonException) {
              throw new DanaException("API Error: " + errorBodyString);
            }
          } else {
            throw new DanaException("Empty error body");
          }
        }
      }
    } catch (IOException e) {
      throw new DanaException("Network error", e);
    }
  }

  /**
   * Query Division
   * This API is used to obtain information of division
   * @param queryDivisionRequest  (required)
   * @return QueryDivisionResponse
   */
  public QueryDivisionResponse queryDivision(
    @retrofit2.http.Body QueryDivisionRequest queryDivisionRequest
  ) {
    // Run custom validations (e.g., validUpTo date validation)
    // This validation runs even when structs are created directly (bypassing setters)
    try {
      String packageName = "id.dana.merchantmanagement.v1.api";
      String customValidationPackage = packageName.replace(".api", "");
      Class<?> customValidationClass = Class.forName(customValidationPackage + ".CustomValidation");
      java.lang.reflect.Method customValidationMethod = customValidationClass.getMethod("customValidation", Object.class);
      customValidationMethod.invoke(null, queryDivisionRequest);
    } catch (ClassNotFoundException | NoClassDefFoundError e) {
      // If CustomValidation doesn't exist for this domain, skip it
      // This allows the template to work for all domains
    } catch (Exception e) {
      // Re-throw other exceptions (validation errors, etc.)
      if (e instanceof java.lang.reflect.InvocationTargetException) {
        Throwable cause = ((java.lang.reflect.InvocationTargetException) e).getTargetException();
        if (cause instanceof DanaException) {
          throw (DanaException) cause;
        }
        if (cause instanceof RuntimeException) {
          throw (RuntimeException) cause;
        }
      }
      throw new DanaException("Custom validation error", e);
    }
    try {
      Response<QueryDivisionResponse> response = service.queryDivision(queryDivisionRequest).execute();
      if (response.isSuccessful()) {
        return response.body();
      } else {
        try (ResponseBody errorBody = response.errorBody()) {
          if (errorBody != null) {
            String errorBodyString = errorBody.string();
            try {
              return objectMapper.readValue(errorBodyString, QueryDivisionResponse.class);
            } catch (Exception jsonException) {
              throw new DanaException("API Error: " + errorBodyString);
            }
          } else {
            throw new DanaException("Empty error body");
          }
        }
      }
    } catch (IOException e) {
      throw new DanaException("Network error", e);
    }
  }

  /**
   * Member – Merchant Open API Check Disbursement Account
   * The interface is check merchant resource info (account balance merchant)
   * @param queryMerchantResourceRequest  (required)
   * @return QueryMerchantResourceResponse
   */
  public QueryMerchantResourceResponse queryMerchantResource(
    @retrofit2.http.Body QueryMerchantResourceRequest queryMerchantResourceRequest
  ) {
    // Run custom validations (e.g., validUpTo date validation)
    // This validation runs even when structs are created directly (bypassing setters)
    try {
      String packageName = "id.dana.merchantmanagement.v1.api";
      String customValidationPackage = packageName.replace(".api", "");
      Class<?> customValidationClass = Class.forName(customValidationPackage + ".CustomValidation");
      java.lang.reflect.Method customValidationMethod = customValidationClass.getMethod("customValidation", Object.class);
      customValidationMethod.invoke(null, queryMerchantResourceRequest);
    } catch (ClassNotFoundException | NoClassDefFoundError e) {
      // If CustomValidation doesn't exist for this domain, skip it
      // This allows the template to work for all domains
    } catch (Exception e) {
      // Re-throw other exceptions (validation errors, etc.)
      if (e instanceof java.lang.reflect.InvocationTargetException) {
        Throwable cause = ((java.lang.reflect.InvocationTargetException) e).getTargetException();
        if (cause instanceof DanaException) {
          throw (DanaException) cause;
        }
        if (cause instanceof RuntimeException) {
          throw (RuntimeException) cause;
        }
      }
      throw new DanaException("Custom validation error", e);
    }
    try {
      Response<QueryMerchantResourceResponse> response = service.queryMerchantResource(queryMerchantResourceRequest).execute();
      if (response.isSuccessful()) {
        return response.body();
      } else {
        try (ResponseBody errorBody = response.errorBody()) {
          if (errorBody != null) {
            String errorBodyString = errorBody.string();
            try {
              return objectMapper.readValue(errorBodyString, QueryMerchantResourceResponse.class);
            } catch (Exception jsonException) {
              throw new DanaException("API Error: " + errorBodyString);
            }
          } else {
            throw new DanaException("Empty error body");
          }
        }
      }
    } catch (IOException e) {
      throw new DanaException("Network error", e);
    }
  }

  /**
   * Member – Query Shop
   * This API is used to obtain information of shop information
   * @param queryShopRequest  (required)
   * @return QueryShopResponse
   */
  public QueryShopResponse queryShop(
    @retrofit2.http.Body QueryShopRequest queryShopRequest
  ) {
    // Run custom validations (e.g., validUpTo date validation)
    // This validation runs even when structs are created directly (bypassing setters)
    try {
      String packageName = "id.dana.merchantmanagement.v1.api";
      String customValidationPackage = packageName.replace(".api", "");
      Class<?> customValidationClass = Class.forName(customValidationPackage + ".CustomValidation");
      java.lang.reflect.Method customValidationMethod = customValidationClass.getMethod("customValidation", Object.class);
      customValidationMethod.invoke(null, queryShopRequest);
    } catch (ClassNotFoundException | NoClassDefFoundError e) {
      // If CustomValidation doesn't exist for this domain, skip it
      // This allows the template to work for all domains
    } catch (Exception e) {
      // Re-throw other exceptions (validation errors, etc.)
      if (e instanceof java.lang.reflect.InvocationTargetException) {
        Throwable cause = ((java.lang.reflect.InvocationTargetException) e).getTargetException();
        if (cause instanceof DanaException) {
          throw (DanaException) cause;
        }
        if (cause instanceof RuntimeException) {
          throw (RuntimeException) cause;
        }
      }
      throw new DanaException("Custom validation error", e);
    }
    try {
      Response<QueryShopResponse> response = service.queryShop(queryShopRequest).execute();
      if (response.isSuccessful()) {
        return response.body();
      } else {
        try (ResponseBody errorBody = response.errorBody()) {
          if (errorBody != null) {
            String errorBodyString = errorBody.string();
            try {
              return objectMapper.readValue(errorBodyString, QueryShopResponse.class);
            } catch (Exception jsonException) {
              throw new DanaException("API Error: " + errorBodyString);
            }
          } else {
            throw new DanaException("Empty error body");
          }
        }
      }
    } catch (IOException e) {
      throw new DanaException("Network error", e);
    }
  }

  /**
   * Update Division
   * This API is used to update the division information
   * @param updateDivisionRequest  (required)
   * @return UpdateDivisionResponse
   */
  public UpdateDivisionResponse updateDivision(
    @retrofit2.http.Body UpdateDivisionRequest updateDivisionRequest
  ) {
    // Run custom validations (e.g., validUpTo date validation)
    // This validation runs even when structs are created directly (bypassing setters)
    try {
      String packageName = "id.dana.merchantmanagement.v1.api";
      String customValidationPackage = packageName.replace(".api", "");
      Class<?> customValidationClass = Class.forName(customValidationPackage + ".CustomValidation");
      java.lang.reflect.Method customValidationMethod = customValidationClass.getMethod("customValidation", Object.class);
      customValidationMethod.invoke(null, updateDivisionRequest);
    } catch (ClassNotFoundException | NoClassDefFoundError e) {
      // If CustomValidation doesn't exist for this domain, skip it
      // This allows the template to work for all domains
    } catch (Exception e) {
      // Re-throw other exceptions (validation errors, etc.)
      if (e instanceof java.lang.reflect.InvocationTargetException) {
        Throwable cause = ((java.lang.reflect.InvocationTargetException) e).getTargetException();
        if (cause instanceof DanaException) {
          throw (DanaException) cause;
        }
        if (cause instanceof RuntimeException) {
          throw (RuntimeException) cause;
        }
      }
      throw new DanaException("Custom validation error", e);
    }
    try {
      Response<UpdateDivisionResponse> response = service.updateDivision(updateDivisionRequest).execute();
      if (response.isSuccessful()) {
        return response.body();
      } else {
        try (ResponseBody errorBody = response.errorBody()) {
          if (errorBody != null) {
            String errorBodyString = errorBody.string();
            try {
              return objectMapper.readValue(errorBodyString, UpdateDivisionResponse.class);
            } catch (Exception jsonException) {
              throw new DanaException("API Error: " + errorBodyString);
            }
          } else {
            throw new DanaException("Empty error body");
          }
        }
      }
    } catch (IOException e) {
      throw new DanaException("Network error", e);
    }
  }

  /**
   * Update Shop
   * This API is used to update the shop information
   * @param updateShopRequest  (required)
   * @return UpdateShopResponse
   */
  public UpdateShopResponse updateShop(
    @retrofit2.http.Body UpdateShopRequest updateShopRequest
  ) {
    // Run custom validations (e.g., validUpTo date validation)
    // This validation runs even when structs are created directly (bypassing setters)
    try {
      String packageName = "id.dana.merchantmanagement.v1.api";
      String customValidationPackage = packageName.replace(".api", "");
      Class<?> customValidationClass = Class.forName(customValidationPackage + ".CustomValidation");
      java.lang.reflect.Method customValidationMethod = customValidationClass.getMethod("customValidation", Object.class);
      customValidationMethod.invoke(null, updateShopRequest);
    } catch (ClassNotFoundException | NoClassDefFoundError e) {
      // If CustomValidation doesn't exist for this domain, skip it
      // This allows the template to work for all domains
    } catch (Exception e) {
      // Re-throw other exceptions (validation errors, etc.)
      if (e instanceof java.lang.reflect.InvocationTargetException) {
        Throwable cause = ((java.lang.reflect.InvocationTargetException) e).getTargetException();
        if (cause instanceof DanaException) {
          throw (DanaException) cause;
        }
        if (cause instanceof RuntimeException) {
          throw (RuntimeException) cause;
        }
      }
      throw new DanaException("Custom validation error", e);
    }
    try {
      Response<UpdateShopResponse> response = service.updateShop(updateShopRequest).execute();
      if (response.isSuccessful()) {
        return response.body();
      } else {
        try (ResponseBody errorBody = response.errorBody()) {
          if (errorBody != null) {
            String errorBodyString = errorBody.string();
            try {
              return objectMapper.readValue(errorBodyString, UpdateShopResponse.class);
            } catch (Exception jsonException) {
              throw new DanaException("API Error: " + errorBodyString);
            }
          } else {
            throw new DanaException("Empty error body");
          }
        }
      }
    } catch (IOException e) {
      throw new DanaException("Network error", e);
    }
  }

}
