/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.widget.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.dana.widget.v1.model.AccountUnbindingRequestAdditionalInfo;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AccountUnbindingRequest
 */
@JsonPropertyOrder({
  AccountUnbindingRequest.JSON_PROPERTY_MERCHANT_ID,
  AccountUnbindingRequest.JSON_PROPERTY_SUB_MERCHANT_ID,
  AccountUnbindingRequest.JSON_PROPERTY_PARTNER_REFERENCE_NO,
  AccountUnbindingRequest.JSON_PROPERTY_LINK_ID,
  AccountUnbindingRequest.JSON_PROPERTY_TOKEN_ID,
  AccountUnbindingRequest.JSON_PROPERTY_ADDITIONAL_INFO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class AccountUnbindingRequest {
  public static final String JSON_PROPERTY_MERCHANT_ID = "merchantId";
  @javax.annotation.Nonnull
  private String merchantId;

  public static final String JSON_PROPERTY_SUB_MERCHANT_ID = "subMerchantId";
  @javax.annotation.Nullable
  private String subMerchantId;

  public static final String JSON_PROPERTY_PARTNER_REFERENCE_NO = "partnerReferenceNo";
  @javax.annotation.Nullable
  private String partnerReferenceNo;

  public static final String JSON_PROPERTY_LINK_ID = "linkId";
  @javax.annotation.Nullable
  private String linkId;

  public static final String JSON_PROPERTY_TOKEN_ID = "tokenId";
  @javax.annotation.Nullable
  private String tokenId;

  public static final String JSON_PROPERTY_ADDITIONAL_INFO = "additionalInfo";
  @javax.annotation.Nonnull
  private AccountUnbindingRequestAdditionalInfo additionalInfo;

  public AccountUnbindingRequest() {
  }

  public AccountUnbindingRequest merchantId(@javax.annotation.Nonnull String merchantId) {
    
    this.merchantId = merchantId;
    return this;
  }

  /**
   * Merchant identifier that is unique per each merchant
   * @return merchantId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MERCHANT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMerchantId() {
    return merchantId;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMerchantId(@javax.annotation.Nonnull String merchantId) {
    this.merchantId = merchantId;
  }

  public AccountUnbindingRequest subMerchantId(@javax.annotation.Nullable String subMerchantId) {
    
    this.subMerchantId = subMerchantId;
    return this;
  }

  /**
   * Information of sub merchant identifier
   * @return subMerchantId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUB_MERCHANT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubMerchantId() {
    return subMerchantId;
  }


  @JsonProperty(JSON_PROPERTY_SUB_MERCHANT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubMerchantId(@javax.annotation.Nullable String subMerchantId) {
    this.subMerchantId = subMerchantId;
  }

  public AccountUnbindingRequest partnerReferenceNo(@javax.annotation.Nullable String partnerReferenceNo) {
    
    this.partnerReferenceNo = partnerReferenceNo;
    return this;
  }

  /**
   * Unique transaction identifier on partner system which assigned to each transaction
   * @return partnerReferenceNo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARTNER_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPartnerReferenceNo() {
    return partnerReferenceNo;
  }


  @JsonProperty(JSON_PROPERTY_PARTNER_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPartnerReferenceNo(@javax.annotation.Nullable String partnerReferenceNo) {
    this.partnerReferenceNo = partnerReferenceNo;
  }

  public AccountUnbindingRequest linkId(@javax.annotation.Nullable String linkId) {
    
    this.linkId = linkId;
    return this;
  }

  /**
   * Information of link identifier
   * @return linkId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLinkId() {
    return linkId;
  }


  @JsonProperty(JSON_PROPERTY_LINK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinkId(@javax.annotation.Nullable String linkId) {
    this.linkId = linkId;
  }

  public AccountUnbindingRequest tokenId(@javax.annotation.Nullable String tokenId) {
    
    this.tokenId = tokenId;
    return this;
  }

  /**
   * Information of token identifier
   * @return tokenId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOKEN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTokenId() {
    return tokenId;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTokenId(@javax.annotation.Nullable String tokenId) {
    this.tokenId = tokenId;
  }

  public AccountUnbindingRequest additionalInfo(@javax.annotation.Nonnull AccountUnbindingRequestAdditionalInfo additionalInfo) {
    
    this.additionalInfo = additionalInfo;
    return this;
  }

  /**
   * Additional information
   * @return additionalInfo
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AccountUnbindingRequestAdditionalInfo getAdditionalInfo() {
    return additionalInfo;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAdditionalInfo(@javax.annotation.Nonnull AccountUnbindingRequestAdditionalInfo additionalInfo) {
    this.additionalInfo = additionalInfo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountUnbindingRequest accountUnbindingRequest = (AccountUnbindingRequest) o;
    return Objects.equals(this.merchantId, accountUnbindingRequest.merchantId) &&
        Objects.equals(this.subMerchantId, accountUnbindingRequest.subMerchantId) &&
        Objects.equals(this.partnerReferenceNo, accountUnbindingRequest.partnerReferenceNo) &&
        Objects.equals(this.linkId, accountUnbindingRequest.linkId) &&
        Objects.equals(this.tokenId, accountUnbindingRequest.tokenId) &&
        Objects.equals(this.additionalInfo, accountUnbindingRequest.additionalInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchantId, subMerchantId, partnerReferenceNo, linkId, tokenId, additionalInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountUnbindingRequest {\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    subMerchantId: ").append(toIndentedString(subMerchantId)).append("\n");
    sb.append("    partnerReferenceNo: ").append(toIndentedString(partnerReferenceNo)).append("\n");
    sb.append("    linkId: ").append(toIndentedString(linkId)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    additionalInfo: ").append(toIndentedString(additionalInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
