/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.widget.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Additional information
 */
@JsonPropertyOrder({
  ApplyOTTRequestAdditionalInfo.JSON_PROPERTY_ACCESS_TOKEN,
  ApplyOTTRequestAdditionalInfo.JSON_PROPERTY_END_USER_IP_ADDRESS,
  ApplyOTTRequestAdditionalInfo.JSON_PROPERTY_DEVICE_ID,
  ApplyOTTRequestAdditionalInfo.JSON_PROPERTY_LATITUDE,
  ApplyOTTRequestAdditionalInfo.JSON_PROPERTY_LONGITUDE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class ApplyOTTRequestAdditionalInfo {
  public static final String JSON_PROPERTY_ACCESS_TOKEN = "accessToken";
  @javax.annotation.Nonnull
  private String accessToken;

  public static final String JSON_PROPERTY_END_USER_IP_ADDRESS = "endUserIpAddress";
  @javax.annotation.Nullable
  private String endUserIpAddress;

  public static final String JSON_PROPERTY_DEVICE_ID = "deviceId";
  @javax.annotation.Nonnull
  private String deviceId;

  public static final String JSON_PROPERTY_LATITUDE = "latitude";
  @javax.annotation.Nullable
  private String latitude;

  public static final String JSON_PROPERTY_LONGITUDE = "longitude";
  @javax.annotation.Nullable
  private String longitude;

  public ApplyOTTRequestAdditionalInfo() {
  }

  public ApplyOTTRequestAdditionalInfo accessToken(@javax.annotation.Nonnull String accessToken) {
    
    this.accessToken = accessToken;
    return this;
  }

  /**
   * Contains customer token, which has been obtained from binding process
   * @return accessToken
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACCESS_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAccessToken() {
    return accessToken;
  }


  @JsonProperty(JSON_PROPERTY_ACCESS_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccessToken(@javax.annotation.Nonnull String accessToken) {
    this.accessToken = accessToken;
  }

  public ApplyOTTRequestAdditionalInfo endUserIpAddress(@javax.annotation.Nullable String endUserIpAddress) {
    
    this.endUserIpAddress = endUserIpAddress;
    return this;
  }

  /**
   * IP address of the end user (customer) using IPv4 format
   * @return endUserIpAddress
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END_USER_IP_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEndUserIpAddress() {
    return endUserIpAddress;
  }


  @JsonProperty(JSON_PROPERTY_END_USER_IP_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndUserIpAddress(@javax.annotation.Nullable String endUserIpAddress) {
    this.endUserIpAddress = endUserIpAddress;
  }

  public ApplyOTTRequestAdditionalInfo deviceId(@javax.annotation.Nonnull String deviceId) {
    
    this.deviceId = deviceId;
    return this;
  }

  /**
   * Device identification on which the API services is currently being accessed by the end user (customer)
   * @return deviceId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DEVICE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDeviceId() {
    return deviceId;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeviceId(@javax.annotation.Nonnull String deviceId) {
    this.deviceId = deviceId;
  }

  public ApplyOTTRequestAdditionalInfo latitude(@javax.annotation.Nullable String latitude) {
    
    this.latitude = latitude;
    return this;
  }

  /**
   * Location on which the API services is currently being accessed by the end user (customer), refer to ISO 6709 standard representation of geographic point location by coordinates
   * @return latitude
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LATITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLatitude() {
    return latitude;
  }


  @JsonProperty(JSON_PROPERTY_LATITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatitude(@javax.annotation.Nullable String latitude) {
    this.latitude = latitude;
  }

  public ApplyOTTRequestAdditionalInfo longitude(@javax.annotation.Nullable String longitude) {
    
    this.longitude = longitude;
    return this;
  }

  /**
   * Location on which the API services is currently being accessed by the end user (customer), refer to ISO 6709 Standard representation of geographic point location by coordinates
   * @return longitude
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LONGITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLongitude() {
    return longitude;
  }


  @JsonProperty(JSON_PROPERTY_LONGITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLongitude(@javax.annotation.Nullable String longitude) {
    this.longitude = longitude;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplyOTTRequestAdditionalInfo applyOTTRequestAdditionalInfo = (ApplyOTTRequestAdditionalInfo) o;
    return Objects.equals(this.accessToken, applyOTTRequestAdditionalInfo.accessToken) &&
        Objects.equals(this.endUserIpAddress, applyOTTRequestAdditionalInfo.endUserIpAddress) &&
        Objects.equals(this.deviceId, applyOTTRequestAdditionalInfo.deviceId) &&
        Objects.equals(this.latitude, applyOTTRequestAdditionalInfo.latitude) &&
        Objects.equals(this.longitude, applyOTTRequestAdditionalInfo.longitude);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessToken, endUserIpAddress, deviceId, latitude, longitude);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplyOTTRequestAdditionalInfo {\n");
    sb.append("    accessToken: ").append(toIndentedString(accessToken)).append("\n");
    sb.append("    endUserIpAddress: ").append(toIndentedString(endUserIpAddress)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
