/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.widget.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Additional information of user. Contains publicUserId
 */
@JsonPropertyOrder({
  ApplyTokenResponseAdditionalInfoUserInfo.JSON_PROPERTY_PUBLIC_USER_ID
})
@JsonTypeName("ApplyTokenResponseAdditionalInfo_userInfo")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class ApplyTokenResponseAdditionalInfoUserInfo {
  public static final String JSON_PROPERTY_PUBLIC_USER_ID = "publicUserId";
  @javax.annotation.Nullable
  private String publicUserId;

  public ApplyTokenResponseAdditionalInfoUserInfo() {
  }

  public ApplyTokenResponseAdditionalInfoUserInfo publicUserId(@javax.annotation.Nullable String publicUserId) {
    
    this.publicUserId = publicUserId;
    return this;
  }

  /**
   * Static unique identifier for one user
   * @return publicUserId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLIC_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPublicUserId() {
    return publicUserId;
  }


  @JsonProperty(JSON_PROPERTY_PUBLIC_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublicUserId(@javax.annotation.Nullable String publicUserId) {
    this.publicUserId = publicUserId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplyTokenResponseAdditionalInfoUserInfo applyTokenResponseAdditionalInfoUserInfo = (ApplyTokenResponseAdditionalInfoUserInfo) o;
    return Objects.equals(this.publicUserId, applyTokenResponseAdditionalInfoUserInfo.publicUserId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(publicUserId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplyTokenResponseAdditionalInfoUserInfo {\n");
    sb.append("    publicUserId: ").append(toIndentedString(publicUserId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

