/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.widget.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.dana.widget.v1.model.BalanceInquiryRequestAdditionalInfo;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BalanceInquiryRequest
 */
@JsonPropertyOrder({
  BalanceInquiryRequest.JSON_PROPERTY_PARTNER_REFERENCE_NO,
  BalanceInquiryRequest.JSON_PROPERTY_BALANCE_TYPES,
  BalanceInquiryRequest.JSON_PROPERTY_ADDITIONAL_INFO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class BalanceInquiryRequest {
  public static final String JSON_PROPERTY_PARTNER_REFERENCE_NO = "partnerReferenceNo";
  @javax.annotation.Nullable
  private String partnerReferenceNo;

  public static final String JSON_PROPERTY_BALANCE_TYPES = "balanceTypes";
  @javax.annotation.Nullable
  private List<String> balanceTypes = new ArrayList<>();

  public static final String JSON_PROPERTY_ADDITIONAL_INFO = "additionalInfo";
  @javax.annotation.Nonnull
  private BalanceInquiryRequestAdditionalInfo additionalInfo;

  public BalanceInquiryRequest() {
  }

  public BalanceInquiryRequest partnerReferenceNo(@javax.annotation.Nullable String partnerReferenceNo) {
    
    this.partnerReferenceNo = partnerReferenceNo;
    return this;
  }

  /**
   * Unique transaction identifier on partner system which assigned to each transaction<br> Notes:<br> If the partner receives a timeout or an unexpected response from DANA and partner expects to perform retry request to DANA, please use the partnerReferenceNo that is the same as the one used in the transaction request process before 
   * @return partnerReferenceNo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARTNER_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPartnerReferenceNo() {
    return partnerReferenceNo;
  }


  @JsonProperty(JSON_PROPERTY_PARTNER_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPartnerReferenceNo(@javax.annotation.Nullable String partnerReferenceNo) {
    this.partnerReferenceNo = partnerReferenceNo;
  }

  public BalanceInquiryRequest balanceTypes(@javax.annotation.Nullable List<String> balanceTypes) {
    
    this.balanceTypes = balanceTypes;
    return this;
  }

  public BalanceInquiryRequest addBalanceTypesItem(String balanceTypesItem) {
    if (this.balanceTypes == null) {
      this.balanceTypes = new ArrayList<>();
    }
    this.balanceTypes.add(balanceTypesItem);
    return this;
  }

  /**
   * Information of balance types to specify which balance type expected to be returned. Will return all available balance type if this parameter empty
   * @return balanceTypes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BALANCE_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getBalanceTypes() {
    return balanceTypes;
  }


  @JsonProperty(JSON_PROPERTY_BALANCE_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBalanceTypes(@javax.annotation.Nullable List<String> balanceTypes) {
    this.balanceTypes = balanceTypes;
  }

  public BalanceInquiryRequest additionalInfo(@javax.annotation.Nonnull BalanceInquiryRequestAdditionalInfo additionalInfo) {
    
    this.additionalInfo = additionalInfo;
    return this;
  }

  /**
   * Additional information
   * @return additionalInfo
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BalanceInquiryRequestAdditionalInfo getAdditionalInfo() {
    return additionalInfo;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAdditionalInfo(@javax.annotation.Nonnull BalanceInquiryRequestAdditionalInfo additionalInfo) {
    this.additionalInfo = additionalInfo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BalanceInquiryRequest balanceInquiryRequest = (BalanceInquiryRequest) o;
    return Objects.equals(this.partnerReferenceNo, balanceInquiryRequest.partnerReferenceNo) &&
        Objects.equals(this.balanceTypes, balanceInquiryRequest.balanceTypes) &&
        Objects.equals(this.additionalInfo, balanceInquiryRequest.additionalInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(partnerReferenceNo, balanceTypes, additionalInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BalanceInquiryRequest {\n");
    sb.append("    partnerReferenceNo: ").append(toIndentedString(partnerReferenceNo)).append("\n");
    sb.append("    balanceTypes: ").append(toIndentedString(balanceTypes)).append("\n");
    sb.append("    additionalInfo: ").append(toIndentedString(additionalInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
