/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.widget.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.dana.widget.v1.model.Money;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CancelOrderRequest
 */
@JsonPropertyOrder({
  CancelOrderRequest.JSON_PROPERTY_ORIGINAL_PARTNER_REFERENCE_NO,
  CancelOrderRequest.JSON_PROPERTY_ORIGINAL_REFERENCE_NO,
  CancelOrderRequest.JSON_PROPERTY_ORIGINAL_EXTERNAL_ID,
  CancelOrderRequest.JSON_PROPERTY_MERCHANT_ID,
  CancelOrderRequest.JSON_PROPERTY_SUB_MERCHANT_ID,
  CancelOrderRequest.JSON_PROPERTY_REASON,
  CancelOrderRequest.JSON_PROPERTY_EXTERNAL_STORE_ID,
  CancelOrderRequest.JSON_PROPERTY_AMOUNT,
  CancelOrderRequest.JSON_PROPERTY_ADDITIONAL_INFO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class CancelOrderRequest {
  public static final String JSON_PROPERTY_ORIGINAL_PARTNER_REFERENCE_NO = "originalPartnerReferenceNo";
  @javax.annotation.Nonnull
  private String originalPartnerReferenceNo;

  public static final String JSON_PROPERTY_ORIGINAL_REFERENCE_NO = "originalReferenceNo";
  @javax.annotation.Nullable
  private String originalReferenceNo;

  public static final String JSON_PROPERTY_ORIGINAL_EXTERNAL_ID = "originalExternalId";
  @javax.annotation.Nullable
  private String originalExternalId;

  public static final String JSON_PROPERTY_MERCHANT_ID = "merchantId";
  @javax.annotation.Nonnull
  private String merchantId;

  public static final String JSON_PROPERTY_SUB_MERCHANT_ID = "subMerchantId";
  @javax.annotation.Nullable
  private String subMerchantId;

  public static final String JSON_PROPERTY_REASON = "reason";
  @javax.annotation.Nullable
  private String reason;

  public static final String JSON_PROPERTY_EXTERNAL_STORE_ID = "externalStoreId";
  @javax.annotation.Nullable
  private String externalStoreId;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @javax.annotation.Nullable
  private Money amount;

  public static final String JSON_PROPERTY_ADDITIONAL_INFO = "additionalInfo";
  @javax.annotation.Nullable
  private Object additionalInfo;

  public CancelOrderRequest() {
  }

  public CancelOrderRequest originalPartnerReferenceNo(@javax.annotation.Nonnull String originalPartnerReferenceNo) {
    
    this.originalPartnerReferenceNo = originalPartnerReferenceNo;
    return this;
  }

  /**
   * Original transaction identifier on partner system
   * @return originalPartnerReferenceNo
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ORIGINAL_PARTNER_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOriginalPartnerReferenceNo() {
    return originalPartnerReferenceNo;
  }


  @JsonProperty(JSON_PROPERTY_ORIGINAL_PARTNER_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOriginalPartnerReferenceNo(@javax.annotation.Nonnull String originalPartnerReferenceNo) {
    this.originalPartnerReferenceNo = originalPartnerReferenceNo;
  }

  public CancelOrderRequest originalReferenceNo(@javax.annotation.Nullable String originalReferenceNo) {
    
    this.originalReferenceNo = originalReferenceNo;
    return this;
  }

  /**
   * Original transaction identifier on DANA system
   * @return originalReferenceNo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORIGINAL_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOriginalReferenceNo() {
    return originalReferenceNo;
  }


  @JsonProperty(JSON_PROPERTY_ORIGINAL_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOriginalReferenceNo(@javax.annotation.Nullable String originalReferenceNo) {
    this.originalReferenceNo = originalReferenceNo;
  }

  public CancelOrderRequest originalExternalId(@javax.annotation.Nullable String originalExternalId) {
    
    this.originalExternalId = originalExternalId;
    return this;
  }

  /**
   * Original external identifier on header message
   * @return originalExternalId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORIGINAL_EXTERNAL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOriginalExternalId() {
    return originalExternalId;
  }


  @JsonProperty(JSON_PROPERTY_ORIGINAL_EXTERNAL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOriginalExternalId(@javax.annotation.Nullable String originalExternalId) {
    this.originalExternalId = originalExternalId;
  }

  public CancelOrderRequest merchantId(@javax.annotation.Nonnull String merchantId) {
    
    this.merchantId = merchantId;
    return this;
  }

  /**
   * Merchant identifier that is unique per each merchant
   * @return merchantId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MERCHANT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMerchantId() {
    return merchantId;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMerchantId(@javax.annotation.Nonnull String merchantId) {
    this.merchantId = merchantId;
  }

  public CancelOrderRequest subMerchantId(@javax.annotation.Nullable String subMerchantId) {
    
    this.subMerchantId = subMerchantId;
    return this;
  }

  /**
   * Information of sub merchant identifier
   * @return subMerchantId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUB_MERCHANT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubMerchantId() {
    return subMerchantId;
  }


  @JsonProperty(JSON_PROPERTY_SUB_MERCHANT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubMerchantId(@javax.annotation.Nullable String subMerchantId) {
    this.subMerchantId = subMerchantId;
  }

  public CancelOrderRequest reason(@javax.annotation.Nullable String reason) {
    
    this.reason = reason;
    return this;
  }

  /**
   * Cancellation reason
   * @return reason
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReason() {
    return reason;
  }


  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReason(@javax.annotation.Nullable String reason) {
    this.reason = reason;
  }

  public CancelOrderRequest externalStoreId(@javax.annotation.Nullable String externalStoreId) {
    
    this.externalStoreId = externalStoreId;
    return this;
  }

  /**
   * Store identifier to indicate to which store this payment belongs to
   * @return externalStoreId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTERNAL_STORE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExternalStoreId() {
    return externalStoreId;
  }


  @JsonProperty(JSON_PROPERTY_EXTERNAL_STORE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalStoreId(@javax.annotation.Nullable String externalStoreId) {
    this.externalStoreId = externalStoreId;
  }

  public CancelOrderRequest amount(@javax.annotation.Nullable Money amount) {
    
    this.amount = amount;
    return this;
  }

  /**
   * Amount. Contains two sub fields - Value (Transaction amount, including the cents) and Currency (Currency code based on ISO 4217)
   * @return amount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Money getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmount(@javax.annotation.Nullable Money amount) {
    this.amount = amount;
  }

  public CancelOrderRequest additionalInfo(@javax.annotation.Nullable Object additionalInfo) {
    
    this.additionalInfo = additionalInfo;
    return this;
  }

  /**
   * Additional information
   * @return additionalInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getAdditionalInfo() {
    return additionalInfo;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalInfo(@javax.annotation.Nullable Object additionalInfo) {
    this.additionalInfo = additionalInfo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CancelOrderRequest cancelOrderRequest = (CancelOrderRequest) o;
    return Objects.equals(this.originalPartnerReferenceNo, cancelOrderRequest.originalPartnerReferenceNo) &&
        Objects.equals(this.originalReferenceNo, cancelOrderRequest.originalReferenceNo) &&
        Objects.equals(this.originalExternalId, cancelOrderRequest.originalExternalId) &&
        Objects.equals(this.merchantId, cancelOrderRequest.merchantId) &&
        Objects.equals(this.subMerchantId, cancelOrderRequest.subMerchantId) &&
        Objects.equals(this.reason, cancelOrderRequest.reason) &&
        Objects.equals(this.externalStoreId, cancelOrderRequest.externalStoreId) &&
        Objects.equals(this.amount, cancelOrderRequest.amount) &&
        Objects.equals(this.additionalInfo, cancelOrderRequest.additionalInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(originalPartnerReferenceNo, originalReferenceNo, originalExternalId, merchantId, subMerchantId, reason, externalStoreId, amount, additionalInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CancelOrderRequest {\n");
    sb.append("    originalPartnerReferenceNo: ").append(toIndentedString(originalPartnerReferenceNo)).append("\n");
    sb.append("    originalReferenceNo: ").append(toIndentedString(originalReferenceNo)).append("\n");
    sb.append("    originalExternalId: ").append(toIndentedString(originalExternalId)).append("\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    subMerchantId: ").append(toIndentedString(subMerchantId)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    externalStoreId: ").append(toIndentedString(externalStoreId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    additionalInfo: ").append(toIndentedString(additionalInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

