/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.widget.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.dana.widget.v1.model.Money;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Goods
 */
@JsonPropertyOrder({
  Goods.JSON_PROPERTY_NAME,
  Goods.JSON_PROPERTY_MERCHANT_GOODS_ID,
  Goods.JSON_PROPERTY_DESCRIPTION,
  Goods.JSON_PROPERTY_CATEGORY,
  Goods.JSON_PROPERTY_PRICE,
  Goods.JSON_PROPERTY_UNIT,
  Goods.JSON_PROPERTY_QUANTITY,
  Goods.JSON_PROPERTY_MERCHANT_SHIPPING_ID,
  Goods.JSON_PROPERTY_SNAPSHOT_URL,
  Goods.JSON_PROPERTY_EXTEND_INFO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class Goods {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_MERCHANT_GOODS_ID = "merchantGoodsId";
  @javax.annotation.Nonnull
  private String merchantGoodsId;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nonnull
  private String description;

  public static final String JSON_PROPERTY_CATEGORY = "category";
  @javax.annotation.Nonnull
  private String category;

  public static final String JSON_PROPERTY_PRICE = "price";
  @javax.annotation.Nonnull
  private Money price;

  public static final String JSON_PROPERTY_UNIT = "unit";
  @javax.annotation.Nullable
  private String unit;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  @javax.annotation.Nonnull
  private String quantity;

  public static final String JSON_PROPERTY_MERCHANT_SHIPPING_ID = "merchantShippingId";
  @javax.annotation.Nullable
  private String merchantShippingId;

  public static final String JSON_PROPERTY_SNAPSHOT_URL = "snapshotUrl";
  @javax.annotation.Nullable
  private String snapshotUrl;

  public static final String JSON_PROPERTY_EXTEND_INFO = "extendInfo";
  @javax.annotation.Nullable
  private String extendInfo;

  public Goods() {
  }

  public Goods name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Goods name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public Goods merchantGoodsId(@javax.annotation.Nonnull String merchantGoodsId) {
    
    this.merchantGoodsId = merchantGoodsId;
    return this;
  }

  /**
   * Goods identifier provided by merchant
   * @return merchantGoodsId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MERCHANT_GOODS_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMerchantGoodsId() {
    return merchantGoodsId;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_GOODS_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMerchantGoodsId(@javax.annotation.Nonnull String merchantGoodsId) {
    this.merchantGoodsId = merchantGoodsId;
  }

  public Goods description(@javax.annotation.Nonnull String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Goods description
   * @return description
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(@javax.annotation.Nonnull String description) {
    this.description = description;
  }

  public Goods category(@javax.annotation.Nonnull String category) {
    
    this.category = category;
    return this;
  }

  /**
   * Goods category
   * @return category
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCategory() {
    return category;
  }


  @JsonProperty(JSON_PROPERTY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCategory(@javax.annotation.Nonnull String category) {
    this.category = category;
  }

  public Goods price(@javax.annotation.Nonnull Money price) {
    
    this.price = price;
    return this;
  }

  /**
   * Goods price. Contains two sub-fields:<br> 1. Value: Transaction amount, including the cents<br> 2. Currency: Currency code based on ISO<br> 
   * @return price
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Money getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrice(@javax.annotation.Nonnull Money price) {
    this.price = price;
  }

  public Goods unit(@javax.annotation.Nullable String unit) {
    
    this.unit = unit;
    return this;
  }

  /**
   * Goods unit
   * @return unit
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnit() {
    return unit;
  }


  @JsonProperty(JSON_PROPERTY_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnit(@javax.annotation.Nullable String unit) {
    this.unit = unit;
  }

  public Goods quantity(@javax.annotation.Nonnull String quantity) {
    
    this.quantity = quantity;
    return this;
  }

  /**
   * Count of items
   * @return quantity
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getQuantity() {
    return quantity;
  }


  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuantity(@javax.annotation.Nonnull String quantity) {
    this.quantity = quantity;
  }

  public Goods merchantShippingId(@javax.annotation.Nullable String merchantShippingId) {
    
    this.merchantShippingId = merchantShippingId;
    return this;
  }

  /**
   * Shipment identifier provided by merchant
   * @return merchantShippingId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MERCHANT_SHIPPING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMerchantShippingId() {
    return merchantShippingId;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_SHIPPING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchantShippingId(@javax.annotation.Nullable String merchantShippingId) {
    this.merchantShippingId = merchantShippingId;
  }

  public Goods snapshotUrl(@javax.annotation.Nullable String snapshotUrl) {
    
    this.snapshotUrl = snapshotUrl;
    return this;
  }

  /**
   * The URL of good's snapshot web page
   * @return snapshotUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SNAPSHOT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSnapshotUrl() {
    return snapshotUrl;
  }


  @JsonProperty(JSON_PROPERTY_SNAPSHOT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSnapshotUrl(@javax.annotation.Nullable String snapshotUrl) {
    this.snapshotUrl = snapshotUrl;
  }

  public Goods extendInfo(@javax.annotation.Nullable String extendInfo) {
    
    this.extendInfo = extendInfo;
    return this;
  }

  /**
   * Extend information
   * @return extendInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTEND_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExtendInfo() {
    return extendInfo;
  }


  @JsonProperty(JSON_PROPERTY_EXTEND_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtendInfo(@javax.annotation.Nullable String extendInfo) {
    this.extendInfo = extendInfo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Goods goods = (Goods) o;
    return Objects.equals(this.name, goods.name) &&
        Objects.equals(this.merchantGoodsId, goods.merchantGoodsId) &&
        Objects.equals(this.description, goods.description) &&
        Objects.equals(this.category, goods.category) &&
        Objects.equals(this.price, goods.price) &&
        Objects.equals(this.unit, goods.unit) &&
        Objects.equals(this.quantity, goods.quantity) &&
        Objects.equals(this.merchantShippingId, goods.merchantShippingId) &&
        Objects.equals(this.snapshotUrl, goods.snapshotUrl) &&
        Objects.equals(this.extendInfo, goods.extendInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, merchantGoodsId, description, category, price, unit, quantity, merchantShippingId, snapshotUrl, extendInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Goods {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    merchantGoodsId: ").append(toIndentedString(merchantGoodsId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    merchantShippingId: ").append(toIndentedString(merchantShippingId)).append("\n");
    sb.append("    snapshotUrl: ").append(toIndentedString(snapshotUrl)).append("\n");
    sb.append("    extendInfo: ").append(toIndentedString(extendInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
