/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.widget.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.dana.widget.v1.model.InternationalOrderInfoExchangeRate;
import id.dana.widget.v1.model.Money;
import id.dana.widget.v1.model.PaymentPromoInfo;
import id.dana.widget.v1.model.RefundPromoInfo;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Additional information for international orders (non-IDR currency transactions)
 */
@JsonPropertyOrder({
  InternationalOrderInfo.JSON_PROPERTY_ORIGIN_ORDER_AMOUNT,
  InternationalOrderInfo.JSON_PROPERTY_EXCHANGE_RATE,
  InternationalOrderInfo.JSON_PROPERTY_TOTAL_AMOUNT,
  InternationalOrderInfo.JSON_PROPERTY_PAYMENT_PROMO_INFO,
  InternationalOrderInfo.JSON_PROPERTY_REFUND_PROMO_INFO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class InternationalOrderInfo {
  public static final String JSON_PROPERTY_ORIGIN_ORDER_AMOUNT = "originOrderAmount";
  @javax.annotation.Nullable
  private Money originOrderAmount;

  public static final String JSON_PROPERTY_EXCHANGE_RATE = "exchangeRate";
  @javax.annotation.Nullable
  private InternationalOrderInfoExchangeRate exchangeRate;

  public static final String JSON_PROPERTY_TOTAL_AMOUNT = "totalAmount";
  @javax.annotation.Nullable
  private Money totalAmount;

  public static final String JSON_PROPERTY_PAYMENT_PROMO_INFO = "paymentPromoInfo";
  @javax.annotation.Nullable
  private PaymentPromoInfo paymentPromoInfo;

  public static final String JSON_PROPERTY_REFUND_PROMO_INFO = "refundPromoInfo";
  @javax.annotation.Nullable
  private RefundPromoInfo refundPromoInfo;

  public InternationalOrderInfo() {
  }

  public InternationalOrderInfo originOrderAmount(@javax.annotation.Nullable Money originOrderAmount) {
    
    this.originOrderAmount = originOrderAmount;
    return this;
  }

  /**
   * Origin order amount in the original currency. Contains value (amount including cents) and currency (code based on ISO)
   * @return originOrderAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORIGIN_ORDER_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Money getOriginOrderAmount() {
    return originOrderAmount;
  }


  @JsonProperty(JSON_PROPERTY_ORIGIN_ORDER_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOriginOrderAmount(@javax.annotation.Nullable Money originOrderAmount) {
    this.originOrderAmount = originOrderAmount;
  }

  public InternationalOrderInfo exchangeRate(@javax.annotation.Nullable InternationalOrderInfoExchangeRate exchangeRate) {
    
    this.exchangeRate = exchangeRate;
    return this;
  }

  /**
   * Get exchangeRate
   * @return exchangeRate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXCHANGE_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InternationalOrderInfoExchangeRate getExchangeRate() {
    return exchangeRate;
  }


  @JsonProperty(JSON_PROPERTY_EXCHANGE_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExchangeRate(@javax.annotation.Nullable InternationalOrderInfoExchangeRate exchangeRate) {
    this.exchangeRate = exchangeRate;
  }

  public InternationalOrderInfo totalAmount(@javax.annotation.Nullable Money totalAmount) {
    
    this.totalAmount = totalAmount;
    return this;
  }

  /**
   * Total amount after conversion. Contains value (amount including cents) and currency (code based on ISO)
   * @return totalAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Money getTotalAmount() {
    return totalAmount;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalAmount(@javax.annotation.Nullable Money totalAmount) {
    this.totalAmount = totalAmount;
  }

  public InternationalOrderInfo paymentPromoInfo(@javax.annotation.Nullable PaymentPromoInfo paymentPromoInfo) {
    
    this.paymentPromoInfo = paymentPromoInfo;
    return this;
  }

  /**
   * Define the detail of payment promo information, contains promotion that handled and set by merchant
   * @return paymentPromoInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_PROMO_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PaymentPromoInfo getPaymentPromoInfo() {
    return paymentPromoInfo;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_PROMO_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentPromoInfo(@javax.annotation.Nullable PaymentPromoInfo paymentPromoInfo) {
    this.paymentPromoInfo = paymentPromoInfo;
  }

  public InternationalOrderInfo refundPromoInfo(@javax.annotation.Nullable RefundPromoInfo refundPromoInfo) {
    
    this.refundPromoInfo = refundPromoInfo;
    return this;
  }

  /**
   * Define the detail of refund promo information
   * @return refundPromoInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFUND_PROMO_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RefundPromoInfo getRefundPromoInfo() {
    return refundPromoInfo;
  }


  @JsonProperty(JSON_PROPERTY_REFUND_PROMO_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefundPromoInfo(@javax.annotation.Nullable RefundPromoInfo refundPromoInfo) {
    this.refundPromoInfo = refundPromoInfo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InternationalOrderInfo internationalOrderInfo = (InternationalOrderInfo) o;
    return Objects.equals(this.originOrderAmount, internationalOrderInfo.originOrderAmount) &&
        Objects.equals(this.exchangeRate, internationalOrderInfo.exchangeRate) &&
        Objects.equals(this.totalAmount, internationalOrderInfo.totalAmount) &&
        Objects.equals(this.paymentPromoInfo, internationalOrderInfo.paymentPromoInfo) &&
        Objects.equals(this.refundPromoInfo, internationalOrderInfo.refundPromoInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(originOrderAmount, exchangeRate, totalAmount, paymentPromoInfo, refundPromoInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InternationalOrderInfo {\n");
    sb.append("    originOrderAmount: ").append(toIndentedString(originOrderAmount)).append("\n");
    sb.append("    exchangeRate: ").append(toIndentedString(exchangeRate)).append("\n");
    sb.append("    totalAmount: ").append(toIndentedString(totalAmount)).append("\n");
    sb.append("    paymentPromoInfo: ").append(toIndentedString(paymentPromoInfo)).append("\n");
    sb.append("    refundPromoInfo: ").append(toIndentedString(refundPromoInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
