/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.widget.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Define the detail of exchange rate information
 */
@JsonPropertyOrder({
  InternationalOrderInfoExchangeRate.JSON_PROPERTY_RATE,
  InternationalOrderInfoExchangeRate.JSON_PROPERTY_EXCHANGE_RELATION
})
@JsonTypeName("InternationalOrderInfo_exchangeRate")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class InternationalOrderInfoExchangeRate {
  public static final String JSON_PROPERTY_RATE = "rate";
  @javax.annotation.Nullable
  private String rate;

  public static final String JSON_PROPERTY_EXCHANGE_RELATION = "exchangeRelation";
  @javax.annotation.Nullable
  private String exchangeRelation;

  public InternationalOrderInfoExchangeRate() {
  }

  public InternationalOrderInfoExchangeRate rate(@javax.annotation.Nullable String rate) {
    
    this.rate = rate;
    return this;
  }

  /**
   * Rate of exchange value represents the relation between two currencies. For example, 15917.2690 indicates that one USD is equivalent to 15917.2690 IDR
   * @return rate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRate() {
    return rate;
  }


  @JsonProperty(JSON_PROPERTY_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRate(@javax.annotation.Nullable String rate) {
    this.rate = rate;
  }

  public InternationalOrderInfoExchangeRate exchangeRelation(@javax.annotation.Nullable String exchangeRelation) {
    
    this.exchangeRelation = exchangeRelation;
    return this;
  }

  /**
   * Exchange rate between two currencies. For example USD/IDR, refers to how much of one currency (in this case, Indonesian Rupiah or IDR) can be exchanged for one unit of another currency (in this case, US Dollar or USD)
   * @return exchangeRelation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXCHANGE_RELATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExchangeRelation() {
    return exchangeRelation;
  }


  @JsonProperty(JSON_PROPERTY_EXCHANGE_RELATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExchangeRelation(@javax.annotation.Nullable String exchangeRelation) {
    this.exchangeRelation = exchangeRelation;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InternationalOrderInfoExchangeRate internationalOrderInfoExchangeRate = (InternationalOrderInfoExchangeRate) o;
    return Objects.equals(this.rate, internationalOrderInfoExchangeRate.rate) &&
        Objects.equals(this.exchangeRelation, internationalOrderInfoExchangeRate.exchangeRelation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rate, exchangeRelation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InternationalOrderInfoExchangeRate {\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("    exchangeRelation: ").append(toIndentedString(exchangeRelation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
