/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.widget.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.dana.widget.v1.model.Buyer;
import id.dana.widget.v1.model.Goods;
import id.dana.widget.v1.model.InternationalOrderInfo;
import id.dana.widget.v1.model.Seller;
import id.dana.widget.v1.model.ShippingInfo;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Order
 */
@JsonPropertyOrder({
  Order.JSON_PROPERTY_BUYER,
  Order.JSON_PROPERTY_SELLER,
  Order.JSON_PROPERTY_ORDER_TITLE,
  Order.JSON_PROPERTY_MERCHANT_TRANS_TYPE,
  Order.JSON_PROPERTY_ORDER_MEMO,
  Order.JSON_PROPERTY_CREATED_TIME,
  Order.JSON_PROPERTY_GOODS,
  Order.JSON_PROPERTY_SHIPPING_INFO,
  Order.JSON_PROPERTY_INTERNATIONAL_ORDER_INFO,
  Order.JSON_PROPERTY_EXTEND_INFO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class Order {
  public static final String JSON_PROPERTY_BUYER = "buyer";
  @javax.annotation.Nullable
  private Buyer buyer;

  public static final String JSON_PROPERTY_SELLER = "seller";
  @javax.annotation.Nullable
  private Seller seller;

  public static final String JSON_PROPERTY_ORDER_TITLE = "orderTitle";
  @javax.annotation.Nonnull
  private String orderTitle;

  public static final String JSON_PROPERTY_MERCHANT_TRANS_TYPE = "merchantTransType";
  @javax.annotation.Nullable
  private String merchantTransType;

  public static final String JSON_PROPERTY_ORDER_MEMO = "orderMemo";
  @javax.annotation.Nullable
  private String orderMemo;

  public static final String JSON_PROPERTY_CREATED_TIME = "createdTime";
  @javax.annotation.Nullable
  private String createdTime;

  public static final String JSON_PROPERTY_GOODS = "goods";
  @javax.annotation.Nullable
  private List<Goods> goods = new ArrayList<>();

  public static final String JSON_PROPERTY_SHIPPING_INFO = "shippingInfo";
  @javax.annotation.Nullable
  private List<ShippingInfo> shippingInfo = new ArrayList<>();

  public static final String JSON_PROPERTY_INTERNATIONAL_ORDER_INFO = "internationalOrderInfo";
  @javax.annotation.Nullable
  private InternationalOrderInfo internationalOrderInfo;

  public static final String JSON_PROPERTY_EXTEND_INFO = "extendInfo";
  @javax.annotation.Nullable
  private String extendInfo;

  public Order() {
  }

  public Order buyer(@javax.annotation.Nullable Buyer buyer) {
    
    this.buyer = buyer;
    return this;
  }

  /**
   * Get buyer
   * @return buyer
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUYER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Buyer getBuyer() {
    return buyer;
  }


  @JsonProperty(JSON_PROPERTY_BUYER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuyer(@javax.annotation.Nullable Buyer buyer) {
    this.buyer = buyer;
  }

  public Order seller(@javax.annotation.Nullable Seller seller) {
    
    this.seller = seller;
    return this;
  }

  /**
   * Get seller
   * @return seller
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SELLER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Seller getSeller() {
    return seller;
  }


  @JsonProperty(JSON_PROPERTY_SELLER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeller(@javax.annotation.Nullable Seller seller) {
    this.seller = seller;
  }

  public Order orderTitle(@javax.annotation.Nonnull String orderTitle) {
    
    this.orderTitle = orderTitle;
    return this;
  }

  /**
   * Additional information of order title
   * @return orderTitle
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ORDER_TITLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOrderTitle() {
    return orderTitle;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_TITLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrderTitle(@javax.annotation.Nonnull String orderTitle) {
    this.orderTitle = orderTitle;
  }

  public Order merchantTransType(@javax.annotation.Nullable String merchantTransType) {
    
    this.merchantTransType = merchantTransType;
    return this;
  }

  /**
   * Additional information of merchant transaction type
   * @return merchantTransType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MERCHANT_TRANS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMerchantTransType() {
    return merchantTransType;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_TRANS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchantTransType(@javax.annotation.Nullable String merchantTransType) {
    this.merchantTransType = merchantTransType;
  }

  public Order orderMemo(@javax.annotation.Nullable String orderMemo) {
    
    this.orderMemo = orderMemo;
    return this;
  }

  /**
   * Additional information of order memo
   * @return orderMemo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER_MEMO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrderMemo() {
    return orderMemo;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_MEMO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderMemo(@javax.annotation.Nullable String orderMemo) {
    this.orderMemo = orderMemo;
  }

  public Order createdTime(@javax.annotation.Nullable String createdTime) {
    
    this.createdTime = createdTime;
    return this;
  }

  /**
   * Additional information of created time, in format YYYY-MM-DDTHH:mm:ss+07:00. Time must be in GMT+7 (Jakarta time)
   * @return createdTime
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedTime() {
    return createdTime;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedTime(@javax.annotation.Nullable String createdTime) {
    this.createdTime = createdTime;
  }

  public Order goods(@javax.annotation.Nullable List<Goods> goods) {
    
    this.goods = goods;
    return this;
  }

  public Order addGoodsItem(Goods goodsItem) {
    if (this.goods == null) {
      this.goods = new ArrayList<>();
    }
    this.goods.add(goodsItem);
    return this;
  }

  /**
   * Get goods
   * @return goods
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GOODS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Goods> getGoods() {
    return goods;
  }


  @JsonProperty(JSON_PROPERTY_GOODS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGoods(@javax.annotation.Nullable List<Goods> goods) {
    this.goods = goods;
  }

  public Order shippingInfo(@javax.annotation.Nullable List<ShippingInfo> shippingInfo) {
    
    this.shippingInfo = shippingInfo;
    return this;
  }

  public Order addShippingInfoItem(ShippingInfo shippingInfoItem) {
    if (this.shippingInfo == null) {
      this.shippingInfo = new ArrayList<>();
    }
    this.shippingInfo.add(shippingInfoItem);
    return this;
  }

  /**
   * Additional information of shipping
   * @return shippingInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHIPPING_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ShippingInfo> getShippingInfo() {
    return shippingInfo;
  }


  @JsonProperty(JSON_PROPERTY_SHIPPING_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShippingInfo(@javax.annotation.Nullable List<ShippingInfo> shippingInfo) {
    this.shippingInfo = shippingInfo;
  }

  public Order internationalOrderInfo(@javax.annotation.Nullable InternationalOrderInfo internationalOrderInfo) {
    
    this.internationalOrderInfo = internationalOrderInfo;
    return this;
  }

  /**
   * Additional information of international order. Only use for Mini Program service
   * @return internationalOrderInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTERNATIONAL_ORDER_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InternationalOrderInfo getInternationalOrderInfo() {
    return internationalOrderInfo;
  }


  @JsonProperty(JSON_PROPERTY_INTERNATIONAL_ORDER_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInternationalOrderInfo(@javax.annotation.Nullable InternationalOrderInfo internationalOrderInfo) {
    this.internationalOrderInfo = internationalOrderInfo;
  }

  public Order extendInfo(@javax.annotation.Nullable String extendInfo) {
    
    this.extendInfo = extendInfo;
    return this;
  }

  /**
   * Additional information of extend
   * @return extendInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTEND_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExtendInfo() {
    return extendInfo;
  }


  @JsonProperty(JSON_PROPERTY_EXTEND_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtendInfo(@javax.annotation.Nullable String extendInfo) {
    this.extendInfo = extendInfo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Order order = (Order) o;
    return Objects.equals(this.buyer, order.buyer) &&
        Objects.equals(this.seller, order.seller) &&
        Objects.equals(this.orderTitle, order.orderTitle) &&
        Objects.equals(this.merchantTransType, order.merchantTransType) &&
        Objects.equals(this.orderMemo, order.orderMemo) &&
        Objects.equals(this.createdTime, order.createdTime) &&
        Objects.equals(this.goods, order.goods) &&
        Objects.equals(this.shippingInfo, order.shippingInfo) &&
        Objects.equals(this.internationalOrderInfo, order.internationalOrderInfo) &&
        Objects.equals(this.extendInfo, order.extendInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(buyer, seller, orderTitle, merchantTransType, orderMemo, createdTime, goods, shippingInfo, internationalOrderInfo, extendInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Order {\n");
    sb.append("    buyer: ").append(toIndentedString(buyer)).append("\n");
    sb.append("    seller: ").append(toIndentedString(seller)).append("\n");
    sb.append("    orderTitle: ").append(toIndentedString(orderTitle)).append("\n");
    sb.append("    merchantTransType: ").append(toIndentedString(merchantTransType)).append("\n");
    sb.append("    orderMemo: ").append(toIndentedString(orderMemo)).append("\n");
    sb.append("    createdTime: ").append(toIndentedString(createdTime)).append("\n");
    sb.append("    goods: ").append(toIndentedString(goods)).append("\n");
    sb.append("    shippingInfo: ").append(toIndentedString(shippingInfo)).append("\n");
    sb.append("    internationalOrderInfo: ").append(toIndentedString(internationalOrderInfo)).append("\n");
    sb.append("    extendInfo: ").append(toIndentedString(extendInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
