/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.widget.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.dana.widget.v1.model.Money;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Information about the payment promotion that was applied
 */
@JsonPropertyOrder({
  PaymentPromoInfo.JSON_PROPERTY_PROMO_ID,
  PaymentPromoInfo.JSON_PROPERTY_PROMO_NAME,
  PaymentPromoInfo.JSON_PROPERTY_PROMO_TYPE,
  PaymentPromoInfo.JSON_PROPERTY_SAVINGS_AMOUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class PaymentPromoInfo {
  public static final String JSON_PROPERTY_PROMO_ID = "promoId";
  @javax.annotation.Nonnull
  private String promoId;

  public static final String JSON_PROPERTY_PROMO_NAME = "promoName";
  @javax.annotation.Nonnull
  private String promoName;

  /**
   * Type of promotion
   */
  public enum PromoTypeEnum {
    CASH_BACK(String.valueOf("CASH_BACK")),
    
    DISCOUNT(String.valueOf("DISCOUNT")),
    
    VOUCHER(String.valueOf("VOUCHER")),
    
    POINT(String.valueOf("POINT")),
    
    UNSPECIFIED(String.valueOf(""));

    private String value;

    PromoTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PromoTypeEnum fromValue(String value) {
      for (PromoTypeEnum b : PromoTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PROMO_TYPE = "promoType";
  @javax.annotation.Nonnull
  private PromoTypeEnum promoType;

  public static final String JSON_PROPERTY_SAVINGS_AMOUNT = "savingsAmount";
  @javax.annotation.Nonnull
  private Money savingsAmount;

  public PaymentPromoInfo() {
  }

  public PaymentPromoInfo promoId(@javax.annotation.Nonnull String promoId) {
    
    this.promoId = promoId;
    return this;
  }

  /**
   * Promotion identifier
   * @return promoId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROMO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPromoId() {
    return promoId;
  }


  @JsonProperty(JSON_PROPERTY_PROMO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPromoId(@javax.annotation.Nonnull String promoId) {
    this.promoId = promoId;
  }

  public PaymentPromoInfo promoName(@javax.annotation.Nonnull String promoName) {
    
    this.promoName = promoName;
    return this;
  }

  /**
   * Promotion name
   * @return promoName
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROMO_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPromoName() {
    return promoName;
  }


  @JsonProperty(JSON_PROPERTY_PROMO_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPromoName(@javax.annotation.Nonnull String promoName) {
    this.promoName = promoName;
  }

  public PaymentPromoInfo promoType(@javax.annotation.Nonnull PromoTypeEnum promoType) {
    
    this.promoType = promoType;
    return this;
  }

  /**
   * Type of promotion
   * @return promoType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROMO_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PromoTypeEnum getPromoType() {
    return promoType;
  }


  @JsonProperty(JSON_PROPERTY_PROMO_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPromoType(@javax.annotation.Nonnull PromoTypeEnum promoType) {
    this.promoType = promoType;
  }

  public PaymentPromoInfo savingsAmount(@javax.annotation.Nonnull Money savingsAmount) {
    
    this.savingsAmount = savingsAmount;
    return this;
  }

  /**
   * Savings amount from this promotion. Contains value (amount including cents) and currency (code based on ISO)
   * @return savingsAmount
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SAVINGS_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Money getSavingsAmount() {
    return savingsAmount;
  }


  @JsonProperty(JSON_PROPERTY_SAVINGS_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSavingsAmount(@javax.annotation.Nonnull Money savingsAmount) {
    this.savingsAmount = savingsAmount;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentPromoInfo paymentPromoInfo = (PaymentPromoInfo) o;
    return Objects.equals(this.promoId, paymentPromoInfo.promoId) &&
        Objects.equals(this.promoName, paymentPromoInfo.promoName) &&
        Objects.equals(this.promoType, paymentPromoInfo.promoType) &&
        Objects.equals(this.savingsAmount, paymentPromoInfo.savingsAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(promoId, promoName, promoType, savingsAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentPromoInfo {\n");
    sb.append("    promoId: ").append(toIndentedString(promoId)).append("\n");
    sb.append("    promoName: ").append(toIndentedString(promoName)).append("\n");
    sb.append("    promoType: ").append(toIndentedString(promoType)).append("\n");
    sb.append("    savingsAmount: ").append(toIndentedString(savingsAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

