/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.widget.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.dana.widget.v1.model.Money;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PayOptionInfo
 */
@JsonPropertyOrder({
  PayOptionInfo.JSON_PROPERTY_PAY_METHOD,
  PayOptionInfo.JSON_PROPERTY_PAY_OPTION,
  PayOptionInfo.JSON_PROPERTY_PAY_AMOUNT,
  PayOptionInfo.JSON_PROPERTY_TRANS_AMOUNT,
  PayOptionInfo.JSON_PROPERTY_CHARGE_AMOUNT,
  PayOptionInfo.JSON_PROPERTY_PAY_OPTION_BILL_EXTEND_INFO,
  PayOptionInfo.JSON_PROPERTY_EXTEND_INFO,
  PayOptionInfo.JSON_PROPERTY_PAYMENT_CODE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class PayOptionInfo {
  /**
   * Payment method name. The enums:<br>   * BALANCE - Payment method with balance<br>   * COUPON - Payment method with coupon<br>   * NET_BANKING - Payment method with internet banking<br>   * CREDIT_CARD - Payment method with credit card<br>   * DEBIT_CARD - Payment method with debit card<br>   * VIRTUAL_ACCOUNT - Payment method with virtual account<br>   * OTC - Payment method with OTC<br>   * DIRECT_DEBIT_CREDIT_CARD - Payment method with direct debit of credit card<br>   * DIRECT_DEBIT_DEBIT_CARD - Payment method with direct debit of debit card<br>   * ONLINE_CREDIT - Payment method with online Credit<br>   * LOAN_CREDIT - Payment method with DANA Cicil<br>   * NETWORK_PAY - Payment method with e-wallet   * CARD - Payment method with Card 
   */
  public enum PayMethodEnum {
    /**
     * Payment method with balance
     */
    BALANCE(String.valueOf("BALANCE")),
    
    /**
     * Payment method with coupon
     */
    COUPON(String.valueOf("COUPON")),
    
    /**
     * Payment method with internet banking
     */
    NET_BANKING(String.valueOf("NET_BANKING")),
    
    /**
     * Payment method with credit card
     */
    CREDIT_CARD(String.valueOf("CREDIT_CARD")),
    
    /**
     * Payment method with debit card
     */
    DEBIT_CARD(String.valueOf("DEBIT_CARD")),
    
    /**
     * Payment method with virtual account
     */
    VIRTUAL_ACCOUNT(String.valueOf("VIRTUAL_ACCOUNT")),
    
    /**
     * Payment method with OTC
     */
    OTC(String.valueOf("OTC")),
    
    /**
     * Payment method with direct debit of credit card
     */
    DIRECT_DEBIT_CREDIT_CARD(String.valueOf("DIRECT_DEBIT_CREDIT_CARD")),
    
    /**
     * Payment method with direct debit of debit card
     */
    DIRECT_DEBIT_DEBIT_CARD(String.valueOf("DIRECT_DEBIT_DEBIT_CARD")),
    
    /**
     * Payment method with online Credit
     */
    ONLINE_CREDIT(String.valueOf("ONLINE_CREDIT")),
    
    /**
     * Payment method with DANA Cicil
     */
    LOAN_CREDIT(String.valueOf("LOAN_CREDIT")),
    
    /**
     * Payment method with e-wallet
     */
    NETWORK_PAY(String.valueOf("NETWORK_PAY")),
    
    /**
     * Payment method with Card
     */
    CARD(String.valueOf("CARD")),
    
    /**
     * To handle empty string value
     */
    UNSPECIFIED(String.valueOf(""));

    private String value;

    PayMethodEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PayMethodEnum fromValue(String value) {
      for (PayMethodEnum b : PayMethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public static final String JSON_PROPERTY_PAY_METHOD = "payMethod";
  @javax.annotation.Nonnull
  private PayMethodEnum payMethod;

  /**
   * Payment option which shows the provider of this payment. The enums:<br>   * NETWORK_PAY_PG_SPAY - Payment method with ShopeePay e-wallet<br>   * NETWORK_PAY_PG_OVO - Payment method with OVO e-wallet<br>   * NETWORK_PAY_PG_GOPAY - Payment method with GoPay e-wallet<br>   * NETWORK_PAY_PG_LINKAJA - Payment method with LinkAja e-wallet<br>   * NETWORK_PAY_PG_CARD - Payment method with Card<br>   * NETWORK_PAY_PC_INDOMARET - Payment method with Indomaret<br>   * NETWORK_PAY_PG_QRIS - Payment method with QRIS<br>   * VIRTUAL_ACCOUNT_BCA - Payment method with BCA virtual account<br>   * VIRTUAL_ACCOUNT_BNI - Payment method with BNI virtual account<br>   * VIRTUAL_ACCOUNT_MANDIRI - Payment method with Mandiri virtual account<br>   * VIRTUAL_ACCOUNT_BRI - Payment method with BRI virtual account<br>   * VIRTUAL_ACCOUNT_BTPN - Payment method with BTPN virtual account<br>   * VIRTUAL_ACCOUNT_CIMB - Payment method with CIMB virtual account<br>   * VIRTUAL_ACCOUNT_PERMATA - Payment method with Permata virtual account<br>   * VIRTUAL_ACCOUNT_PANI - Payment method with Panin virtual account<br> 
   */
  public enum PayOptionEnum {
    /**
     * Payment method with ShopeePay e-wallet
     */
    NETWORK_PAY_PG_SPAY(String.valueOf("NETWORK_PAY_PG_SPAY")),
    
    /**
     * Payment method with OVO e-wallet
     */
    NETWORK_PAY_PG_OVO(String.valueOf("NETWORK_PAY_PG_OVO")),
    
    /**
     * Payment method with GoPay e-wallet
     */
    NETWORK_PAY_PG_GOPAY(String.valueOf("NETWORK_PAY_PG_GOPAY")),
    
    /**
     * Payment method with LinkAja e-wallet
     */
    NETWORK_PAY_PG_LINKAJA(String.valueOf("NETWORK_PAY_PG_LINKAJA")),
    
    /**
     * Payment method with Card
     */
    NETWORK_PAY_PG_CARD(String.valueOf("NETWORK_PAY_PG_CARD")),
    
    /**
     * Payment method with Indomaret
     */
    NETWORK_PAY_PC_INDOMARET(String.valueOf("NETWORK_PAY_PC_INDOMARET")),
    
    /**
     * Payment method with QRIS
     */
    NETWORK_PAY_PG_QRIS(String.valueOf("NETWORK_PAY_PG_QRIS")),
    
    /**
     * Payment method with BCA virtual account
     */
    VIRTUAL_ACCOUNT_BCA(String.valueOf("VIRTUAL_ACCOUNT_BCA")),
    
    /**
     * Payment method with BNI virtual account
     */
    VIRTUAL_ACCOUNT_BNI(String.valueOf("VIRTUAL_ACCOUNT_BNI")),
    
    /**
     * Payment method with Mandiri virtual account
     */
    VIRTUAL_ACCOUNT_MANDIRI(String.valueOf("VIRTUAL_ACCOUNT_MANDIRI")),
    
    /**
     * Payment method with BRI virtual account
     */
    VIRTUAL_ACCOUNT_BRI(String.valueOf("VIRTUAL_ACCOUNT_BRI")),
    
    /**
     * Payment method with BTPN virtual account
     */
    VIRTUAL_ACCOUNT_BTPN(String.valueOf("VIRTUAL_ACCOUNT_BTPN")),
    
    /**
     * Payment method with CIMB virtual account
     */
    VIRTUAL_ACCOUNT_CIMB(String.valueOf("VIRTUAL_ACCOUNT_CIMB")),
    
    /**
     * Payment method with Permata virtual account
     */
    VIRTUAL_ACCOUNT_PERMATA(String.valueOf("VIRTUAL_ACCOUNT_PERMATA")),
    
    /**
     * Payment method with Panin virtual account
     */
    VIRTUAL_ACCOUNT_PANI(String.valueOf("VIRTUAL_ACCOUNT_PANI")),
    
    /**
     * To handle empty string value
     */
    UNSPECIFIED(String.valueOf(""));

    private String value;

    PayOptionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PayOptionEnum fromValue(String value) {
      for (PayOptionEnum b : PayOptionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public static final String JSON_PROPERTY_PAY_OPTION = "payOption";
  @javax.annotation.Nullable
  private PayOptionEnum payOption;

  public static final String JSON_PROPERTY_PAY_AMOUNT = "payAmount";
  @javax.annotation.Nullable
  private Money payAmount;

  public static final String JSON_PROPERTY_TRANS_AMOUNT = "transAmount";
  @javax.annotation.Nullable
  private Money transAmount;

  public static final String JSON_PROPERTY_CHARGE_AMOUNT = "chargeAmount";
  @javax.annotation.Nullable
  private Money chargeAmount;

  public static final String JSON_PROPERTY_PAY_OPTION_BILL_EXTEND_INFO = "payOptionBillExtendInfo";
  @javax.annotation.Nullable
  private String payOptionBillExtendInfo;

  public static final String JSON_PROPERTY_EXTEND_INFO = "extendInfo";
  @javax.annotation.Nullable
  private String extendInfo;

  public static final String JSON_PROPERTY_PAYMENT_CODE = "paymentCode";
  @javax.annotation.Nullable
  private String paymentCode;

  public PayOptionInfo() {
  }

  public PayOptionInfo payMethod(@javax.annotation.Nonnull PayMethodEnum payMethod) {
    
    this.payMethod = payMethod;
    return this;
  }

  /**
   * Payment method name. The enums:<br>   * BALANCE - Payment method with balance<br>   * COUPON - Payment method with coupon<br>   * NET_BANKING - Payment method with internet banking<br>   * CREDIT_CARD - Payment method with credit card<br>   * DEBIT_CARD - Payment method with debit card<br>   * VIRTUAL_ACCOUNT - Payment method with virtual account<br>   * OTC - Payment method with OTC<br>   * DIRECT_DEBIT_CREDIT_CARD - Payment method with direct debit of credit card<br>   * DIRECT_DEBIT_DEBIT_CARD - Payment method with direct debit of debit card<br>   * ONLINE_CREDIT - Payment method with online Credit<br>   * LOAN_CREDIT - Payment method with DANA Cicil<br>   * NETWORK_PAY - Payment method with e-wallet   * CARD - Payment method with Card 
   * @return payMethod
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAY_METHOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PayMethodEnum getPayMethod() {
    return payMethod;
  }


  @JsonProperty(JSON_PROPERTY_PAY_METHOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPayMethod(@javax.annotation.Nonnull PayMethodEnum payMethod) {
    this.payMethod = payMethod;
  }

  public PayOptionInfo payOption(@javax.annotation.Nullable PayOptionEnum payOption) {
    
    this.payOption = payOption;
    return this;
  }

  /**
   * Payment option which shows the provider of this payment. The enums:<br>   * NETWORK_PAY_PG_SPAY - Payment method with ShopeePay e-wallet<br>   * NETWORK_PAY_PG_OVO - Payment method with OVO e-wallet<br>   * NETWORK_PAY_PG_GOPAY - Payment method with GoPay e-wallet<br>   * NETWORK_PAY_PG_LINKAJA - Payment method with LinkAja e-wallet<br>   * NETWORK_PAY_PG_CARD - Payment method with Card<br>   * NETWORK_PAY_PC_INDOMARET - Payment method with Indomaret<br>   * NETWORK_PAY_PG_QRIS - Payment method with QRIS<br>   * VIRTUAL_ACCOUNT_BCA - Payment method with BCA virtual account<br>   * VIRTUAL_ACCOUNT_BNI - Payment method with BNI virtual account<br>   * VIRTUAL_ACCOUNT_MANDIRI - Payment method with Mandiri virtual account<br>   * VIRTUAL_ACCOUNT_BRI - Payment method with BRI virtual account<br>   * VIRTUAL_ACCOUNT_BTPN - Payment method with BTPN virtual account<br>   * VIRTUAL_ACCOUNT_CIMB - Payment method with CIMB virtual account<br>   * VIRTUAL_ACCOUNT_PERMATA - Payment method with Permata virtual account<br>   * VIRTUAL_ACCOUNT_PANI - Payment method with Panin virtual account<br> 
   * @return payOption
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAY_OPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PayOptionEnum getPayOption() {
    return payOption;
  }


  @JsonProperty(JSON_PROPERTY_PAY_OPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayOption(@javax.annotation.Nullable PayOptionEnum payOption) {
    this.payOption = payOption;
  }

  public PayOptionInfo payAmount(@javax.annotation.Nullable Money payAmount) {
    
    this.payAmount = payAmount;
    return this;
  }

  /**
   * Pay amount. Contains two sub-fields:<br> 1. Value: Transaction amount, including the cents<br> 2. Currency: Currency code based on ISO<br> 
   * @return payAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Money getPayAmount() {
    return payAmount;
  }


  @JsonProperty(JSON_PROPERTY_PAY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayAmount(@javax.annotation.Nullable Money payAmount) {
    this.payAmount = payAmount;
  }

  public PayOptionInfo transAmount(@javax.annotation.Nullable Money transAmount) {
    
    this.transAmount = transAmount;
    return this;
  }

  /**
   * Trans amount. Contains two sub-fields:<br> 1. Value: Transaction amount, including the cents<br> 2. Currency: Currency code based on ISO<br> 
   * @return transAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANS_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Money getTransAmount() {
    return transAmount;
  }


  @JsonProperty(JSON_PROPERTY_TRANS_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransAmount(@javax.annotation.Nullable Money transAmount) {
    this.transAmount = transAmount;
  }

  public PayOptionInfo chargeAmount(@javax.annotation.Nullable Money chargeAmount) {
    
    this.chargeAmount = chargeAmount;
    return this;
  }

  /**
   * Charge amount. Contains two sub-fields:<br> 1. Value: Transaction amount, including the cents<br> 2. Currency: Currency code based on ISO<br> 
   * @return chargeAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHARGE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Money getChargeAmount() {
    return chargeAmount;
  }


  @JsonProperty(JSON_PROPERTY_CHARGE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChargeAmount(@javax.annotation.Nullable Money chargeAmount) {
    this.chargeAmount = chargeAmount;
  }

  public PayOptionInfo payOptionBillExtendInfo(@javax.annotation.Nullable String payOptionBillExtendInfo) {
    
    this.payOptionBillExtendInfo = payOptionBillExtendInfo;
    return this;
  }

  /**
   * Extend information of pay option bill
   * @return payOptionBillExtendInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAY_OPTION_BILL_EXTEND_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPayOptionBillExtendInfo() {
    return payOptionBillExtendInfo;
  }


  @JsonProperty(JSON_PROPERTY_PAY_OPTION_BILL_EXTEND_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayOptionBillExtendInfo(@javax.annotation.Nullable String payOptionBillExtendInfo) {
    this.payOptionBillExtendInfo = payOptionBillExtendInfo;
  }

  public PayOptionInfo extendInfo(@javax.annotation.Nullable String extendInfo) {
    
    this.extendInfo = extendInfo;
    return this;
  }

  /**
   * Extend information
   * @return extendInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTEND_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExtendInfo() {
    return extendInfo;
  }


  @JsonProperty(JSON_PROPERTY_EXTEND_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtendInfo(@javax.annotation.Nullable String extendInfo) {
    this.extendInfo = extendInfo;
  }

  public PayOptionInfo paymentCode(@javax.annotation.Nullable String paymentCode) {
    
    this.paymentCode = paymentCode;
    return this;
  }

  /**
   * Payment code
   * @return paymentCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPaymentCode() {
    return paymentCode;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentCode(@javax.annotation.Nullable String paymentCode) {
    this.paymentCode = paymentCode;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayOptionInfo payOptionInfo = (PayOptionInfo) o;
    return Objects.equals(this.payMethod, payOptionInfo.payMethod) &&
        Objects.equals(this.payOption, payOptionInfo.payOption) &&
        Objects.equals(this.payAmount, payOptionInfo.payAmount) &&
        Objects.equals(this.transAmount, payOptionInfo.transAmount) &&
        Objects.equals(this.chargeAmount, payOptionInfo.chargeAmount) &&
        Objects.equals(this.payOptionBillExtendInfo, payOptionInfo.payOptionBillExtendInfo) &&
        Objects.equals(this.extendInfo, payOptionInfo.extendInfo) &&
        Objects.equals(this.paymentCode, payOptionInfo.paymentCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payMethod, payOption, payAmount, transAmount, chargeAmount, payOptionBillExtendInfo, extendInfo, paymentCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayOptionInfo {\n");
    sb.append("    payMethod: ").append(toIndentedString(payMethod)).append("\n");
    sb.append("    payOption: ").append(toIndentedString(payOption)).append("\n");
    sb.append("    payAmount: ").append(toIndentedString(payAmount)).append("\n");
    sb.append("    transAmount: ").append(toIndentedString(transAmount)).append("\n");
    sb.append("    chargeAmount: ").append(toIndentedString(chargeAmount)).append("\n");
    sb.append("    payOptionBillExtendInfo: ").append(toIndentedString(payOptionBillExtendInfo)).append("\n");
    sb.append("    extendInfo: ").append(toIndentedString(extendInfo)).append("\n");
    sb.append("    paymentCode: ").append(toIndentedString(paymentCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
