/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.widget.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UserResourceInfo
 */
@JsonPropertyOrder({
  UserResourceInfo.JSON_PROPERTY_RESOURCE_TYPE,
  UserResourceInfo.JSON_PROPERTY_VALUE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class UserResourceInfo {
  /**
   * Type of user resource
   */
  public enum ResourceTypeEnum {
    /**
     * Query balance of user in DANA
     */
    BALANCE(String.valueOf("BALANCE")),
    
    /**
     * Obtain the top up URL for merchant to redirect
     */
    TOPUP_URL(String.valueOf("TOPUP_URL")),
    
    /**
     * Obtain the transaction URL for merchant to redirect
     */
    TRANSACTION_URL(String.valueOf("TRANSACTION_URL")),
    
    /**
     * Obtain the OTT of URLs including TOPUP/TRANSACTION/CASHIER/CHECKOUT_URL
     */
    OTT(String.valueOf("OTT")),
    
    /**
     * The masked identifier from DANA side
     */
    MASK_DANA_ID(String.valueOf("MASK_DANA_ID")),
    
    /**
     * KYC level. 00 = KYC level 0, 02 = KYC level 2
     */
    USER_KYC(String.valueOf("USER_KYC")),
    
    /**
     * Login identifier of the user, currently it's only set to phone number
     */
    LOGIN_ID(String.valueOf("LOGIN_ID")),
    
    /**
     * The unmasked identifier from DANA side
     */
    CLEAR_TEXT_DANA_ID(String.valueOf("CLEAR_TEXT_DANA_ID")),
    
    /**
     * Nickname of the user in DANA
     */
    NICKNAME(String.valueOf("NICKNAME")),
    
    /**
     * Full name of the user in DANA
     */
    FULLNAME(String.valueOf("FULLNAME")),
    
    /**
     * KTP number of the user in DANA
     */
    KTP_NUMBER(String.valueOf("KTP_NUMBER")),
    
    /**
     * KTP photo binary data in base64 of the user in DANA
     */
    KTP_PHOTO_DATA(String.valueOf("KTP_PHOTO_DATA")),
    
    /**
     * Selfie photo binary data in base64 of the user in DANA
     */
    SELFIE_PHOTO_DATA(String.valueOf("SELFIE_PHOTO_DATA")),
    
    /**
     * Location of avatar photo of the user in DANA
     */
    AVATAR_URL(String.valueOf("AVATAR_URL")),
    
    /**
     * Masked full name of the user in DANA
     */
    MASKED_FULLNAME(String.valueOf("MASKED_FULLNAME")),
    
    /**
     * To handle empty string value
     */
    UNSPECIFIED(String.valueOf(""));

    private String value;

    ResourceTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ResourceTypeEnum fromValue(String value) {
      for (ResourceTypeEnum b : ResourceTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public static final String JSON_PROPERTY_RESOURCE_TYPE = "resourceType";
  @javax.annotation.Nonnull
  private ResourceTypeEnum resourceType;

  public static final String JSON_PROPERTY_VALUE = "value";
  @javax.annotation.Nonnull
  private String value;

  public UserResourceInfo() {
  }

  public UserResourceInfo resourceType(@javax.annotation.Nonnull ResourceTypeEnum resourceType) {
    
    this.resourceType = resourceType;
    return this;
  }

  /**
   * Type of user resource
   * @return resourceType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ResourceTypeEnum getResourceType() {
    return resourceType;
  }


  @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResourceType(@javax.annotation.Nonnull ResourceTypeEnum resourceType) {
    this.resourceType = resourceType;
  }

  public UserResourceInfo value(@javax.annotation.Nonnull String value) {
    
    this.value = value;
    return this;
  }

  /**
   * Resource value
   * @return value
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValue(@javax.annotation.Nonnull String value) {
    this.value = value;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserResourceInfo userResourceInfo = (UserResourceInfo) o;
    return Objects.equals(this.resourceType, userResourceInfo.resourceType) &&
        Objects.equals(this.value, userResourceInfo.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceType, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserResourceInfo {\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
