/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.widget.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Response object for Direct Debit Payment API
 */
@JsonPropertyOrder({
  WidgetPaymentResponse.JSON_PROPERTY_RESPONSE_CODE,
  WidgetPaymentResponse.JSON_PROPERTY_RESPONSE_MESSAGE,
  WidgetPaymentResponse.JSON_PROPERTY_REFERENCE_NO,
  WidgetPaymentResponse.JSON_PROPERTY_PARTNER_REFERENCE_NO,
  WidgetPaymentResponse.JSON_PROPERTY_WEB_REDIRECT_URL,
  WidgetPaymentResponse.JSON_PROPERTY_ADDITIONAL_INFO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class WidgetPaymentResponse {
  public static final String JSON_PROPERTY_RESPONSE_CODE = "responseCode";
  @javax.annotation.Nonnull
  private String responseCode;

  public static final String JSON_PROPERTY_RESPONSE_MESSAGE = "responseMessage";
  @javax.annotation.Nonnull
  private String responseMessage;

  public static final String JSON_PROPERTY_REFERENCE_NO = "referenceNo";
  @javax.annotation.Nullable
  private String referenceNo;

  public static final String JSON_PROPERTY_PARTNER_REFERENCE_NO = "partnerReferenceNo";
  @javax.annotation.Nonnull
  private String partnerReferenceNo;

  public static final String JSON_PROPERTY_WEB_REDIRECT_URL = "webRedirectUrl";
  @javax.annotation.Nullable
  private String webRedirectUrl;

  public static final String JSON_PROPERTY_ADDITIONAL_INFO = "additionalInfo";
  @javax.annotation.Nullable
  private Map<String, Object> additionalInfo = new HashMap<>();

  public WidgetPaymentResponse() {
  }

  public WidgetPaymentResponse responseCode(@javax.annotation.Nonnull String responseCode) {
    
    this.responseCode = responseCode;
    return this;
  }

  /**
   * Refer to response code list:<br> * 2005400 - Successful<br> * 4005400 - Bad Request - Retry request with proper parameter<br> * 4005401 - Invalid Field Format - Retry request with proper parameter<br> * 4005402 - Invalid Mandatory Field - Retry request with proper parameter<br> * 4015400 - Unauthorized. [reason] - Retry request with proper parameter<br> * 4035402 - Exceeds Transaction Amount Limit - Try to adjust the order amount<br> * 4035405 - Do Not Honor - Retry request with proper parameter or can contact DANA to check the user/account status<br> * 4035415 - Transaction Not Permitted - Retry request periodically or consult to DANA<br> * 4045408 - Invalid Merchant - Retry request with proper parameter<br> * 4045418 - Inconsistent Request - Retry with proper parameter<br> * 4295400 - Too Many Requests - Retry request periodically by sending same request payload<br> * 5005400 - General Error - Retry request periodically<br> * 5005401 - Internal Server Error - Retry request periodically by sending same request payload<br> 
   * @return responseCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESPONSE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getResponseCode() {
    return responseCode;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResponseCode(@javax.annotation.Nonnull String responseCode) {
    this.responseCode = responseCode;
  }

  public WidgetPaymentResponse responseMessage(@javax.annotation.Nonnull String responseMessage) {
    
    this.responseMessage = responseMessage;
    return this;
  }

  /**
   * Human readable response message
   * @return responseMessage
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESPONSE_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getResponseMessage() {
    return responseMessage;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResponseMessage(@javax.annotation.Nonnull String responseMessage) {
    this.responseMessage = responseMessage;
  }

  public WidgetPaymentResponse referenceNo(@javax.annotation.Nullable String referenceNo) {
    
    this.referenceNo = referenceNo;
    return this;
  }

  /**
   * Transaction identifier on DANA system, returned when transaction is successfully processed
   * @return referenceNo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReferenceNo() {
    return referenceNo;
  }


  @JsonProperty(JSON_PROPERTY_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReferenceNo(@javax.annotation.Nullable String referenceNo) {
    this.referenceNo = referenceNo;
  }

  public WidgetPaymentResponse partnerReferenceNo(@javax.annotation.Nonnull String partnerReferenceNo) {
    
    this.partnerReferenceNo = partnerReferenceNo;
    return this;
  }

  /**
   * Transaction identifier on partner system which assigned to each transaction
   * @return partnerReferenceNo
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PARTNER_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPartnerReferenceNo() {
    return partnerReferenceNo;
  }


  @JsonProperty(JSON_PROPERTY_PARTNER_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPartnerReferenceNo(@javax.annotation.Nonnull String partnerReferenceNo) {
    this.partnerReferenceNo = partnerReferenceNo;
  }

  public WidgetPaymentResponse webRedirectUrl(@javax.annotation.Nullable String webRedirectUrl) {
    
    this.webRedirectUrl = webRedirectUrl;
    return this;
  }

  /**
   * DANA checkout URL, returned when transaction is successfully processed
   * @return webRedirectUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEB_REDIRECT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWebRedirectUrl() {
    return webRedirectUrl;
  }


  @JsonProperty(JSON_PROPERTY_WEB_REDIRECT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebRedirectUrl(@javax.annotation.Nullable String webRedirectUrl) {
    this.webRedirectUrl = webRedirectUrl;
  }

  public WidgetPaymentResponse additionalInfo(@javax.annotation.Nullable Map<String, Object> additionalInfo) {
    
    this.additionalInfo = additionalInfo;
    return this;
  }

  public WidgetPaymentResponse putAdditionalInfoItem(String key, Object additionalInfoItem) {
    if (this.additionalInfo == null) {
      this.additionalInfo = new HashMap<>();
    }
    this.additionalInfo.put(key, additionalInfoItem);
    return this;
  }

  /**
   * Additional information
   * @return additionalInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFO)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getAdditionalInfo() {
    return additionalInfo;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFO)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalInfo(@javax.annotation.Nullable Map<String, Object> additionalInfo) {
    this.additionalInfo = additionalInfo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WidgetPaymentResponse widgetPaymentResponse = (WidgetPaymentResponse) o;
    return Objects.equals(this.responseCode, widgetPaymentResponse.responseCode) &&
        Objects.equals(this.responseMessage, widgetPaymentResponse.responseMessage) &&
        Objects.equals(this.referenceNo, widgetPaymentResponse.referenceNo) &&
        Objects.equals(this.partnerReferenceNo, widgetPaymentResponse.partnerReferenceNo) &&
        Objects.equals(this.webRedirectUrl, widgetPaymentResponse.webRedirectUrl) &&
        Objects.equals(this.additionalInfo, widgetPaymentResponse.additionalInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseCode, responseMessage, referenceNo, partnerReferenceNo, webRedirectUrl, additionalInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WidgetPaymentResponse {\n");
    sb.append("    responseCode: ").append(toIndentedString(responseCode)).append("\n");
    sb.append("    responseMessage: ").append(toIndentedString(responseMessage)).append("\n");
    sb.append("    referenceNo: ").append(toIndentedString(referenceNo)).append("\n");
    sb.append("    partnerReferenceNo: ").append(toIndentedString(partnerReferenceNo)).append("\n");
    sb.append("    webRedirectUrl: ").append(toIndentedString(webRedirectUrl)).append("\n");
    sb.append("    additionalInfo: ").append(toIndentedString(additionalInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
