/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.merchantmanagement.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * One row in `assetCardList` (response body)
 */
@JsonPropertyOrder({
  AssetCardListItem.JSON_PROPERTY_CONTACT_BIZ_TYPE,
  AssetCardListItem.JSON_PROPERTY_CARD_INDEX_NO,
  AssetCardListItem.JSON_PROPERTY_CARD_NO_LENGTH,
  AssetCardListItem.JSON_PROPERTY_MASKED_CARD_NO,
  AssetCardListItem.JSON_PROPERTY_ASSET_TYPE,
  AssetCardListItem.JSON_PROPERTY_HOLDER_NAME,
  AssetCardListItem.JSON_PROPERTY_INST_LOGO_URL,
  AssetCardListItem.JSON_PROPERTY_INST_ID,
  AssetCardListItem.JSON_PROPERTY_INST_OFFICIAL_NAME,
  AssetCardListItem.JSON_PROPERTY_EXPIRY_YEAR,
  AssetCardListItem.JSON_PROPERTY_EXPIRY_MONTH,
  AssetCardListItem.JSON_PROPERTY_VERIFIED,
  AssetCardListItem.JSON_PROPERTY_BINDING_ID,
  AssetCardListItem.JSON_PROPERTY_DEFAULT_ASSET,
  AssetCardListItem.JSON_PROPERTY_ENABLE_STATUS,
  AssetCardListItem.JSON_PROPERTY_DIRECT_DEBIT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class AssetCardListItem {
  /**
   * Contact business type (`ContactBizTypeEnum`)
   */
  public enum ContactBizTypeEnum {
    /**
     * History of transfer transaction
     */
    TRANSFER_HIS(String.valueOf("TRANSFER_HIS")),
    
    /**
     * Transfer from virtual bank card
     */
    DIRECT_TRANSFER(String.valueOf("DIRECT_TRANSFER")),
    
    /**
     * Bank card used for general purpose
     */
    GENERAL_CARD(String.valueOf("GENERAL_CARD")),
    
    /**
     * Bank card used for direct payment
     */
    DIRECTPAY_CARD(String.valueOf("DIRECTPAY_CARD")),
    
    /**
     * Bank card for payment card
     */
    PAYMENT_CARD(String.valueOf("PAYMENT_CARD")),
    
    /**
     * Bank card used for cashout
     */
    CASHOUT_CARD(String.valueOf("CASHOUT_CARD")),
    
    /**
     * Bank card used for BCA
     */
    IMPS_ACCOUNT(String.valueOf("IMPS_ACCOUNT")),
    
    /**
     * Investment account
     */
    INVESTMENT_ACCOUNT(String.valueOf("INVESTMENT_ACCOUNT")),
    
    /**
     * To handle empty string value
     */
    UNSPECIFIED(String.valueOf(""));

    private String value;

    ContactBizTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ContactBizTypeEnum fromValue(String value) {
      for (ContactBizTypeEnum b : ContactBizTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public static final String JSON_PROPERTY_CONTACT_BIZ_TYPE = "contactBizType";
  @javax.annotation.Nonnull
  private ContactBizTypeEnum contactBizType;

  public static final String JSON_PROPERTY_CARD_INDEX_NO = "cardIndexNo";
  @javax.annotation.Nonnull
  private String cardIndexNo;

  public static final String JSON_PROPERTY_CARD_NO_LENGTH = "cardNoLength";
  @javax.annotation.Nonnull
  private String cardNoLength;

  public static final String JSON_PROPERTY_MASKED_CARD_NO = "maskedCardNo";
  @javax.annotation.Nonnull
  private String maskedCardNo;

  /**
   * Asset / card type (`AssetCardTypeEnum`)
   */
  public enum AssetTypeEnum {
    /**
     * Checking account
     */
    CHECKING_ACCOUNT(String.valueOf("CHECKING_ACCOUNT")),
    
    /**
     * User's savings account
     */
    SAVINGS_ACCOUNT(String.valueOf("SAVINGS_ACCOUNT")),
    
    /**
     * User's loan account
     */
    LOAN_ACCOUNT(String.valueOf("LOAN_ACCOUNT")),
    
    /**
     * Immediate payment service account
     */
    IMPS_ACCOUNT(String.valueOf("IMPS_ACCOUNT")),
    
    /**
     * User's debit card
     */
    DEBIT_CARD(String.valueOf("DEBIT_CARD")),
    
    /**
     * User's credit card
     */
    CREDIT_CARD(String.valueOf("CREDIT_CARD")),
    
    /**
     * Secured credit card
     */
    SECURED_CREDIT_CARD(String.valueOf("SECURED_CREDIT_CARD")),
    
    /**
     * Virtual account
     */
    VA_ACCOUNT(String.valueOf("VA_ACCOUNT")),
    
    /**
     * On the counter account
     */
    OTC_ACCOUNT(String.valueOf("OTC_ACCOUNT")),
    
    /**
     * User's refund account
     */
    REFUND_ACCOUNT(String.valueOf("REFUND_ACCOUNT")),
    
    /**
     * User's credit account
     */
    CREDIT_ACCOUNT(String.valueOf("CREDIT_ACCOUNT")),
    
    /**
     * User's loan account paylater
     */
    LOAN(String.valueOf("LOAN")),
    
    /**
     * User's mutual fund account
     */
    MUTUAL_FUNDS_ACCOUNT(String.valueOf("MUTUAL_FUNDS_ACCOUNT")),
    
    /**
     * User's investment account
     */
    INVESTMENT(String.valueOf("INVESTMENT")),
    
    /**
     * To handle empty string value
     */
    UNSPECIFIED(String.valueOf(""));

    private String value;

    AssetTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AssetTypeEnum fromValue(String value) {
      for (AssetTypeEnum b : AssetTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public static final String JSON_PROPERTY_ASSET_TYPE = "assetType";
  @javax.annotation.Nonnull
  private AssetTypeEnum assetType;

  public static final String JSON_PROPERTY_HOLDER_NAME = "holderName";
  @javax.annotation.Nonnull
  private Map<String, Object> holderName = new HashMap<>();

  public static final String JSON_PROPERTY_INST_LOGO_URL = "instLogoUrl";
  @javax.annotation.Nullable
  private String instLogoUrl;

  public static final String JSON_PROPERTY_INST_ID = "instId";
  @javax.annotation.Nonnull
  private String instId;

  public static final String JSON_PROPERTY_INST_OFFICIAL_NAME = "instOfficialName";
  @javax.annotation.Nonnull
  private String instOfficialName;

  public static final String JSON_PROPERTY_EXPIRY_YEAR = "expiryYear";
  @javax.annotation.Nonnull
  private String expiryYear;

  public static final String JSON_PROPERTY_EXPIRY_MONTH = "expiryMonth";
  @javax.annotation.Nonnull
  private String expiryMonth;

  /**
   * Whether the user's card is verified
   */
  public enum VerifiedEnum {
    TRUE(String.valueOf("true")),
    
    FALSE(String.valueOf("false")),
    
    /**
     * To handle empty string value
     */
    UNSPECIFIED(String.valueOf(""));

    private String value;

    VerifiedEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static VerifiedEnum fromValue(String value) {
      for (VerifiedEnum b : VerifiedEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public static final String JSON_PROPERTY_VERIFIED = "verified";
  @javax.annotation.Nonnull
  private VerifiedEnum verified;

  public static final String JSON_PROPERTY_BINDING_ID = "bindingId";
  @javax.annotation.Nullable
  private String bindingId;

  /**
   * Whether this asset is the user's default payment
   */
  public enum DefaultAssetEnum {
    TRUE(String.valueOf("true")),
    
    FALSE(String.valueOf("false")),
    
    /**
     * To handle empty string value
     */
    UNSPECIFIED(String.valueOf(""));

    private String value;

    DefaultAssetEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DefaultAssetEnum fromValue(String value) {
      for (DefaultAssetEnum b : DefaultAssetEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public static final String JSON_PROPERTY_DEFAULT_ASSET = "defaultAsset";
  @javax.annotation.Nullable
  private DefaultAssetEnum defaultAsset;

  /**
   * Whether the card status is enabled; `\"true\"` when `enableOnly` in request was true
   */
  public enum EnableStatusEnum {
    TRUE(String.valueOf("true")),
    
    FALSE(String.valueOf("false")),
    
    /**
     * To handle empty string value
     */
    UNSPECIFIED(String.valueOf(""));

    private String value;

    EnableStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EnableStatusEnum fromValue(String value) {
      for (EnableStatusEnum b : EnableStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public static final String JSON_PROPERTY_ENABLE_STATUS = "enableStatus";
  @javax.annotation.Nullable
  private EnableStatusEnum enableStatus;

  /**
   * Whether payment uses direct debit
   */
  public enum DirectDebitEnum {
    TRUE(String.valueOf("true")),
    
    FALSE(String.valueOf("false")),
    
    /**
     * To handle empty string value
     */
    UNSPECIFIED(String.valueOf(""));

    private String value;

    DirectDebitEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DirectDebitEnum fromValue(String value) {
      for (DirectDebitEnum b : DirectDebitEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public static final String JSON_PROPERTY_DIRECT_DEBIT = "directDebit";
  @javax.annotation.Nullable
  private DirectDebitEnum directDebit;

  public AssetCardListItem() {
  }

  public AssetCardListItem contactBizType(@javax.annotation.Nonnull ContactBizTypeEnum contactBizType) {
    
    this.contactBizType = contactBizType;
    return this;
  }

  /**
   * Contact business type (`ContactBizTypeEnum`)
   * @return contactBizType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CONTACT_BIZ_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ContactBizTypeEnum getContactBizType() {
    return contactBizType;
  }


  @JsonProperty(JSON_PROPERTY_CONTACT_BIZ_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContactBizType(@javax.annotation.Nonnull ContactBizTypeEnum contactBizType) {
    this.contactBizType = contactBizType;
  }

  public AssetCardListItem cardIndexNo(@javax.annotation.Nonnull String cardIndexNo) {
    
    this.cardIndexNo = cardIndexNo;
    return this;
  }

  /**
   * Card index number
   * @return cardIndexNo
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CARD_INDEX_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCardIndexNo() {
    return cardIndexNo;
  }


  @JsonProperty(JSON_PROPERTY_CARD_INDEX_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCardIndexNo(@javax.annotation.Nonnull String cardIndexNo) {
    this.cardIndexNo = cardIndexNo;
  }

  public AssetCardListItem cardNoLength(@javax.annotation.Nonnull String cardNoLength) {
    
    this.cardNoLength = cardNoLength;
    return this;
  }

  /**
   * Card number length based on card index number
   * @return cardNoLength
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CARD_NO_LENGTH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCardNoLength() {
    return cardNoLength;
  }


  @JsonProperty(JSON_PROPERTY_CARD_NO_LENGTH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCardNoLength(@javax.annotation.Nonnull String cardNoLength) {
    this.cardNoLength = cardNoLength;
  }

  public AssetCardListItem maskedCardNo(@javax.annotation.Nonnull String maskedCardNo) {
    
    this.maskedCardNo = maskedCardNo;
    return this;
  }

  /**
   * Card number (masked)
   * @return maskedCardNo
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASKED_CARD_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMaskedCardNo() {
    return maskedCardNo;
  }


  @JsonProperty(JSON_PROPERTY_MASKED_CARD_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMaskedCardNo(@javax.annotation.Nonnull String maskedCardNo) {
    this.maskedCardNo = maskedCardNo;
  }

  public AssetCardListItem assetType(@javax.annotation.Nonnull AssetTypeEnum assetType) {
    
    this.assetType = assetType;
    return this;
  }

  /**
   * Asset / card type (`AssetCardTypeEnum`)
   * @return assetType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ASSET_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AssetTypeEnum getAssetType() {
    return assetType;
  }


  @JsonProperty(JSON_PROPERTY_ASSET_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAssetType(@javax.annotation.Nonnull AssetTypeEnum assetType) {
    this.assetType = assetType;
  }

  public AssetCardListItem holderName(@javax.annotation.Nonnull Map<String, Object> holderName) {
    
    this.holderName = holderName;
    return this;
  }

  public AssetCardListItem putHolderNameItem(String key, Object holderNameItem) {
    this.holderName.put(key, holderNameItem);
    return this;
  }

  /**
   * Holder name (JSON object per DANA spec)
   * @return holderName
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HOLDER_NAME)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)

  public Map<String, Object> getHolderName() {
    return holderName;
  }


  @JsonProperty(JSON_PROPERTY_HOLDER_NAME)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public void setHolderName(@javax.annotation.Nonnull Map<String, Object> holderName) {
    this.holderName = holderName;
  }

  public AssetCardListItem instLogoUrl(@javax.annotation.Nullable String instLogoUrl) {
    
    this.instLogoUrl = instLogoUrl;
    return this;
  }

  /**
   * Institution logo URL
   * @return instLogoUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INST_LOGO_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInstLogoUrl() {
    return instLogoUrl;
  }


  @JsonProperty(JSON_PROPERTY_INST_LOGO_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInstLogoUrl(@javax.annotation.Nullable String instLogoUrl) {
    this.instLogoUrl = instLogoUrl;
  }

  public AssetCardListItem instId(@javax.annotation.Nonnull String instId) {
    
    this.instId = instId;
    return this;
  }

  /**
   * Institution identifier
   * @return instId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INST_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getInstId() {
    return instId;
  }


  @JsonProperty(JSON_PROPERTY_INST_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInstId(@javax.annotation.Nonnull String instId) {
    this.instId = instId;
  }

  public AssetCardListItem instOfficialName(@javax.annotation.Nonnull String instOfficialName) {
    
    this.instOfficialName = instOfficialName;
    return this;
  }

  /**
   * Institution official name based on `instId`
   * @return instOfficialName
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INST_OFFICIAL_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getInstOfficialName() {
    return instOfficialName;
  }


  @JsonProperty(JSON_PROPERTY_INST_OFFICIAL_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInstOfficialName(@javax.annotation.Nonnull String instOfficialName) {
    this.instOfficialName = instOfficialName;
  }

  public AssetCardListItem expiryYear(@javax.annotation.Nonnull String expiryYear) {
    
    this.expiryYear = expiryYear;
    return this;
  }

  /**
   * Expiry year (e.g. debit, credit, virtual account)
   * @return expiryYear
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EXPIRY_YEAR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExpiryYear() {
    return expiryYear;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRY_YEAR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpiryYear(@javax.annotation.Nonnull String expiryYear) {
    this.expiryYear = expiryYear;
  }

  public AssetCardListItem expiryMonth(@javax.annotation.Nonnull String expiryMonth) {
    
    this.expiryMonth = expiryMonth;
    return this;
  }

  /**
   * Expiry month
   * @return expiryMonth
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EXPIRY_MONTH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExpiryMonth() {
    return expiryMonth;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRY_MONTH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpiryMonth(@javax.annotation.Nonnull String expiryMonth) {
    this.expiryMonth = expiryMonth;
  }

  public AssetCardListItem verified(@javax.annotation.Nonnull VerifiedEnum verified) {
    
    this.verified = verified;
    return this;
  }

  /**
   * Whether the user's card is verified
   * @return verified
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VERIFIED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public VerifiedEnum getVerified() {
    return verified;
  }


  @JsonProperty(JSON_PROPERTY_VERIFIED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVerified(@javax.annotation.Nonnull VerifiedEnum verified) {
    this.verified = verified;
  }

  public AssetCardListItem bindingId(@javax.annotation.Nullable String bindingId) {
    
    this.bindingId = bindingId;
    return this;
  }

  /**
   * Asset card bind identifier
   * @return bindingId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BINDING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBindingId() {
    return bindingId;
  }


  @JsonProperty(JSON_PROPERTY_BINDING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBindingId(@javax.annotation.Nullable String bindingId) {
    this.bindingId = bindingId;
  }

  public AssetCardListItem defaultAsset(@javax.annotation.Nullable DefaultAssetEnum defaultAsset) {
    
    this.defaultAsset = defaultAsset;
    return this;
  }

  /**
   * Whether this asset is the user's default payment
   * @return defaultAsset
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEFAULT_ASSET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DefaultAssetEnum getDefaultAsset() {
    return defaultAsset;
  }


  @JsonProperty(JSON_PROPERTY_DEFAULT_ASSET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultAsset(@javax.annotation.Nullable DefaultAssetEnum defaultAsset) {
    this.defaultAsset = defaultAsset;
  }

  public AssetCardListItem enableStatus(@javax.annotation.Nullable EnableStatusEnum enableStatus) {
    
    this.enableStatus = enableStatus;
    return this;
  }

  /**
   * Whether the card status is enabled; `\"true\"` when `enableOnly` in request was true
   * @return enableStatus
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENABLE_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EnableStatusEnum getEnableStatus() {
    return enableStatus;
  }


  @JsonProperty(JSON_PROPERTY_ENABLE_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnableStatus(@javax.annotation.Nullable EnableStatusEnum enableStatus) {
    this.enableStatus = enableStatus;
  }

  public AssetCardListItem directDebit(@javax.annotation.Nullable DirectDebitEnum directDebit) {
    
    this.directDebit = directDebit;
    return this;
  }

  /**
   * Whether payment uses direct debit
   * @return directDebit
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIRECT_DEBIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DirectDebitEnum getDirectDebit() {
    return directDebit;
  }


  @JsonProperty(JSON_PROPERTY_DIRECT_DEBIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDirectDebit(@javax.annotation.Nullable DirectDebitEnum directDebit) {
    this.directDebit = directDebit;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssetCardListItem assetCardListItem = (AssetCardListItem) o;
    return Objects.equals(this.contactBizType, assetCardListItem.contactBizType) &&
        Objects.equals(this.cardIndexNo, assetCardListItem.cardIndexNo) &&
        Objects.equals(this.cardNoLength, assetCardListItem.cardNoLength) &&
        Objects.equals(this.maskedCardNo, assetCardListItem.maskedCardNo) &&
        Objects.equals(this.assetType, assetCardListItem.assetType) &&
        Objects.equals(this.holderName, assetCardListItem.holderName) &&
        Objects.equals(this.instLogoUrl, assetCardListItem.instLogoUrl) &&
        Objects.equals(this.instId, assetCardListItem.instId) &&
        Objects.equals(this.instOfficialName, assetCardListItem.instOfficialName) &&
        Objects.equals(this.expiryYear, assetCardListItem.expiryYear) &&
        Objects.equals(this.expiryMonth, assetCardListItem.expiryMonth) &&
        Objects.equals(this.verified, assetCardListItem.verified) &&
        Objects.equals(this.bindingId, assetCardListItem.bindingId) &&
        Objects.equals(this.defaultAsset, assetCardListItem.defaultAsset) &&
        Objects.equals(this.enableStatus, assetCardListItem.enableStatus) &&
        Objects.equals(this.directDebit, assetCardListItem.directDebit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contactBizType, cardIndexNo, cardNoLength, maskedCardNo, assetType, holderName, instLogoUrl, instId, instOfficialName, expiryYear, expiryMonth, verified, bindingId, defaultAsset, enableStatus, directDebit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssetCardListItem {\n");
    sb.append("    contactBizType: ").append(toIndentedString(contactBizType)).append("\n");
    sb.append("    cardIndexNo: ").append(toIndentedString(cardIndexNo)).append("\n");
    sb.append("    cardNoLength: ").append(toIndentedString(cardNoLength)).append("\n");
    sb.append("    maskedCardNo: ").append(toIndentedString(maskedCardNo)).append("\n");
    sb.append("    assetType: ").append(toIndentedString(assetType)).append("\n");
    sb.append("    holderName: ").append(toIndentedString(holderName)).append("\n");
    sb.append("    instLogoUrl: ").append(toIndentedString(instLogoUrl)).append("\n");
    sb.append("    instId: ").append(toIndentedString(instId)).append("\n");
    sb.append("    instOfficialName: ").append(toIndentedString(instOfficialName)).append("\n");
    sb.append("    expiryYear: ").append(toIndentedString(expiryYear)).append("\n");
    sb.append("    expiryMonth: ").append(toIndentedString(expiryMonth)).append("\n");
    sb.append("    verified: ").append(toIndentedString(verified)).append("\n");
    sb.append("    bindingId: ").append(toIndentedString(bindingId)).append("\n");
    sb.append("    defaultAsset: ").append(toIndentedString(defaultAsset)).append("\n");
    sb.append("    enableStatus: ").append(toIndentedString(enableStatus)).append("\n");
    sb.append("    directDebit: ").append(toIndentedString(directDebit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
