/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.merchantmanagement.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.dana.merchantmanagement.v1.model.ResultInfo;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateShopResponseResponseBody
 */
@JsonPropertyOrder({
  CreateShopResponseResponseBody.JSON_PROPERTY_RESULT_INFO,
  CreateShopResponseResponseBody.JSON_PROPERTY_SHOP_ID
})
@JsonTypeName("CreateShopResponse_response_body")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class CreateShopResponseResponseBody {
  public static final String JSON_PROPERTY_RESULT_INFO = "resultInfo";
  @javax.annotation.Nonnull
  private ResultInfo resultInfo;

  public static final String JSON_PROPERTY_SHOP_ID = "shopId";
  @javax.annotation.Nullable
  private String shopId;

  public CreateShopResponseResponseBody() {
  }

  public CreateShopResponseResponseBody resultInfo(@javax.annotation.Nonnull ResultInfo resultInfo) {
    
    this.resultInfo = resultInfo;
    return this;
  }

  /**
   * Get resultInfo
   * @return resultInfo
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESULT_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ResultInfo getResultInfo() {
    return resultInfo;
  }


  @JsonProperty(JSON_PROPERTY_RESULT_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResultInfo(@javax.annotation.Nonnull ResultInfo resultInfo) {
    this.resultInfo = resultInfo;
  }

  public CreateShopResponseResponseBody shopId(@javax.annotation.Nullable String shopId) {
    
    this.shopId = shopId;
    return this;
  }

  /**
   * The shop ID that was created. Present when resultCodeId is 00000000
   * @return shopId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHOP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getShopId() {
    return shopId;
  }


  @JsonProperty(JSON_PROPERTY_SHOP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShopId(@javax.annotation.Nullable String shopId) {
    this.shopId = shopId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateShopResponseResponseBody createShopResponseResponseBody = (CreateShopResponseResponseBody) o;
    return Objects.equals(this.resultInfo, createShopResponseResponseBody.resultInfo) &&
        Objects.equals(this.shopId, createShopResponseResponseBody.shopId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultInfo, shopId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateShopResponseResponseBody {\n");
    sb.append("    resultInfo: ").append(toIndentedString(resultInfo)).append("\n");
    sb.append("    shopId: ").append(toIndentedString(shopId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
