/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.merchantmanagement.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PicInfo
 */
@JsonPropertyOrder({
  PicInfo.JSON_PROPERTY_PIC_NAME,
  PicInfo.JSON_PROPERTY_PIC_POSITION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class PicInfo {
  public static final String JSON_PROPERTY_PIC_NAME = "picName";
  @javax.annotation.Nullable
  private String picName;

  public static final String JSON_PROPERTY_PIC_POSITION = "picPosition";
  @javax.annotation.Nullable
  private String picPosition;

  public PicInfo() {
  }

  public PicInfo picName(@javax.annotation.Nullable String picName) {
    
    this.picName = picName;
    return this;
  }

  /**
   * PIC name
   * @return picName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PIC_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPicName() {
    return picName;
  }


  @JsonProperty(JSON_PROPERTY_PIC_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPicName(@javax.annotation.Nullable String picName) {
    this.picName = picName;
  }

  public PicInfo picPosition(@javax.annotation.Nullable String picPosition) {
    
    this.picPosition = picPosition;
    return this;
  }

  /**
   * PIC position
   * @return picPosition
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PIC_POSITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPicPosition() {
    return picPosition;
  }


  @JsonProperty(JSON_PROPERTY_PIC_POSITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPicPosition(@javax.annotation.Nullable String picPosition) {
    this.picPosition = picPosition;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PicInfo picInfo = (PicInfo) o;
    return Objects.equals(this.picName, picInfo.picName) &&
        Objects.equals(this.picPosition, picInfo.picPosition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(picName, picPosition);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PicInfo {\n");
    sb.append("    picName: ").append(toIndentedString(picName)).append("\n");
    sb.append("    picPosition: ").append(toIndentedString(picPosition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
