/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.merchantmanagement.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.dana.merchantmanagement.v1.model.ResultInfo;
import id.dana.merchantmanagement.v1.model.ShopResourceInfo;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * QueryShopResponseResponseBody
 */
@JsonPropertyOrder({
  QueryShopResponseResponseBody.JSON_PROPERTY_RESULT_INFO,
  QueryShopResponseResponseBody.JSON_PROPERTY_SHOP_RESOURCE_INFO
})
@JsonTypeName("QueryShopResponse_response_body")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class QueryShopResponseResponseBody {
  public static final String JSON_PROPERTY_RESULT_INFO = "resultInfo";
  @javax.annotation.Nonnull
  private ResultInfo resultInfo;

  public static final String JSON_PROPERTY_SHOP_RESOURCE_INFO = "shopResourceInfo";
  @javax.annotation.Nullable
  private ShopResourceInfo shopResourceInfo;

  public QueryShopResponseResponseBody() {
  }

  public QueryShopResponseResponseBody resultInfo(@javax.annotation.Nonnull ResultInfo resultInfo) {
    
    this.resultInfo = resultInfo;
    return this;
  }

  /**
   * Get resultInfo
   * @return resultInfo
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESULT_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ResultInfo getResultInfo() {
    return resultInfo;
  }


  @JsonProperty(JSON_PROPERTY_RESULT_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResultInfo(@javax.annotation.Nonnull ResultInfo resultInfo) {
    this.resultInfo = resultInfo;
  }

  public QueryShopResponseResponseBody shopResourceInfo(@javax.annotation.Nullable ShopResourceInfo shopResourceInfo) {
    
    this.shopResourceInfo = shopResourceInfo;
    return this;
  }

  /**
   * Get shopResourceInfo
   * @return shopResourceInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHOP_RESOURCE_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ShopResourceInfo getShopResourceInfo() {
    return shopResourceInfo;
  }


  @JsonProperty(JSON_PROPERTY_SHOP_RESOURCE_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShopResourceInfo(@javax.annotation.Nullable ShopResourceInfo shopResourceInfo) {
    this.shopResourceInfo = shopResourceInfo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryShopResponseResponseBody queryShopResponseResponseBody = (QueryShopResponseResponseBody) o;
    return Objects.equals(this.resultInfo, queryShopResponseResponseBody.resultInfo) &&
        Objects.equals(this.shopResourceInfo, queryShopResponseResponseBody.shopResourceInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultInfo, shopResourceInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryShopResponseResponseBody {\n");
    sb.append("    resultInfo: ").append(toIndentedString(resultInfo)).append("\n");
    sb.append("    shopResourceInfo: ").append(toIndentedString(shopResourceInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
