/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.merchantmanagement.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.dana.merchantmanagement.v1.model.QueryMerchantInfoResponseResponse;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * QueryMerchantInfoResponse
 */
@JsonPropertyOrder({
  QueryMerchantInfoResponse.JSON_PROPERTY_RESPONSE,
  QueryMerchantInfoResponse.JSON_PROPERTY_SIGNATURE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class QueryMerchantInfoResponse {
  public static final String JSON_PROPERTY_RESPONSE = "response";
  @javax.annotation.Nullable
  private QueryMerchantInfoResponseResponse response;

  public static final String JSON_PROPERTY_SIGNATURE = "signature";
  @javax.annotation.Nullable
  private String signature;

  public QueryMerchantInfoResponse() {
  }

  public QueryMerchantInfoResponse response(@javax.annotation.Nullable QueryMerchantInfoResponseResponse response) {
    
    this.response = response;
    return this;
  }

  /**
   * Get response
   * @return response
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESPONSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public QueryMerchantInfoResponseResponse getResponse() {
    return response;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponse(@javax.annotation.Nullable QueryMerchantInfoResponseResponse response) {
    this.response = response;
  }

  public QueryMerchantInfoResponse signature(@javax.annotation.Nullable String signature) {
    
    this.signature = signature;
    return this;
  }

  /**
   * Signature
   * @return signature
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignature() {
    return signature;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignature(@javax.annotation.Nullable String signature) {
    this.signature = signature;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryMerchantInfoResponse queryMerchantInfoResponse = (QueryMerchantInfoResponse) o;
    return Objects.equals(this.response, queryMerchantInfoResponse.response) &&
        Objects.equals(this.signature, queryMerchantInfoResponse.signature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(response, signature);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryMerchantInfoResponse {\n");
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
