/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.merchantmanagement.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.dana.merchantmanagement.v1.model.DivisionResourceInfo;
import id.dana.merchantmanagement.v1.model.ResultInfo;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * QueryDivisionResponseResponseBody
 */
@JsonPropertyOrder({
  QueryDivisionResponseResponseBody.JSON_PROPERTY_RESULT_INFO,
  QueryDivisionResponseResponseBody.JSON_PROPERTY_DIVISION_RESOURCE_INFO
})
@JsonTypeName("QueryDivisionResponse_response_body")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class QueryDivisionResponseResponseBody {
  public static final String JSON_PROPERTY_RESULT_INFO = "resultInfo";
  @javax.annotation.Nonnull
  private ResultInfo resultInfo;

  public static final String JSON_PROPERTY_DIVISION_RESOURCE_INFO = "divisionResourceInfo";
  @javax.annotation.Nullable
  private DivisionResourceInfo divisionResourceInfo;

  public QueryDivisionResponseResponseBody() {
  }

  public QueryDivisionResponseResponseBody resultInfo(@javax.annotation.Nonnull ResultInfo resultInfo) {
    
    this.resultInfo = resultInfo;
    return this;
  }

  /**
   * Get resultInfo
   * @return resultInfo
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESULT_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ResultInfo getResultInfo() {
    return resultInfo;
  }


  @JsonProperty(JSON_PROPERTY_RESULT_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResultInfo(@javax.annotation.Nonnull ResultInfo resultInfo) {
    this.resultInfo = resultInfo;
  }

  public QueryDivisionResponseResponseBody divisionResourceInfo(@javax.annotation.Nullable DivisionResourceInfo divisionResourceInfo) {
    
    this.divisionResourceInfo = divisionResourceInfo;
    return this;
  }

  /**
   * Get divisionResourceInfo
   * @return divisionResourceInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIVISION_RESOURCE_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DivisionResourceInfo getDivisionResourceInfo() {
    return divisionResourceInfo;
  }


  @JsonProperty(JSON_PROPERTY_DIVISION_RESOURCE_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDivisionResourceInfo(@javax.annotation.Nullable DivisionResourceInfo divisionResourceInfo) {
    this.divisionResourceInfo = divisionResourceInfo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryDivisionResponseResponseBody queryDivisionResponseResponseBody = (QueryDivisionResponseResponseBody) o;
    return Objects.equals(this.resultInfo, queryDivisionResponseResponseBody.resultInfo) &&
        Objects.equals(this.divisionResourceInfo, queryDivisionResponseResponseBody.divisionResourceInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultInfo, divisionResourceInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryDivisionResponseResponseBody {\n");
    sb.append("    resultInfo: ").append(toIndentedString(resultInfo)).append("\n");
    sb.append("    divisionResourceInfo: ").append(toIndentedString(divisionResourceInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
