/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.merchantmanagement.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.dana.merchantmanagement.v1.model.AddressInfo;
import id.dana.merchantmanagement.v1.model.BusinessDocs;
import id.dana.merchantmanagement.v1.model.MobileNoInfo;
import id.dana.merchantmanagement.v1.model.PicInfo;
import id.dana.merchantmanagement.v1.model.UserName;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UpdateShopRequest
 */
@JsonPropertyOrder({
  UpdateShopRequest.JSON_PROPERTY_SHOP_ID,
  UpdateShopRequest.JSON_PROPERTY_MERCHANT_ID,
  UpdateShopRequest.JSON_PROPERTY_SHOP_ID_TYPE,
  UpdateShopRequest.JSON_PROPERTY_MAIN_NAME,
  UpdateShopRequest.JSON_PROPERTY_SHOP_ADDRESS,
  UpdateShopRequest.JSON_PROPERTY_SHOP_DESC,
  UpdateShopRequest.JSON_PROPERTY_NEW_EXTERNAL_SHOP_ID,
  UpdateShopRequest.JSON_PROPERTY_MCC_CODES,
  UpdateShopRequest.JSON_PROPERTY_LOGO_URL_MAP,
  UpdateShopRequest.JSON_PROPERTY_EXT_INFO,
  UpdateShopRequest.JSON_PROPERTY_SIZE_TYPE,
  UpdateShopRequest.JSON_PROPERTY_LN,
  UpdateShopRequest.JSON_PROPERTY_LAT,
  UpdateShopRequest.JSON_PROPERTY_LOYALTY,
  UpdateShopRequest.JSON_PROPERTY_OWNER_ADDRESS,
  UpdateShopRequest.JSON_PROPERTY_OWNER_NAME,
  UpdateShopRequest.JSON_PROPERTY_OWNER_PHONE_NUMBER,
  UpdateShopRequest.JSON_PROPERTY_OWNER_ID_TYPE,
  UpdateShopRequest.JSON_PROPERTY_OWNER_ID_NO,
  UpdateShopRequest.JSON_PROPERTY_DEVICE_NUMBER,
  UpdateShopRequest.JSON_PROPERTY_POS_NUMBER,
  UpdateShopRequest.JSON_PROPERTY_API_VERSION,
  UpdateShopRequest.JSON_PROPERTY_BUSINESS_ENTITY,
  UpdateShopRequest.JSON_PROPERTY_SHOP_OWNING,
  UpdateShopRequest.JSON_PROPERTY_SHOP_BIZ_TYPE,
  UpdateShopRequest.JSON_PROPERTY_BUSINESS_DOCS,
  UpdateShopRequest.JSON_PROPERTY_BUSINESS_END_DATE,
  UpdateShopRequest.JSON_PROPERTY_TAX_NO,
  UpdateShopRequest.JSON_PROPERTY_TAX_ADDRESS,
  UpdateShopRequest.JSON_PROPERTY_BRAND_NAME,
  UpdateShopRequest.JSON_PROPERTY_DIRECTOR_PICS,
  UpdateShopRequest.JSON_PROPERTY_NON_DIRECTOR_PICS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class UpdateShopRequest {
  public static final String JSON_PROPERTY_SHOP_ID = "shopId";
  @javax.annotation.Nonnull
  private String shopId;

  public static final String JSON_PROPERTY_MERCHANT_ID = "merchantId";
  @javax.annotation.Nonnull
  private String merchantId;

  /**
   * Shop identifier type
   */
  public enum ShopIdTypeEnum {
    INNER_ID(String.valueOf("INNER_ID")),
    
    EXTERNAL_ID(String.valueOf("EXTERNAL_ID")),
    
    /**
     * To handle empty string value
     */
    UNSPECIFIED(String.valueOf(""));

    private String value;

    ShopIdTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ShopIdTypeEnum fromValue(String value) {
      for (ShopIdTypeEnum b : ShopIdTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public static final String JSON_PROPERTY_SHOP_ID_TYPE = "shopIdType";
  @javax.annotation.Nonnull
  private ShopIdTypeEnum shopIdType;

  public static final String JSON_PROPERTY_MAIN_NAME = "mainName";
  @javax.annotation.Nullable
  private String mainName;

  public static final String JSON_PROPERTY_SHOP_ADDRESS = "shopAddress";
  @javax.annotation.Nonnull
  private AddressInfo shopAddress;

  public static final String JSON_PROPERTY_SHOP_DESC = "shopDesc";
  @javax.annotation.Nullable
  private String shopDesc;

  public static final String JSON_PROPERTY_NEW_EXTERNAL_SHOP_ID = "newExternalShopId";
  @javax.annotation.Nullable
  private String newExternalShopId;

  public static final String JSON_PROPERTY_MCC_CODES = "mccCodes";
  @javax.annotation.Nullable
  private List<String> mccCodes = new ArrayList<>();

  public static final String JSON_PROPERTY_LOGO_URL_MAP = "logoUrlMap";
  @javax.annotation.Nullable
  private Map<String, String> logoUrlMap = new HashMap<>();

  public static final String JSON_PROPERTY_EXT_INFO = "extInfo";
  @javax.annotation.Nullable
  private Map<String, Object> extInfo = new HashMap<>();

  /**
   * Size type
   */
  public enum SizeTypeEnum {
    UMI(String.valueOf("UMI")),
    
    UKE(String.valueOf("UKE")),
    
    UME(String.valueOf("UME")),
    
    UBE(String.valueOf("UBE")),
    
    /**
     * To handle empty string value
     */
    UNSPECIFIED(String.valueOf(""));

    private String value;

    SizeTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SizeTypeEnum fromValue(String value) {
      for (SizeTypeEnum b : SizeTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public static final String JSON_PROPERTY_SIZE_TYPE = "sizeType";
  @javax.annotation.Nullable
  private SizeTypeEnum sizeType;

  public static final String JSON_PROPERTY_LN = "ln";
  @javax.annotation.Nullable
  private String ln;

  public static final String JSON_PROPERTY_LAT = "lat";
  @javax.annotation.Nullable
  private String lat;

  /**
   * Flag for loyalty category
   */
  public enum LoyaltyEnum {
    TRUE(String.valueOf("true")),
    
    FALSE(String.valueOf("false")),
    
    /**
     * To handle empty string value
     */
    UNSPECIFIED(String.valueOf(""));

    private String value;

    LoyaltyEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LoyaltyEnum fromValue(String value) {
      for (LoyaltyEnum b : LoyaltyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public static final String JSON_PROPERTY_LOYALTY = "loyalty";
  @javax.annotation.Nullable
  private LoyaltyEnum loyalty;

  public static final String JSON_PROPERTY_OWNER_ADDRESS = "ownerAddress";
  @javax.annotation.Nullable
  private AddressInfo ownerAddress;

  public static final String JSON_PROPERTY_OWNER_NAME = "ownerName";
  @javax.annotation.Nullable
  private UserName ownerName;

  public static final String JSON_PROPERTY_OWNER_PHONE_NUMBER = "ownerPhoneNumber";
  @javax.annotation.Nullable
  private MobileNoInfo ownerPhoneNumber;

  /**
   * Owner identifier type
   */
  public enum OwnerIdTypeEnum {
    KTP(String.valueOf("KTP")),
    
    SIM(String.valueOf("SIM")),
    
    PASSPORT(String.valueOf("PASSPORT")),
    
    SIUP(String.valueOf("SIUP")),
    
    NIB(String.valueOf("NIB")),
    
    /**
     * To handle empty string value
     */
    UNSPECIFIED(String.valueOf(""));

    private String value;

    OwnerIdTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OwnerIdTypeEnum fromValue(String value) {
      for (OwnerIdTypeEnum b : OwnerIdTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public static final String JSON_PROPERTY_OWNER_ID_TYPE = "ownerIdType";
  @javax.annotation.Nullable
  private OwnerIdTypeEnum ownerIdType;

  public static final String JSON_PROPERTY_OWNER_ID_NO = "ownerIdNo";
  @javax.annotation.Nullable
  private String ownerIdNo;

  public static final String JSON_PROPERTY_DEVICE_NUMBER = "deviceNumber";
  @javax.annotation.Nullable
  private String deviceNumber;

  public static final String JSON_PROPERTY_POS_NUMBER = "posNumber";
  @javax.annotation.Nullable
  private String posNumber;

  public static final String JSON_PROPERTY_API_VERSION = "apiVersion";
  @javax.annotation.Nullable
  private String apiVersion;

  /**
   * Business entity type
   */
  public enum BusinessEntityEnum {
    PT(String.valueOf("pt")),
    
    CV(String.valueOf("cv")),
    
    INDIVIDU(String.valueOf("individu")),
    
    USAHA_DAGANG(String.valueOf("usaha_dagang")),
    
    YAYASAN(String.valueOf("yayasan")),
    
    KOPERASI(String.valueOf("koperasi")),
    
    /**
     * To handle empty string value
     */
    UNSPECIFIED(String.valueOf(""));

    private String value;

    BusinessEntityEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static BusinessEntityEnum fromValue(String value) {
      for (BusinessEntityEnum b : BusinessEntityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public static final String JSON_PROPERTY_BUSINESS_ENTITY = "businessEntity";
  @javax.annotation.Nullable
  private BusinessEntityEnum businessEntity;

  /**
   * Shop owning information
   */
  public enum ShopOwningEnum {
    DIRECT_OWNED(String.valueOf("DIRECT_OWNED")),
    
    FRANCHISED(String.valueOf("FRANCHISED")),
    
    /**
     * To handle empty string value
     */
    UNSPECIFIED(String.valueOf(""));

    private String value;

    ShopOwningEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ShopOwningEnum fromValue(String value) {
      for (ShopOwningEnum b : ShopOwningEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public static final String JSON_PROPERTY_SHOP_OWNING = "shopOwning";
  @javax.annotation.Nullable
  private ShopOwningEnum shopOwning;

  /**
   * Shop business type
   */
  public enum ShopBizTypeEnum {
    ONLINE(String.valueOf("ONLINE")),
    
    OFFLINE(String.valueOf("OFFLINE")),
    
    /**
     * To handle empty string value
     */
    UNSPECIFIED(String.valueOf(""));

    private String value;

    ShopBizTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ShopBizTypeEnum fromValue(String value) {
      for (ShopBizTypeEnum b : ShopBizTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public static final String JSON_PROPERTY_SHOP_BIZ_TYPE = "shopBizType";
  @javax.annotation.Nullable
  private ShopBizTypeEnum shopBizType;

  public static final String JSON_PROPERTY_BUSINESS_DOCS = "businessDocs";
  @javax.annotation.Nullable
  private List<BusinessDocs> businessDocs = new ArrayList<>();

  public static final String JSON_PROPERTY_BUSINESS_END_DATE = "businessEndDate";
  @javax.annotation.Nullable
  private String businessEndDate;

  public static final String JSON_PROPERTY_TAX_NO = "taxNo";
  @javax.annotation.Nullable
  private String taxNo;

  public static final String JSON_PROPERTY_TAX_ADDRESS = "taxAddress";
  @javax.annotation.Nullable
  private AddressInfo taxAddress;

  public static final String JSON_PROPERTY_BRAND_NAME = "brandName";
  @javax.annotation.Nullable
  private String brandName;

  public static final String JSON_PROPERTY_DIRECTOR_PICS = "directorPics";
  @javax.annotation.Nullable
  private List<PicInfo> directorPics = new ArrayList<>();

  public static final String JSON_PROPERTY_NON_DIRECTOR_PICS = "nonDirectorPics";
  @javax.annotation.Nullable
  private List<PicInfo> nonDirectorPics = new ArrayList<>();

  public UpdateShopRequest() {
  }

  public UpdateShopRequest shopId(@javax.annotation.Nonnull String shopId) {
    
    this.shopId = shopId;
    return this;
  }

  /**
   * Shop identifier. Length depends on shopIdType - INNER_ID (21 max), EXTERNAL_ID (64 max)
   * @return shopId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SHOP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getShopId() {
    return shopId;
  }


  @JsonProperty(JSON_PROPERTY_SHOP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShopId(@javax.annotation.Nonnull String shopId) {
    this.shopId = shopId;
  }

  public UpdateShopRequest merchantId(@javax.annotation.Nonnull String merchantId) {
    
    this.merchantId = merchantId;
    return this;
  }

  /**
   * Merchant identifier
   * @return merchantId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MERCHANT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMerchantId() {
    return merchantId;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMerchantId(@javax.annotation.Nonnull String merchantId) {
    this.merchantId = merchantId;
  }

  public UpdateShopRequest shopIdType(@javax.annotation.Nonnull ShopIdTypeEnum shopIdType) {
    
    this.shopIdType = shopIdType;
    return this;
  }

  /**
   * Shop identifier type
   * @return shopIdType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SHOP_ID_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ShopIdTypeEnum getShopIdType() {
    return shopIdType;
  }


  @JsonProperty(JSON_PROPERTY_SHOP_ID_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShopIdType(@javax.annotation.Nonnull ShopIdTypeEnum shopIdType) {
    this.shopIdType = shopIdType;
  }

  public UpdateShopRequest mainName(@javax.annotation.Nullable String mainName) {
    
    this.mainName = mainName;
    return this;
  }

  /**
   * Shop name
   * @return mainName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAIN_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMainName() {
    return mainName;
  }


  @JsonProperty(JSON_PROPERTY_MAIN_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMainName(@javax.annotation.Nullable String mainName) {
    this.mainName = mainName;
  }

  public UpdateShopRequest shopAddress(@javax.annotation.Nonnull AddressInfo shopAddress) {
    
    this.shopAddress = shopAddress;
    return this;
  }

  /**
   * Get shopAddress
   * @return shopAddress
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SHOP_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AddressInfo getShopAddress() {
    return shopAddress;
  }


  @JsonProperty(JSON_PROPERTY_SHOP_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShopAddress(@javax.annotation.Nonnull AddressInfo shopAddress) {
    this.shopAddress = shopAddress;
  }

  public UpdateShopRequest shopDesc(@javax.annotation.Nullable String shopDesc) {
    
    this.shopDesc = shopDesc;
    return this;
  }

  /**
   * Shop description
   * @return shopDesc
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHOP_DESC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getShopDesc() {
    return shopDesc;
  }


  @JsonProperty(JSON_PROPERTY_SHOP_DESC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShopDesc(@javax.annotation.Nullable String shopDesc) {
    this.shopDesc = shopDesc;
  }

  public UpdateShopRequest newExternalShopId(@javax.annotation.Nullable String newExternalShopId) {
    
    this.newExternalShopId = newExternalShopId;
    return this;
  }

  /**
   * New external shop identifier
   * @return newExternalShopId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEW_EXTERNAL_SHOP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNewExternalShopId() {
    return newExternalShopId;
  }


  @JsonProperty(JSON_PROPERTY_NEW_EXTERNAL_SHOP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNewExternalShopId(@javax.annotation.Nullable String newExternalShopId) {
    this.newExternalShopId = newExternalShopId;
  }

  public UpdateShopRequest mccCodes(@javax.annotation.Nullable List<String> mccCodes) {
    
    this.mccCodes = mccCodes;
    return this;
  }

  public UpdateShopRequest addMccCodesItem(String mccCodesItem) {
    if (this.mccCodes == null) {
      this.mccCodes = new ArrayList<>();
    }
    this.mccCodes.add(mccCodesItem);
    return this;
  }

  /**
   * Merchant category code
   * @return mccCodes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MCC_CODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getMccCodes() {
    return mccCodes;
  }


  @JsonProperty(JSON_PROPERTY_MCC_CODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMccCodes(@javax.annotation.Nullable List<String> mccCodes) {
    this.mccCodes = mccCodes;
  }

  public UpdateShopRequest logoUrlMap(@javax.annotation.Nullable Map<String, String> logoUrlMap) {
    
    this.logoUrlMap = logoUrlMap;
    return this;
  }

  public UpdateShopRequest putLogoUrlMapItem(String key, String logoUrlMapItem) {
    if (this.logoUrlMap == null) {
      this.logoUrlMap = new HashMap<>();
    }
    this.logoUrlMap.put(key, logoUrlMapItem);
    return this;
  }

  /**
   * Logo URL map with base64 encoded images. Keys can be LOGO, PC_LOGO, MOBILE_LOGO
   * @return logoUrlMap
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOGO_URL_MAP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getLogoUrlMap() {
    return logoUrlMap;
  }


  @JsonProperty(JSON_PROPERTY_LOGO_URL_MAP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLogoUrlMap(@javax.annotation.Nullable Map<String, String> logoUrlMap) {
    this.logoUrlMap = logoUrlMap;
  }

  public UpdateShopRequest extInfo(@javax.annotation.Nullable Map<String, Object> extInfo) {
    
    this.extInfo = extInfo;
    return this;
  }

  public UpdateShopRequest putExtInfoItem(String key, Object extInfoItem) {
    if (this.extInfo == null) {
      this.extInfo = new HashMap<>();
    }
    this.extInfo.put(key, extInfoItem);
    return this;
  }

  /**
   * Extend information
   * @return extInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXT_INFO)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getExtInfo() {
    return extInfo;
  }


  @JsonProperty(JSON_PROPERTY_EXT_INFO)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtInfo(@javax.annotation.Nullable Map<String, Object> extInfo) {
    this.extInfo = extInfo;
  }

  public UpdateShopRequest sizeType(@javax.annotation.Nullable SizeTypeEnum sizeType) {
    
    this.sizeType = sizeType;
    return this;
  }

  /**
   * Size type
   * @return sizeType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIZE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SizeTypeEnum getSizeType() {
    return sizeType;
  }


  @JsonProperty(JSON_PROPERTY_SIZE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSizeType(@javax.annotation.Nullable SizeTypeEnum sizeType) {
    this.sizeType = sizeType;
  }

  public UpdateShopRequest ln(@javax.annotation.Nullable String ln) {
    
    this.ln = ln;
    return this;
  }

  /**
   * Longitude of shop's location
   * @return ln
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLn() {
    return ln;
  }


  @JsonProperty(JSON_PROPERTY_LN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLn(@javax.annotation.Nullable String ln) {
    this.ln = ln;
  }

  public UpdateShopRequest lat(@javax.annotation.Nullable String lat) {
    
    this.lat = lat;
    return this;
  }

  /**
   * Latitude of shop's location
   * @return lat
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLat() {
    return lat;
  }


  @JsonProperty(JSON_PROPERTY_LAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLat(@javax.annotation.Nullable String lat) {
    this.lat = lat;
  }

  public UpdateShopRequest loyalty(@javax.annotation.Nullable LoyaltyEnum loyalty) {
    
    this.loyalty = loyalty;
    return this;
  }

  /**
   * Flag for loyalty category
   * @return loyalty
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOYALTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LoyaltyEnum getLoyalty() {
    return loyalty;
  }


  @JsonProperty(JSON_PROPERTY_LOYALTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoyalty(@javax.annotation.Nullable LoyaltyEnum loyalty) {
    this.loyalty = loyalty;
  }

  public UpdateShopRequest ownerAddress(@javax.annotation.Nullable AddressInfo ownerAddress) {
    
    this.ownerAddress = ownerAddress;
    return this;
  }

  /**
   * Get ownerAddress
   * @return ownerAddress
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OWNER_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AddressInfo getOwnerAddress() {
    return ownerAddress;
  }


  @JsonProperty(JSON_PROPERTY_OWNER_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwnerAddress(@javax.annotation.Nullable AddressInfo ownerAddress) {
    this.ownerAddress = ownerAddress;
  }

  public UpdateShopRequest ownerName(@javax.annotation.Nullable UserName ownerName) {
    
    this.ownerName = ownerName;
    return this;
  }

  /**
   * Get ownerName
   * @return ownerName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OWNER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserName getOwnerName() {
    return ownerName;
  }


  @JsonProperty(JSON_PROPERTY_OWNER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwnerName(@javax.annotation.Nullable UserName ownerName) {
    this.ownerName = ownerName;
  }

  public UpdateShopRequest ownerPhoneNumber(@javax.annotation.Nullable MobileNoInfo ownerPhoneNumber) {
    
    this.ownerPhoneNumber = ownerPhoneNumber;
    return this;
  }

  /**
   * Get ownerPhoneNumber
   * @return ownerPhoneNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OWNER_PHONE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MobileNoInfo getOwnerPhoneNumber() {
    return ownerPhoneNumber;
  }


  @JsonProperty(JSON_PROPERTY_OWNER_PHONE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwnerPhoneNumber(@javax.annotation.Nullable MobileNoInfo ownerPhoneNumber) {
    this.ownerPhoneNumber = ownerPhoneNumber;
  }

  public UpdateShopRequest ownerIdType(@javax.annotation.Nullable OwnerIdTypeEnum ownerIdType) {
    
    this.ownerIdType = ownerIdType;
    return this;
  }

  /**
   * Owner identifier type
   * @return ownerIdType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OWNER_ID_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OwnerIdTypeEnum getOwnerIdType() {
    return ownerIdType;
  }


  @JsonProperty(JSON_PROPERTY_OWNER_ID_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwnerIdType(@javax.annotation.Nullable OwnerIdTypeEnum ownerIdType) {
    this.ownerIdType = ownerIdType;
  }

  public UpdateShopRequest ownerIdNo(@javax.annotation.Nullable String ownerIdNo) {
    
    this.ownerIdNo = ownerIdNo;
    return this;
  }

  /**
   * Owner identifier number. Length depends on ownerIdType - KTP (16), SIM (12-14), Passport (8), NIB (>=13), SIUP (free text)
   * @return ownerIdNo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OWNER_ID_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOwnerIdNo() {
    return ownerIdNo;
  }


  @JsonProperty(JSON_PROPERTY_OWNER_ID_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwnerIdNo(@javax.annotation.Nullable String ownerIdNo) {
    this.ownerIdNo = ownerIdNo;
  }

  public UpdateShopRequest deviceNumber(@javax.annotation.Nullable String deviceNumber) {
    
    this.deviceNumber = deviceNumber;
    return this;
  }

  /**
   * Device number
   * @return deviceNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEVICE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDeviceNumber() {
    return deviceNumber;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceNumber(@javax.annotation.Nullable String deviceNumber) {
    this.deviceNumber = deviceNumber;
  }

  public UpdateShopRequest posNumber(@javax.annotation.Nullable String posNumber) {
    
    this.posNumber = posNumber;
    return this;
  }

  /**
   * POS number
   * @return posNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POS_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPosNumber() {
    return posNumber;
  }


  @JsonProperty(JSON_PROPERTY_POS_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPosNumber(@javax.annotation.Nullable String posNumber) {
    this.posNumber = posNumber;
  }

  public UpdateShopRequest apiVersion(@javax.annotation.Nullable String apiVersion) {
    
    this.apiVersion = apiVersion;
    return this;
  }

  /**
   * API version flag. Use > 2 for new attributes
   * @return apiVersion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_API_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getApiVersion() {
    return apiVersion;
  }


  @JsonProperty(JSON_PROPERTY_API_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApiVersion(@javax.annotation.Nullable String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public UpdateShopRequest businessEntity(@javax.annotation.Nullable BusinessEntityEnum businessEntity) {
    
    this.businessEntity = businessEntity;
    return this;
  }

  /**
   * Business entity type
   * @return businessEntity
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUSINESS_ENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BusinessEntityEnum getBusinessEntity() {
    return businessEntity;
  }


  @JsonProperty(JSON_PROPERTY_BUSINESS_ENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBusinessEntity(@javax.annotation.Nullable BusinessEntityEnum businessEntity) {
    this.businessEntity = businessEntity;
  }

  public UpdateShopRequest shopOwning(@javax.annotation.Nullable ShopOwningEnum shopOwning) {
    
    this.shopOwning = shopOwning;
    return this;
  }

  /**
   * Shop owning information
   * @return shopOwning
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHOP_OWNING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ShopOwningEnum getShopOwning() {
    return shopOwning;
  }


  @JsonProperty(JSON_PROPERTY_SHOP_OWNING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShopOwning(@javax.annotation.Nullable ShopOwningEnum shopOwning) {
    this.shopOwning = shopOwning;
  }

  public UpdateShopRequest shopBizType(@javax.annotation.Nullable ShopBizTypeEnum shopBizType) {
    
    this.shopBizType = shopBizType;
    return this;
  }

  /**
   * Shop business type
   * @return shopBizType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHOP_BIZ_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ShopBizTypeEnum getShopBizType() {
    return shopBizType;
  }


  @JsonProperty(JSON_PROPERTY_SHOP_BIZ_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShopBizType(@javax.annotation.Nullable ShopBizTypeEnum shopBizType) {
    this.shopBizType = shopBizType;
  }

  public UpdateShopRequest businessDocs(@javax.annotation.Nullable List<BusinessDocs> businessDocs) {
    
    this.businessDocs = businessDocs;
    return this;
  }

  public UpdateShopRequest addBusinessDocsItem(BusinessDocs businessDocsItem) {
    if (this.businessDocs == null) {
      this.businessDocs = new ArrayList<>();
    }
    this.businessDocs.add(businessDocsItem);
    return this;
  }

  /**
   * Business documents. \"individu\" entity can only use KTP and SIM. Other entities can use SIUP and NIB
   * @return businessDocs
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUSINESS_DOCS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BusinessDocs> getBusinessDocs() {
    return businessDocs;
  }


  @JsonProperty(JSON_PROPERTY_BUSINESS_DOCS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBusinessDocs(@javax.annotation.Nullable List<BusinessDocs> businessDocs) {
    this.businessDocs = businessDocs;
  }

  public UpdateShopRequest businessEndDate(@javax.annotation.Nullable String businessEndDate) {
    
    this.businessEndDate = businessEndDate;
    return this;
  }

  /**
   * Business end date, in format YYYY-MM-dd
   * @return businessEndDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUSINESS_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBusinessEndDate() {
    return businessEndDate;
  }


  @JsonProperty(JSON_PROPERTY_BUSINESS_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBusinessEndDate(@javax.annotation.Nullable String businessEndDate) {
    this.businessEndDate = businessEndDate;
  }

  public UpdateShopRequest taxNo(@javax.annotation.Nullable String taxNo) {
    
    this.taxNo = taxNo;
    return this;
  }

  /**
   * Tax number (NPWP). Must be 15 digits
   * @return taxNo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAX_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTaxNo() {
    return taxNo;
  }


  @JsonProperty(JSON_PROPERTY_TAX_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTaxNo(@javax.annotation.Nullable String taxNo) {
    this.taxNo = taxNo;
  }

  public UpdateShopRequest taxAddress(@javax.annotation.Nullable AddressInfo taxAddress) {
    
    this.taxAddress = taxAddress;
    return this;
  }

  /**
   * Get taxAddress
   * @return taxAddress
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAX_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AddressInfo getTaxAddress() {
    return taxAddress;
  }


  @JsonProperty(JSON_PROPERTY_TAX_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTaxAddress(@javax.annotation.Nullable AddressInfo taxAddress) {
    this.taxAddress = taxAddress;
  }

  public UpdateShopRequest brandName(@javax.annotation.Nullable String brandName) {
    
    this.brandName = brandName;
    return this;
  }

  /**
   * Brand name on legal name or tax name
   * @return brandName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BRAND_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBrandName() {
    return brandName;
  }


  @JsonProperty(JSON_PROPERTY_BRAND_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBrandName(@javax.annotation.Nullable String brandName) {
    this.brandName = brandName;
  }

  public UpdateShopRequest directorPics(@javax.annotation.Nullable List<PicInfo> directorPics) {
    
    this.directorPics = directorPics;
    return this;
  }

  public UpdateShopRequest addDirectorPicsItem(PicInfo directorPicsItem) {
    if (this.directorPics == null) {
      this.directorPics = new ArrayList<>();
    }
    this.directorPics.add(directorPicsItem);
    return this;
  }

  /**
   * Director as a PIC of shop
   * @return directorPics
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIRECTOR_PICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PicInfo> getDirectorPics() {
    return directorPics;
  }


  @JsonProperty(JSON_PROPERTY_DIRECTOR_PICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDirectorPics(@javax.annotation.Nullable List<PicInfo> directorPics) {
    this.directorPics = directorPics;
  }

  public UpdateShopRequest nonDirectorPics(@javax.annotation.Nullable List<PicInfo> nonDirectorPics) {
    
    this.nonDirectorPics = nonDirectorPics;
    return this;
  }

  public UpdateShopRequest addNonDirectorPicsItem(PicInfo nonDirectorPicsItem) {
    if (this.nonDirectorPics == null) {
      this.nonDirectorPics = new ArrayList<>();
    }
    this.nonDirectorPics.add(nonDirectorPicsItem);
    return this;
  }

  /**
   * Non director which become an PIC of shop
   * @return nonDirectorPics
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NON_DIRECTOR_PICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PicInfo> getNonDirectorPics() {
    return nonDirectorPics;
  }


  @JsonProperty(JSON_PROPERTY_NON_DIRECTOR_PICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNonDirectorPics(@javax.annotation.Nullable List<PicInfo> nonDirectorPics) {
    this.nonDirectorPics = nonDirectorPics;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateShopRequest updateShopRequest = (UpdateShopRequest) o;
    return Objects.equals(this.shopId, updateShopRequest.shopId) &&
        Objects.equals(this.merchantId, updateShopRequest.merchantId) &&
        Objects.equals(this.shopIdType, updateShopRequest.shopIdType) &&
        Objects.equals(this.mainName, updateShopRequest.mainName) &&
        Objects.equals(this.shopAddress, updateShopRequest.shopAddress) &&
        Objects.equals(this.shopDesc, updateShopRequest.shopDesc) &&
        Objects.equals(this.newExternalShopId, updateShopRequest.newExternalShopId) &&
        Objects.equals(this.mccCodes, updateShopRequest.mccCodes) &&
        Objects.equals(this.logoUrlMap, updateShopRequest.logoUrlMap) &&
        Objects.equals(this.extInfo, updateShopRequest.extInfo) &&
        Objects.equals(this.sizeType, updateShopRequest.sizeType) &&
        Objects.equals(this.ln, updateShopRequest.ln) &&
        Objects.equals(this.lat, updateShopRequest.lat) &&
        Objects.equals(this.loyalty, updateShopRequest.loyalty) &&
        Objects.equals(this.ownerAddress, updateShopRequest.ownerAddress) &&
        Objects.equals(this.ownerName, updateShopRequest.ownerName) &&
        Objects.equals(this.ownerPhoneNumber, updateShopRequest.ownerPhoneNumber) &&
        Objects.equals(this.ownerIdType, updateShopRequest.ownerIdType) &&
        Objects.equals(this.ownerIdNo, updateShopRequest.ownerIdNo) &&
        Objects.equals(this.deviceNumber, updateShopRequest.deviceNumber) &&
        Objects.equals(this.posNumber, updateShopRequest.posNumber) &&
        Objects.equals(this.apiVersion, updateShopRequest.apiVersion) &&
        Objects.equals(this.businessEntity, updateShopRequest.businessEntity) &&
        Objects.equals(this.shopOwning, updateShopRequest.shopOwning) &&
        Objects.equals(this.shopBizType, updateShopRequest.shopBizType) &&
        Objects.equals(this.businessDocs, updateShopRequest.businessDocs) &&
        Objects.equals(this.businessEndDate, updateShopRequest.businessEndDate) &&
        Objects.equals(this.taxNo, updateShopRequest.taxNo) &&
        Objects.equals(this.taxAddress, updateShopRequest.taxAddress) &&
        Objects.equals(this.brandName, updateShopRequest.brandName) &&
        Objects.equals(this.directorPics, updateShopRequest.directorPics) &&
        Objects.equals(this.nonDirectorPics, updateShopRequest.nonDirectorPics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shopId, merchantId, shopIdType, mainName, shopAddress, shopDesc, newExternalShopId, mccCodes, logoUrlMap, extInfo, sizeType, ln, lat, loyalty, ownerAddress, ownerName, ownerPhoneNumber, ownerIdType, ownerIdNo, deviceNumber, posNumber, apiVersion, businessEntity, shopOwning, shopBizType, businessDocs, businessEndDate, taxNo, taxAddress, brandName, directorPics, nonDirectorPics);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateShopRequest {\n");
    sb.append("    shopId: ").append(toIndentedString(shopId)).append("\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    shopIdType: ").append(toIndentedString(shopIdType)).append("\n");
    sb.append("    mainName: ").append(toIndentedString(mainName)).append("\n");
    sb.append("    shopAddress: ").append(toIndentedString(shopAddress)).append("\n");
    sb.append("    shopDesc: ").append(toIndentedString(shopDesc)).append("\n");
    sb.append("    newExternalShopId: ").append(toIndentedString(newExternalShopId)).append("\n");
    sb.append("    mccCodes: ").append(toIndentedString(mccCodes)).append("\n");
    sb.append("    logoUrlMap: ").append(toIndentedString(logoUrlMap)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    sizeType: ").append(toIndentedString(sizeType)).append("\n");
    sb.append("    ln: ").append(toIndentedString(ln)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    loyalty: ").append(toIndentedString(loyalty)).append("\n");
    sb.append("    ownerAddress: ").append(toIndentedString(ownerAddress)).append("\n");
    sb.append("    ownerName: ").append(toIndentedString(ownerName)).append("\n");
    sb.append("    ownerPhoneNumber: ").append(toIndentedString(ownerPhoneNumber)).append("\n");
    sb.append("    ownerIdType: ").append(toIndentedString(ownerIdType)).append("\n");
    sb.append("    ownerIdNo: ").append(toIndentedString(ownerIdNo)).append("\n");
    sb.append("    deviceNumber: ").append(toIndentedString(deviceNumber)).append("\n");
    sb.append("    posNumber: ").append(toIndentedString(posNumber)).append("\n");
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    businessEntity: ").append(toIndentedString(businessEntity)).append("\n");
    sb.append("    shopOwning: ").append(toIndentedString(shopOwning)).append("\n");
    sb.append("    shopBizType: ").append(toIndentedString(shopBizType)).append("\n");
    sb.append("    businessDocs: ").append(toIndentedString(businessDocs)).append("\n");
    sb.append("    businessEndDate: ").append(toIndentedString(businessEndDate)).append("\n");
    sb.append("    taxNo: ").append(toIndentedString(taxNo)).append("\n");
    sb.append("    taxAddress: ").append(toIndentedString(taxAddress)).append("\n");
    sb.append("    brandName: ").append(toIndentedString(brandName)).append("\n");
    sb.append("    directorPics: ").append(toIndentedString(directorPics)).append("\n");
    sb.append("    nonDirectorPics: ").append(toIndentedString(nonDirectorPics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
