/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.merchantmanagement.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.dana.merchantmanagement.v1.model.ResultInfo;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UpdateDivisionResponseResponseBody
 */
@JsonPropertyOrder({
  UpdateDivisionResponseResponseBody.JSON_PROPERTY_RESULT_INFO
})
@JsonTypeName("UpdateDivisionResponse_response_body")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class UpdateDivisionResponseResponseBody {
  public static final String JSON_PROPERTY_RESULT_INFO = "resultInfo";
  @javax.annotation.Nonnull
  private ResultInfo resultInfo;

  public UpdateDivisionResponseResponseBody() {
  }

  public UpdateDivisionResponseResponseBody resultInfo(@javax.annotation.Nonnull ResultInfo resultInfo) {
    
    this.resultInfo = resultInfo;
    return this;
  }

  /**
   * Get resultInfo
   * @return resultInfo
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESULT_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ResultInfo getResultInfo() {
    return resultInfo;
  }


  @JsonProperty(JSON_PROPERTY_RESULT_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResultInfo(@javax.annotation.Nonnull ResultInfo resultInfo) {
    this.resultInfo = resultInfo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateDivisionResponseResponseBody updateDivisionResponseResponseBody = (UpdateDivisionResponseResponseBody) o;
    return Objects.equals(this.resultInfo, updateDivisionResponseResponseBody.resultInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateDivisionResponseResponseBody {\n");
    sb.append("    resultInfo: ").append(toIndentedString(resultInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
