/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.paymentgateway.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.dana.paymentgateway.v1.model.ConsultPayPaymentInfo;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConsultPayResponse
 */
@JsonPropertyOrder({
  ConsultPayResponse.JSON_PROPERTY_RESPONSE_CODE,
  ConsultPayResponse.JSON_PROPERTY_RESPONSE_MESSAGE,
  ConsultPayResponse.JSON_PROPERTY_PAYMENT_INFOS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class ConsultPayResponse {
  public static final String JSON_PROPERTY_RESPONSE_CODE = "responseCode";
  @javax.annotation.Nullable
  private String responseCode;

  public static final String JSON_PROPERTY_RESPONSE_MESSAGE = "responseMessage";
  @javax.annotation.Nullable
  private String responseMessage;

  public static final String JSON_PROPERTY_PAYMENT_INFOS = "paymentInfos";
  @javax.annotation.Nullable
  private List<ConsultPayPaymentInfo> paymentInfos = new ArrayList<>();

  public ConsultPayResponse() {
  }

  public ConsultPayResponse responseCode(@javax.annotation.Nullable String responseCode) {
    
    this.responseCode = responseCode;
    return this;
  }

  /**
   * Response code. Refer to https://dashboard.dana.id/api-docs/read/237#paymentgatewayprod-ConsultPay-ResponseCodeandMessage
   * @return responseCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESPONSE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResponseCode() {
    return responseCode;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponseCode(@javax.annotation.Nullable String responseCode) {
    this.responseCode = responseCode;
  }

  public ConsultPayResponse responseMessage(@javax.annotation.Nullable String responseMessage) {
    
    this.responseMessage = responseMessage;
    return this;
  }

  /**
   * Response message. Refer to https://dashboard.dana.id/api-docs/read/237#paymentgatewayprod-ConsultPay-ResponseCodeandMessage
   * @return responseMessage
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESPONSE_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResponseMessage() {
    return responseMessage;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponseMessage(@javax.annotation.Nullable String responseMessage) {
    this.responseMessage = responseMessage;
  }

  public ConsultPayResponse paymentInfos(@javax.annotation.Nullable List<ConsultPayPaymentInfo> paymentInfos) {
    
    this.paymentInfos = paymentInfos;
    return this;
  }

  public ConsultPayResponse addPaymentInfosItem(ConsultPayPaymentInfo paymentInfosItem) {
    if (this.paymentInfos == null) {
      this.paymentInfos = new ArrayList<>();
    }
    this.paymentInfos.add(paymentInfosItem);
    return this;
  }

  /**
   * Define list of payment information that includes payment method and payment option for transaction
   * @return paymentInfos
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_INFOS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ConsultPayPaymentInfo> getPaymentInfos() {
    return paymentInfos;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_INFOS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentInfos(@javax.annotation.Nullable List<ConsultPayPaymentInfo> paymentInfos) {
    this.paymentInfos = paymentInfos;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsultPayResponse consultPayResponse = (ConsultPayResponse) o;
    return Objects.equals(this.responseCode, consultPayResponse.responseCode) &&
        Objects.equals(this.responseMessage, consultPayResponse.responseMessage) &&
        Objects.equals(this.paymentInfos, consultPayResponse.paymentInfos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseCode, responseMessage, paymentInfos);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsultPayResponse {\n");
    sb.append("    responseCode: ").append(toIndentedString(responseCode)).append("\n");
    sb.append("    responseMessage: ").append(toIndentedString(responseMessage)).append("\n");
    sb.append("    paymentInfos: ").append(toIndentedString(paymentInfos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
