/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.paymentgateway.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.dana.paymentgateway.v1.model.EnvInfo;
import id.dana.paymentgateway.v1.model.OrderApiObject;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateOrderByApiAdditionalInfo
 */
@JsonPropertyOrder({
  CreateOrderByApiAdditionalInfo.JSON_PROPERTY_MCC,
  CreateOrderByApiAdditionalInfo.JSON_PROPERTY_EXTEND_INFO,
  CreateOrderByApiAdditionalInfo.JSON_PROPERTY_ENV_INFO,
  CreateOrderByApiAdditionalInfo.JSON_PROPERTY_ORDER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class CreateOrderByApiAdditionalInfo {
  public static final String JSON_PROPERTY_MCC = "mcc";
  @javax.annotation.Nonnull
  private String mcc;

  public static final String JSON_PROPERTY_EXTEND_INFO = "extendInfo";
  @javax.annotation.Nullable
  private String extendInfo;

  public static final String JSON_PROPERTY_ENV_INFO = "envInfo";
  @javax.annotation.Nonnull
  private EnvInfo envInfo;

  public static final String JSON_PROPERTY_ORDER = "order";
  @javax.annotation.Nullable
  private OrderApiObject order;

  public CreateOrderByApiAdditionalInfo() {
  }

  public CreateOrderByApiAdditionalInfo mcc(@javax.annotation.Nonnull String mcc) {
    
    this.mcc = mcc;
    return this;
  }

  /**
   * Additional information of merchant category code. This parameter is used to identify the type of business in which a merchant is engaged. Refer to Details of https://dashboard.dana.id/api-docs/read/197#OpenAPI-MerchantCategoryCode
   * @return mcc
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MCC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMcc() {
    return mcc;
  }


  @JsonProperty(JSON_PROPERTY_MCC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMcc(@javax.annotation.Nonnull String mcc) {
    this.mcc = mcc;
  }

  public CreateOrderByApiAdditionalInfo extendInfo(@javax.annotation.Nullable String extendInfo) {
    
    this.extendInfo = extendInfo;
    return this;
  }

  /**
   * Additional information of extend such as partner passthrough and risk information
   * @return extendInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTEND_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExtendInfo() {
    return extendInfo;
  }


  @JsonProperty(JSON_PROPERTY_EXTEND_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtendInfo(@javax.annotation.Nullable String extendInfo) {
    this.extendInfo = extendInfo;
  }

  public CreateOrderByApiAdditionalInfo envInfo(@javax.annotation.Nonnull EnvInfo envInfo) {
    
    this.envInfo = envInfo;
    return this;
  }

  /**
   * Additional information of environment info
   * @return envInfo
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ENV_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public EnvInfo getEnvInfo() {
    return envInfo;
  }


  @JsonProperty(JSON_PROPERTY_ENV_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEnvInfo(@javax.annotation.Nonnull EnvInfo envInfo) {
    this.envInfo = envInfo;
  }

  public CreateOrderByApiAdditionalInfo order(@javax.annotation.Nullable OrderApiObject order) {
    
    this.order = order;
    return this;
  }

  /**
   * Additional information of order
   * @return order
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OrderApiObject getOrder() {
    return order;
  }


  @JsonProperty(JSON_PROPERTY_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrder(@javax.annotation.Nullable OrderApiObject order) {
    this.order = order;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateOrderByApiAdditionalInfo createOrderByApiAdditionalInfo = (CreateOrderByApiAdditionalInfo) o;
    return Objects.equals(this.mcc, createOrderByApiAdditionalInfo.mcc) &&
        Objects.equals(this.extendInfo, createOrderByApiAdditionalInfo.extendInfo) &&
        Objects.equals(this.envInfo, createOrderByApiAdditionalInfo.envInfo) &&
        Objects.equals(this.order, createOrderByApiAdditionalInfo.order);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mcc, extendInfo, envInfo, order);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateOrderByApiAdditionalInfo {\n");
    sb.append("    mcc: ").append(toIndentedString(mcc)).append("\n");
    sb.append("    extendInfo: ").append(toIndentedString(extendInfo)).append("\n");
    sb.append("    envInfo: ").append(toIndentedString(envInfo)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
