/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.paymentgateway.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * EnvInfo
 */
@JsonPropertyOrder({
  EnvInfo.JSON_PROPERTY_SESSION_ID,
  EnvInfo.JSON_PROPERTY_TOKEN_ID,
  EnvInfo.JSON_PROPERTY_WEBSITE_LANGUAGE,
  EnvInfo.JSON_PROPERTY_CLIENT_IP,
  EnvInfo.JSON_PROPERTY_OS_TYPE,
  EnvInfo.JSON_PROPERTY_APP_VERSION,
  EnvInfo.JSON_PROPERTY_SDK_VERSION,
  EnvInfo.JSON_PROPERTY_SOURCE_PLATFORM,
  EnvInfo.JSON_PROPERTY_ORDER_OS_TYPE,
  EnvInfo.JSON_PROPERTY_MERCHANT_APP_VERSION,
  EnvInfo.JSON_PROPERTY_TERMINAL_TYPE,
  EnvInfo.JSON_PROPERTY_ORDER_TERMINAL_TYPE,
  EnvInfo.JSON_PROPERTY_EXTEND_INFO,
  EnvInfo.JSON_PROPERTY_CLIENT_KEY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class EnvInfo {
  public static final String JSON_PROPERTY_SESSION_ID = "sessionId";
  @javax.annotation.Nullable
  private String sessionId;

  public static final String JSON_PROPERTY_TOKEN_ID = "tokenId";
  @javax.annotation.Nullable
  private String tokenId;

  public static final String JSON_PROPERTY_WEBSITE_LANGUAGE = "websiteLanguage";
  @javax.annotation.Nullable
  private String websiteLanguage;

  public static final String JSON_PROPERTY_CLIENT_IP = "clientIp";
  @javax.annotation.Nullable
  private String clientIp;

  public static final String JSON_PROPERTY_OS_TYPE = "osType";
  @javax.annotation.Nullable
  private String osType;

  public static final String JSON_PROPERTY_APP_VERSION = "appVersion";
  @javax.annotation.Nullable
  private String appVersion;

  public static final String JSON_PROPERTY_SDK_VERSION = "sdkVersion";
  @javax.annotation.Nullable
  private String sdkVersion;

  /**
   * The source platform is always independent payment gateway (IPG)
   */
  public enum SourcePlatformEnum {
    IPG(String.valueOf("IPG")),
    
    UNSPECIFIED(String.valueOf(""));

    private String value;

    SourcePlatformEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SourcePlatformEnum fromValue(String value) {
      for (SourcePlatformEnum b : SourcePlatformEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SOURCE_PLATFORM = "sourcePlatform";
  @javax.annotation.Nonnull
  private SourcePlatformEnum sourcePlatform;

  public static final String JSON_PROPERTY_ORDER_OS_TYPE = "orderOsType";
  @javax.annotation.Nullable
  private String orderOsType;

  public static final String JSON_PROPERTY_MERCHANT_APP_VERSION = "merchantAppVersion";
  @javax.annotation.Nullable
  private String merchantAppVersion;

  /**
   * Terminal type. The enums:&lt;br&gt; * APP - Mobile Application&lt;br&gt; * WEB - Browser Web&lt;br&gt; * WAP - Mobile Wap&lt;br&gt; * SYSTEM - System Call&lt;br&gt; 
   */
  public enum TerminalTypeEnum {
    APP(String.valueOf("APP")),
    
    WEB(String.valueOf("WEB")),
    
    WAP(String.valueOf("WAP")),
    
    SYSTEM(String.valueOf("SYSTEM")),
    
    UNSPECIFIED(String.valueOf(""));

    private String value;

    TerminalTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TerminalTypeEnum fromValue(String value) {
      for (TerminalTypeEnum b : TerminalTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TERMINAL_TYPE = "terminalType";
  @javax.annotation.Nonnull
  private TerminalTypeEnum terminalType;

  /**
   * Order terminal type. The enums:&lt;br&gt; * APP - Mobile Application&lt;br&gt; * WEB - Browser Web&lt;br&gt; * WAP - Mobile Wap&lt;br&gt; * SYSTEM - System Call&lt;br&gt; 
   */
  public enum OrderTerminalTypeEnum {
    APP(String.valueOf("APP")),
    
    WEB(String.valueOf("WEB")),
    
    WAP(String.valueOf("WAP")),
    
    SYSTEM(String.valueOf("SYSTEM")),
    
    UNSPECIFIED(String.valueOf(""));

    private String value;

    OrderTerminalTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OrderTerminalTypeEnum fromValue(String value) {
      for (OrderTerminalTypeEnum b : OrderTerminalTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ORDER_TERMINAL_TYPE = "orderTerminalType";
  @javax.annotation.Nullable
  private OrderTerminalTypeEnum orderTerminalType;

  public static final String JSON_PROPERTY_EXTEND_INFO = "extendInfo";
  @javax.annotation.Nullable
  private String extendInfo;

  public static final String JSON_PROPERTY_CLIENT_KEY = "clientKey";
  @javax.annotation.Nullable
  private String clientKey;

  public EnvInfo() {
  }

  public EnvInfo sessionId(@javax.annotation.Nullable String sessionId) {
    
    this.sessionId = sessionId;
    return this;
  }

  /**
   * Session identifier
   * @return sessionId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SESSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSessionId() {
    return sessionId;
  }


  @JsonProperty(JSON_PROPERTY_SESSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSessionId(@javax.annotation.Nullable String sessionId) {
    this.sessionId = sessionId;
  }

  public EnvInfo tokenId(@javax.annotation.Nullable String tokenId) {
    
    this.tokenId = tokenId;
    return this;
  }

  /**
   * Token identifier
   * @return tokenId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOKEN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTokenId() {
    return tokenId;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTokenId(@javax.annotation.Nullable String tokenId) {
    this.tokenId = tokenId;
  }

  public EnvInfo websiteLanguage(@javax.annotation.Nullable String websiteLanguage) {
    
    this.websiteLanguage = websiteLanguage;
    return this;
  }

  /**
   * Website language
   * @return websiteLanguage
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEBSITE_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWebsiteLanguage() {
    return websiteLanguage;
  }


  @JsonProperty(JSON_PROPERTY_WEBSITE_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebsiteLanguage(@javax.annotation.Nullable String websiteLanguage) {
    this.websiteLanguage = websiteLanguage;
  }

  public EnvInfo clientIp(@javax.annotation.Nullable String clientIp) {
    
    this.clientIp = clientIp;
    return this;
  }

  /**
   * Client IP address
   * @return clientIp
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLIENT_IP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClientIp() {
    return clientIp;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_IP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientIp(@javax.annotation.Nullable String clientIp) {
    this.clientIp = clientIp;
  }

  public EnvInfo osType(@javax.annotation.Nullable String osType) {
    
    this.osType = osType;
    return this;
  }

  /**
   * Operating system type
   * @return osType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOsType() {
    return osType;
  }


  @JsonProperty(JSON_PROPERTY_OS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsType(@javax.annotation.Nullable String osType) {
    this.osType = osType;
  }

  public EnvInfo appVersion(@javax.annotation.Nullable String appVersion) {
    
    this.appVersion = appVersion;
    return this;
  }

  /**
   * App version
   * @return appVersion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APP_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAppVersion() {
    return appVersion;
  }


  @JsonProperty(JSON_PROPERTY_APP_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAppVersion(@javax.annotation.Nullable String appVersion) {
    this.appVersion = appVersion;
  }

  public EnvInfo sdkVersion(@javax.annotation.Nullable String sdkVersion) {
    
    this.sdkVersion = sdkVersion;
    return this;
  }

  /**
   * SDK version
   * @return sdkVersion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SDK_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSdkVersion() {
    return sdkVersion;
  }


  @JsonProperty(JSON_PROPERTY_SDK_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSdkVersion(@javax.annotation.Nullable String sdkVersion) {
    this.sdkVersion = sdkVersion;
  }

  public EnvInfo sourcePlatform(@javax.annotation.Nonnull SourcePlatformEnum sourcePlatform) {
    
    this.sourcePlatform = sourcePlatform;
    return this;
  }

  /**
   * The source platform is always independent payment gateway (IPG)
   * @return sourcePlatform
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SOURCE_PLATFORM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SourcePlatformEnum getSourcePlatform() {
    return sourcePlatform;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_PLATFORM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSourcePlatform(@javax.annotation.Nonnull SourcePlatformEnum sourcePlatform) {
    this.sourcePlatform = sourcePlatform;
  }

  public EnvInfo orderOsType(@javax.annotation.Nullable String orderOsType) {
    
    this.orderOsType = orderOsType;
    return this;
  }

  /**
   * Order operating system type
   * @return orderOsType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER_OS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrderOsType() {
    return orderOsType;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_OS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderOsType(@javax.annotation.Nullable String orderOsType) {
    this.orderOsType = orderOsType;
  }

  public EnvInfo merchantAppVersion(@javax.annotation.Nullable String merchantAppVersion) {
    
    this.merchantAppVersion = merchantAppVersion;
    return this;
  }

  /**
   * Merchant App version
   * @return merchantAppVersion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MERCHANT_APP_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMerchantAppVersion() {
    return merchantAppVersion;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_APP_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchantAppVersion(@javax.annotation.Nullable String merchantAppVersion) {
    this.merchantAppVersion = merchantAppVersion;
  }

  public EnvInfo terminalType(@javax.annotation.Nonnull TerminalTypeEnum terminalType) {
    
    this.terminalType = terminalType;
    return this;
  }

  /**
   * Terminal type. The enums:&lt;br&gt; * APP - Mobile Application&lt;br&gt; * WEB - Browser Web&lt;br&gt; * WAP - Mobile Wap&lt;br&gt; * SYSTEM - System Call&lt;br&gt; 
   * @return terminalType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TERMINAL_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TerminalTypeEnum getTerminalType() {
    return terminalType;
  }


  @JsonProperty(JSON_PROPERTY_TERMINAL_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTerminalType(@javax.annotation.Nonnull TerminalTypeEnum terminalType) {
    this.terminalType = terminalType;
  }

  public EnvInfo orderTerminalType(@javax.annotation.Nullable OrderTerminalTypeEnum orderTerminalType) {
    
    this.orderTerminalType = orderTerminalType;
    return this;
  }

  /**
   * Order terminal type. The enums:&lt;br&gt; * APP - Mobile Application&lt;br&gt; * WEB - Browser Web&lt;br&gt; * WAP - Mobile Wap&lt;br&gt; * SYSTEM - System Call&lt;br&gt; 
   * @return orderTerminalType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER_TERMINAL_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OrderTerminalTypeEnum getOrderTerminalType() {
    return orderTerminalType;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_TERMINAL_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderTerminalType(@javax.annotation.Nullable OrderTerminalTypeEnum orderTerminalType) {
    this.orderTerminalType = orderTerminalType;
  }

  public EnvInfo extendInfo(@javax.annotation.Nullable String extendInfo) {
    
    this.extendInfo = extendInfo;
    return this;
  }

  /**
   * Extend information
   * @return extendInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTEND_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExtendInfo() {
    return extendInfo;
  }


  @JsonProperty(JSON_PROPERTY_EXTEND_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtendInfo(@javax.annotation.Nullable String extendInfo) {
    this.extendInfo = extendInfo;
  }

  public EnvInfo clientKey(@javax.annotation.Nullable String clientKey) {
    
    this.clientKey = clientKey;
    return this;
  }

  /**
   * Unique identifier for partner was generated by DANA
   * @return clientKey
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLIENT_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClientKey() {
    return clientKey;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientKey(@javax.annotation.Nullable String clientKey) {
    this.clientKey = clientKey;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnvInfo envInfo = (EnvInfo) o;
    return Objects.equals(this.sessionId, envInfo.sessionId) &&
        Objects.equals(this.tokenId, envInfo.tokenId) &&
        Objects.equals(this.websiteLanguage, envInfo.websiteLanguage) &&
        Objects.equals(this.clientIp, envInfo.clientIp) &&
        Objects.equals(this.osType, envInfo.osType) &&
        Objects.equals(this.appVersion, envInfo.appVersion) &&
        Objects.equals(this.sdkVersion, envInfo.sdkVersion) &&
        Objects.equals(this.sourcePlatform, envInfo.sourcePlatform) &&
        Objects.equals(this.orderOsType, envInfo.orderOsType) &&
        Objects.equals(this.merchantAppVersion, envInfo.merchantAppVersion) &&
        Objects.equals(this.terminalType, envInfo.terminalType) &&
        Objects.equals(this.orderTerminalType, envInfo.orderTerminalType) &&
        Objects.equals(this.extendInfo, envInfo.extendInfo) &&
        Objects.equals(this.clientKey, envInfo.clientKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessionId, tokenId, websiteLanguage, clientIp, osType, appVersion, sdkVersion, sourcePlatform, orderOsType, merchantAppVersion, terminalType, orderTerminalType, extendInfo, clientKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnvInfo {\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    websiteLanguage: ").append(toIndentedString(websiteLanguage)).append("\n");
    sb.append("    clientIp: ").append(toIndentedString(clientIp)).append("\n");
    sb.append("    osType: ").append(toIndentedString(osType)).append("\n");
    sb.append("    appVersion: ").append(toIndentedString(appVersion)).append("\n");
    sb.append("    sdkVersion: ").append(toIndentedString(sdkVersion)).append("\n");
    sb.append("    sourcePlatform: ").append(toIndentedString(sourcePlatform)).append("\n");
    sb.append("    orderOsType: ").append(toIndentedString(orderOsType)).append("\n");
    sb.append("    merchantAppVersion: ").append(toIndentedString(merchantAppVersion)).append("\n");
    sb.append("    terminalType: ").append(toIndentedString(terminalType)).append("\n");
    sb.append("    orderTerminalType: ").append(toIndentedString(orderTerminalType)).append("\n");
    sb.append("    extendInfo: ").append(toIndentedString(extendInfo)).append("\n");
    sb.append("    clientKey: ").append(toIndentedString(clientKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

