/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.paymentgateway.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.dana.paymentgateway.v1.model.Buyer;
import id.dana.paymentgateway.v1.model.Goods;
import id.dana.paymentgateway.v1.model.ShippingInfo;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * OrderRedirectObject
 */
@JsonPropertyOrder({
  OrderRedirectObject.JSON_PROPERTY_ORDER_TITLE,
  OrderRedirectObject.JSON_PROPERTY_MERCHANT_TRANS_TYPE,
  OrderRedirectObject.JSON_PROPERTY_BUYER,
  OrderRedirectObject.JSON_PROPERTY_GOODS,
  OrderRedirectObject.JSON_PROPERTY_SHIPPING_INFO,
  OrderRedirectObject.JSON_PROPERTY_EXTEND_INFO,
  OrderRedirectObject.JSON_PROPERTY_CREATED_TIME,
  OrderRedirectObject.JSON_PROPERTY_ORDER_MEMO,
  OrderRedirectObject.JSON_PROPERTY_SCENARIO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class OrderRedirectObject {
  public static final String JSON_PROPERTY_ORDER_TITLE = "orderTitle";
  @javax.annotation.Nonnull
  private String orderTitle;

  public static final String JSON_PROPERTY_MERCHANT_TRANS_TYPE = "merchantTransType";
  @javax.annotation.Nullable
  private String merchantTransType;

  public static final String JSON_PROPERTY_BUYER = "buyer";
  @javax.annotation.Nullable
  private Buyer buyer;

  public static final String JSON_PROPERTY_GOODS = "goods";
  @javax.annotation.Nullable
  private List<Goods> goods = new ArrayList<>();

  public static final String JSON_PROPERTY_SHIPPING_INFO = "shippingInfo";
  @javax.annotation.Nullable
  private List<ShippingInfo> shippingInfo = new ArrayList<>();

  public static final String JSON_PROPERTY_EXTEND_INFO = "extendInfo";
  @javax.annotation.Nullable
  private String extendInfo;

  public static final String JSON_PROPERTY_CREATED_TIME = "createdTime";
  @javax.annotation.Nullable
  private String createdTime;

  public static final String JSON_PROPERTY_ORDER_MEMO = "orderMemo";
  @javax.annotation.Nullable
  private String orderMemo;

  /**
   * For Payment Gateway Drop-in scenario, need to fill it as REDIRECT
   */
  public enum ScenarioEnum {
    REDIRECT(String.valueOf("REDIRECT")),
    
    UNSPECIFIED(String.valueOf(""));

    private String value;

    ScenarioEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ScenarioEnum fromValue(String value) {
      for (ScenarioEnum b : ScenarioEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SCENARIO = "scenario";
  @javax.annotation.Nullable
  private ScenarioEnum scenario;

  public OrderRedirectObject() {
  }

  public OrderRedirectObject orderTitle(@javax.annotation.Nonnull String orderTitle) {
    
    this.orderTitle = orderTitle;
    return this;
  }

  /**
   * Additional information of order title
   * @return orderTitle
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ORDER_TITLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOrderTitle() {
    return orderTitle;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_TITLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrderTitle(@javax.annotation.Nonnull String orderTitle) {
    this.orderTitle = orderTitle;
  }

  public OrderRedirectObject merchantTransType(@javax.annotation.Nullable String merchantTransType) {
    
    this.merchantTransType = merchantTransType;
    return this;
  }

  /**
   * Additional information of merchant transaction type
   * @return merchantTransType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MERCHANT_TRANS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMerchantTransType() {
    return merchantTransType;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_TRANS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchantTransType(@javax.annotation.Nullable String merchantTransType) {
    this.merchantTransType = merchantTransType;
  }

  public OrderRedirectObject buyer(@javax.annotation.Nullable Buyer buyer) {
    
    this.buyer = buyer;
    return this;
  }

  /**
   * Additional information of buyer
   * @return buyer
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUYER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Buyer getBuyer() {
    return buyer;
  }


  @JsonProperty(JSON_PROPERTY_BUYER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuyer(@javax.annotation.Nullable Buyer buyer) {
    this.buyer = buyer;
  }

  public OrderRedirectObject goods(@javax.annotation.Nullable List<Goods> goods) {
    
    this.goods = goods;
    return this;
  }

  public OrderRedirectObject addGoodsItem(Goods goodsItem) {
    if (this.goods == null) {
      this.goods = new ArrayList<>();
    }
    this.goods.add(goodsItem);
    return this;
  }

  /**
   * Additional information of goods
   * @return goods
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GOODS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Goods> getGoods() {
    return goods;
  }


  @JsonProperty(JSON_PROPERTY_GOODS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGoods(@javax.annotation.Nullable List<Goods> goods) {
    this.goods = goods;
  }

  public OrderRedirectObject shippingInfo(@javax.annotation.Nullable List<ShippingInfo> shippingInfo) {
    
    this.shippingInfo = shippingInfo;
    return this;
  }

  public OrderRedirectObject addShippingInfoItem(ShippingInfo shippingInfoItem) {
    if (this.shippingInfo == null) {
      this.shippingInfo = new ArrayList<>();
    }
    this.shippingInfo.add(shippingInfoItem);
    return this;
  }

  /**
   * Additional information of shipping info
   * @return shippingInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHIPPING_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ShippingInfo> getShippingInfo() {
    return shippingInfo;
  }


  @JsonProperty(JSON_PROPERTY_SHIPPING_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShippingInfo(@javax.annotation.Nullable List<ShippingInfo> shippingInfo) {
    this.shippingInfo = shippingInfo;
  }

  public OrderRedirectObject extendInfo(@javax.annotation.Nullable String extendInfo) {
    
    this.extendInfo = extendInfo;
    return this;
  }

  /**
   * Additional information of extend
   * @return extendInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTEND_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExtendInfo() {
    return extendInfo;
  }


  @JsonProperty(JSON_PROPERTY_EXTEND_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtendInfo(@javax.annotation.Nullable String extendInfo) {
    this.extendInfo = extendInfo;
  }

  public OrderRedirectObject createdTime(@javax.annotation.Nullable String createdTime) {
    
    this.createdTime = createdTime;
    return this;
  }

  /**
   * Additional information of created time
   * @return createdTime
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedTime() {
    return createdTime;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedTime(@javax.annotation.Nullable String createdTime) {
    this.createdTime = createdTime;
  }

  public OrderRedirectObject orderMemo(@javax.annotation.Nullable String orderMemo) {
    
    this.orderMemo = orderMemo;
    return this;
  }

  /**
   * Additional information of order
   * @return orderMemo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER_MEMO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrderMemo() {
    return orderMemo;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_MEMO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderMemo(@javax.annotation.Nullable String orderMemo) {
    this.orderMemo = orderMemo;
  }

  public OrderRedirectObject scenario(@javax.annotation.Nullable ScenarioEnum scenario) {
    
    this.scenario = scenario;
    return this;
  }

  /**
   * For Payment Gateway Drop-in scenario, need to fill it as REDIRECT
   * @return scenario
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCENARIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ScenarioEnum getScenario() {
    return scenario;
  }


  @JsonProperty(JSON_PROPERTY_SCENARIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScenario(@javax.annotation.Nullable ScenarioEnum scenario) {
    this.scenario = scenario;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderRedirectObject orderRedirectObject = (OrderRedirectObject) o;
    return Objects.equals(this.orderTitle, orderRedirectObject.orderTitle) &&
        Objects.equals(this.merchantTransType, orderRedirectObject.merchantTransType) &&
        Objects.equals(this.buyer, orderRedirectObject.buyer) &&
        Objects.equals(this.goods, orderRedirectObject.goods) &&
        Objects.equals(this.shippingInfo, orderRedirectObject.shippingInfo) &&
        Objects.equals(this.extendInfo, orderRedirectObject.extendInfo) &&
        Objects.equals(this.createdTime, orderRedirectObject.createdTime) &&
        Objects.equals(this.orderMemo, orderRedirectObject.orderMemo) &&
        Objects.equals(this.scenario, orderRedirectObject.scenario);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderTitle, merchantTransType, buyer, goods, shippingInfo, extendInfo, createdTime, orderMemo, scenario);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderRedirectObject {\n");
    sb.append("    orderTitle: ").append(toIndentedString(orderTitle)).append("\n");
    sb.append("    merchantTransType: ").append(toIndentedString(merchantTransType)).append("\n");
    sb.append("    buyer: ").append(toIndentedString(buyer)).append("\n");
    sb.append("    goods: ").append(toIndentedString(goods)).append("\n");
    sb.append("    shippingInfo: ").append(toIndentedString(shippingInfo)).append("\n");
    sb.append("    extendInfo: ").append(toIndentedString(extendInfo)).append("\n");
    sb.append("    createdTime: ").append(toIndentedString(createdTime)).append("\n");
    sb.append("    orderMemo: ").append(toIndentedString(orderMemo)).append("\n");
    sb.append("    scenario: ").append(toIndentedString(scenario)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

