/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.disbursement.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Additional information
 */
@JsonPropertyOrder({
  BankAccountInquiryRequestAdditionalInfo.JSON_PROPERTY_FUND_TYPE,
  BankAccountInquiryRequestAdditionalInfo.JSON_PROPERTY_EXTERNAL_DIVISION_ID,
  BankAccountInquiryRequestAdditionalInfo.JSON_PROPERTY_CHARGE_TARGET,
  BankAccountInquiryRequestAdditionalInfo.JSON_PROPERTY_BENEFICIARY_BANK_CODE,
  BankAccountInquiryRequestAdditionalInfo.JSON_PROPERTY_BENEFICIARY_ACCOUNT_NAME,
  BankAccountInquiryRequestAdditionalInfo.JSON_PROPERTY_ACCOUNT_TYPE,
  BankAccountInquiryRequestAdditionalInfo.JSON_PROPERTY_ACCESS_TOKEN
})
@JsonTypeName("BankAccountInquiryRequest_additionalInfo")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class BankAccountInquiryRequestAdditionalInfo {
  public static final String JSON_PROPERTY_FUND_TYPE = "fundType";
  @javax.annotation.Nonnull
  private String fundType;

  public static final String JSON_PROPERTY_EXTERNAL_DIVISION_ID = "externalDivisionId";
  @javax.annotation.Nullable
  private String externalDivisionId;

  /**
   * Additional information of charge target. The values are:<br> • null<br> • DIVISION<br> • MERCHANT<br> Notes: If the value is DIVISION, externalDivisionId will be Mandatory 
   */
  public enum ChargeTargetEnum {
    DIVISION(String.valueOf("DIVISION")),
    
    MERCHANT(String.valueOf("MERCHANT")),
    
    /**
     * To handle empty string value
     */
    UNSPECIFIED(String.valueOf(""));

    private String value;

    ChargeTargetEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ChargeTargetEnum fromValue(String value) {
      for (ChargeTargetEnum b : ChargeTargetEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public static final String JSON_PROPERTY_CHARGE_TARGET = "chargeTarget";
  @javax.annotation.Nullable
  private ChargeTargetEnum chargeTarget;

  public static final String JSON_PROPERTY_BENEFICIARY_BANK_CODE = "beneficiaryBankCode";
  @javax.annotation.Nonnull
  private String beneficiaryBankCode;

  public static final String JSON_PROPERTY_BENEFICIARY_ACCOUNT_NAME = "beneficiaryAccountName";
  @javax.annotation.Nullable
  private String beneficiaryAccountName;

  public static final String JSON_PROPERTY_ACCOUNT_TYPE = "accountType";
  @javax.annotation.Nullable
  private String accountType;

  public static final String JSON_PROPERTY_ACCESS_TOKEN = "accessToken";
  @javax.annotation.Nullable
  private String accessToken;

  public BankAccountInquiryRequestAdditionalInfo() {
  }

  public BankAccountInquiryRequestAdditionalInfo fundType(@javax.annotation.Nonnull String fundType) {
    
    this.fundType = fundType;
    return this;
  }

  /**
   * Additional information of withdraw fund type, i.e.<br> MERCHANT_WITHDRAW_FOR_CORPORATE 
   * @return fundType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FUND_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFundType() {
    return fundType;
  }


  @JsonProperty(JSON_PROPERTY_FUND_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFundType(@javax.annotation.Nonnull String fundType) {
    this.fundType = fundType;
  }

  public BankAccountInquiryRequestAdditionalInfo externalDivisionId(@javax.annotation.Nullable String externalDivisionId) {
    
    this.externalDivisionId = externalDivisionId;
    return this;
  }

  /**
   * Additional information of external division identifier. (fundType: MERCHANT_WITHDRAW_FOR_CORPORATE)<br> Notes: The required of this parameter is Optional, but if \"additionalInfo.chargeTarget\" has value DIVISION then the required of this parameter will be changed to Mandatory 
   * @return externalDivisionId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTERNAL_DIVISION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExternalDivisionId() {
    return externalDivisionId;
  }


  @JsonProperty(JSON_PROPERTY_EXTERNAL_DIVISION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalDivisionId(@javax.annotation.Nullable String externalDivisionId) {
    this.externalDivisionId = externalDivisionId;
  }

  public BankAccountInquiryRequestAdditionalInfo chargeTarget(@javax.annotation.Nullable ChargeTargetEnum chargeTarget) {
    
    this.chargeTarget = chargeTarget;
    return this;
  }

  /**
   * Additional information of charge target. The values are:<br> • null<br> • DIVISION<br> • MERCHANT<br> Notes: If the value is DIVISION, externalDivisionId will be Mandatory 
   * @return chargeTarget
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHARGE_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ChargeTargetEnum getChargeTarget() {
    return chargeTarget;
  }


  @JsonProperty(JSON_PROPERTY_CHARGE_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChargeTarget(@javax.annotation.Nullable ChargeTargetEnum chargeTarget) {
    this.chargeTarget = chargeTarget;
  }

  public BankAccountInquiryRequestAdditionalInfo beneficiaryBankCode(@javax.annotation.Nonnull String beneficiaryBankCode) {
    
    this.beneficiaryBankCode = beneficiaryBankCode;
    return this;
  }

  /**
   * Additional information of beneficiary Bank code
   * @return beneficiaryBankCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BENEFICIARY_BANK_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBeneficiaryBankCode() {
    return beneficiaryBankCode;
  }


  @JsonProperty(JSON_PROPERTY_BENEFICIARY_BANK_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBeneficiaryBankCode(@javax.annotation.Nonnull String beneficiaryBankCode) {
    this.beneficiaryBankCode = beneficiaryBankCode;
  }

  public BankAccountInquiryRequestAdditionalInfo beneficiaryAccountName(@javax.annotation.Nullable String beneficiaryAccountName) {
    
    this.beneficiaryAccountName = beneficiaryAccountName;
    return this;
  }

  /**
   * Additional information of beneficiary account name for validation purpose
   * @return beneficiaryAccountName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BENEFICIARY_ACCOUNT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBeneficiaryAccountName() {
    return beneficiaryAccountName;
  }


  @JsonProperty(JSON_PROPERTY_BENEFICIARY_ACCOUNT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBeneficiaryAccountName(@javax.annotation.Nullable String beneficiaryAccountName) {
    this.beneficiaryAccountName = beneficiaryAccountName;
  }

  public BankAccountInquiryRequestAdditionalInfo accountType(@javax.annotation.Nullable String accountType) {
    
    this.accountType = accountType;
    return this;
  }

  /**
   * Additional information of account type
   * @return accountType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccountType() {
    return accountType;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountType(@javax.annotation.Nullable String accountType) {
    this.accountType = accountType;
  }

  public BankAccountInquiryRequestAdditionalInfo accessToken(@javax.annotation.Nullable String accessToken) {
    
    this.accessToken = accessToken;
    return this;
  }

  /**
   * Contains customer token, which has been obtained from binding process, refer to Account Binding & Unbinding documentation<br> If request is coming from user interaction, this field is mandatory. If not, just filled customerNumber 
   * @return accessToken
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCESS_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccessToken() {
    return accessToken;
  }


  @JsonProperty(JSON_PROPERTY_ACCESS_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccessToken(@javax.annotation.Nullable String accessToken) {
    this.accessToken = accessToken;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankAccountInquiryRequestAdditionalInfo bankAccountInquiryRequestAdditionalInfo = (BankAccountInquiryRequestAdditionalInfo) o;
    return Objects.equals(this.fundType, bankAccountInquiryRequestAdditionalInfo.fundType) &&
        Objects.equals(this.externalDivisionId, bankAccountInquiryRequestAdditionalInfo.externalDivisionId) &&
        Objects.equals(this.chargeTarget, bankAccountInquiryRequestAdditionalInfo.chargeTarget) &&
        Objects.equals(this.beneficiaryBankCode, bankAccountInquiryRequestAdditionalInfo.beneficiaryBankCode) &&
        Objects.equals(this.beneficiaryAccountName, bankAccountInquiryRequestAdditionalInfo.beneficiaryAccountName) &&
        Objects.equals(this.accountType, bankAccountInquiryRequestAdditionalInfo.accountType) &&
        Objects.equals(this.accessToken, bankAccountInquiryRequestAdditionalInfo.accessToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fundType, externalDivisionId, chargeTarget, beneficiaryBankCode, beneficiaryAccountName, accountType, accessToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankAccountInquiryRequestAdditionalInfo {\n");
    sb.append("    fundType: ").append(toIndentedString(fundType)).append("\n");
    sb.append("    externalDivisionId: ").append(toIndentedString(externalDivisionId)).append("\n");
    sb.append("    chargeTarget: ").append(toIndentedString(chargeTarget)).append("\n");
    sb.append("    beneficiaryBankCode: ").append(toIndentedString(beneficiaryBankCode)).append("\n");
    sb.append("    beneficiaryAccountName: ").append(toIndentedString(beneficiaryAccountName)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    accessToken: ").append(toIndentedString(accessToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
