/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.disbursement.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.dana.disbursement.v1.model.BankAccountInquiryResponseAdditionalInfo;
import id.dana.disbursement.v1.model.Money;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BankAccountInquiryResponse
 */
@JsonPropertyOrder({
  BankAccountInquiryResponse.JSON_PROPERTY_RESPONSE_CODE,
  BankAccountInquiryResponse.JSON_PROPERTY_RESPONSE_MESSAGE,
  BankAccountInquiryResponse.JSON_PROPERTY_REFERENCE_NO,
  BankAccountInquiryResponse.JSON_PROPERTY_PARTNER_REFERENCE_NO,
  BankAccountInquiryResponse.JSON_PROPERTY_ACCOUNT_TYPE,
  BankAccountInquiryResponse.JSON_PROPERTY_BENEFICIARY_ACCOUNT_NUMBER,
  BankAccountInquiryResponse.JSON_PROPERTY_BENEFICIARY_ACCOUNT_NAME,
  BankAccountInquiryResponse.JSON_PROPERTY_BENEFICIARY_BANK_CODE,
  BankAccountInquiryResponse.JSON_PROPERTY_BENEFICIARY_BANK_SHORT_NAME,
  BankAccountInquiryResponse.JSON_PROPERTY_BENEFICIARY_BANK_NAME,
  BankAccountInquiryResponse.JSON_PROPERTY_AMOUNT,
  BankAccountInquiryResponse.JSON_PROPERTY_ADDITIONAL_INFO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class BankAccountInquiryResponse {
  public static final String JSON_PROPERTY_RESPONSE_CODE = "responseCode";
  @javax.annotation.Nonnull
  private String responseCode;

  public static final String JSON_PROPERTY_RESPONSE_MESSAGE = "responseMessage";
  @javax.annotation.Nonnull
  private String responseMessage;

  public static final String JSON_PROPERTY_REFERENCE_NO = "referenceNo";
  @javax.annotation.Nullable
  private String referenceNo;

  public static final String JSON_PROPERTY_PARTNER_REFERENCE_NO = "partnerReferenceNo";
  @javax.annotation.Nullable
  private String partnerReferenceNo;

  public static final String JSON_PROPERTY_ACCOUNT_TYPE = "accountType";
  @javax.annotation.Nullable
  private String accountType;

  public static final String JSON_PROPERTY_BENEFICIARY_ACCOUNT_NUMBER = "beneficiaryAccountNumber";
  @javax.annotation.Nonnull
  private String beneficiaryAccountNumber;

  public static final String JSON_PROPERTY_BENEFICIARY_ACCOUNT_NAME = "beneficiaryAccountName";
  @javax.annotation.Nonnull
  private String beneficiaryAccountName;

  public static final String JSON_PROPERTY_BENEFICIARY_BANK_CODE = "beneficiaryBankCode";
  @javax.annotation.Nullable
  private String beneficiaryBankCode;

  public static final String JSON_PROPERTY_BENEFICIARY_BANK_SHORT_NAME = "beneficiaryBankShortName";
  @javax.annotation.Nullable
  private String beneficiaryBankShortName;

  public static final String JSON_PROPERTY_BENEFICIARY_BANK_NAME = "beneficiaryBankName";
  @javax.annotation.Nullable
  private String beneficiaryBankName;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @javax.annotation.Nonnull
  private Money amount;

  public static final String JSON_PROPERTY_ADDITIONAL_INFO = "additionalInfo";
  @javax.annotation.Nullable
  private BankAccountInquiryResponseAdditionalInfo additionalInfo;

  public BankAccountInquiryResponse() {
  }

  public BankAccountInquiryResponse responseCode(@javax.annotation.Nonnull String responseCode) {
    
    this.responseCode = responseCode;
    return this;
  }

  /**
   * Refer to response code list
   * @return responseCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESPONSE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getResponseCode() {
    return responseCode;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResponseCode(@javax.annotation.Nonnull String responseCode) {
    this.responseCode = responseCode;
  }

  public BankAccountInquiryResponse responseMessage(@javax.annotation.Nonnull String responseMessage) {
    
    this.responseMessage = responseMessage;
    return this;
  }

  /**
   * Refer to response code list
   * @return responseMessage
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESPONSE_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getResponseMessage() {
    return responseMessage;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResponseMessage(@javax.annotation.Nonnull String responseMessage) {
    this.responseMessage = responseMessage;
  }

  public BankAccountInquiryResponse referenceNo(@javax.annotation.Nullable String referenceNo) {
    
    this.referenceNo = referenceNo;
    return this;
  }

  /**
   * Transaction identifier on DANA system
   * @return referenceNo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReferenceNo() {
    return referenceNo;
  }


  @JsonProperty(JSON_PROPERTY_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReferenceNo(@javax.annotation.Nullable String referenceNo) {
    this.referenceNo = referenceNo;
  }

  public BankAccountInquiryResponse partnerReferenceNo(@javax.annotation.Nullable String partnerReferenceNo) {
    
    this.partnerReferenceNo = partnerReferenceNo;
    return this;
  }

  /**
   * Unique transaction identifier on partner system which assigned to each transaction<br> Notes:<br> If the partner receives a timeout or an unexpected response from DANA and partner expects to perform retry request to DANA, please use the partnerReferenceNo that is the same as the one used in the transaction request process before 
   * @return partnerReferenceNo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARTNER_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPartnerReferenceNo() {
    return partnerReferenceNo;
  }


  @JsonProperty(JSON_PROPERTY_PARTNER_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPartnerReferenceNo(@javax.annotation.Nullable String partnerReferenceNo) {
    this.partnerReferenceNo = partnerReferenceNo;
  }

  public BankAccountInquiryResponse accountType(@javax.annotation.Nullable String accountType) {
    
    this.accountType = accountType;
    return this;
  }

  /**
   * Customer account type
   * @return accountType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccountType() {
    return accountType;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountType(@javax.annotation.Nullable String accountType) {
    this.accountType = accountType;
  }

  public BankAccountInquiryResponse beneficiaryAccountNumber(@javax.annotation.Nonnull String beneficiaryAccountNumber) {
    
    this.beneficiaryAccountNumber = beneficiaryAccountNumber;
    return this;
  }

  /**
   * Beneficiary account number
   * @return beneficiaryAccountNumber
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BENEFICIARY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBeneficiaryAccountNumber() {
    return beneficiaryAccountNumber;
  }


  @JsonProperty(JSON_PROPERTY_BENEFICIARY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBeneficiaryAccountNumber(@javax.annotation.Nonnull String beneficiaryAccountNumber) {
    this.beneficiaryAccountNumber = beneficiaryAccountNumber;
  }

  public BankAccountInquiryResponse beneficiaryAccountName(@javax.annotation.Nonnull String beneficiaryAccountName) {
    
    this.beneficiaryAccountName = beneficiaryAccountName;
    return this;
  }

  /**
   * Beneficiary account name
   * @return beneficiaryAccountName
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BENEFICIARY_ACCOUNT_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBeneficiaryAccountName() {
    return beneficiaryAccountName;
  }


  @JsonProperty(JSON_PROPERTY_BENEFICIARY_ACCOUNT_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBeneficiaryAccountName(@javax.annotation.Nonnull String beneficiaryAccountName) {
    this.beneficiaryAccountName = beneficiaryAccountName;
  }

  public BankAccountInquiryResponse beneficiaryBankCode(@javax.annotation.Nullable String beneficiaryBankCode) {
    
    this.beneficiaryBankCode = beneficiaryBankCode;
    return this;
  }

  /**
   * Beneficiary Bank code
   * @return beneficiaryBankCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BENEFICIARY_BANK_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBeneficiaryBankCode() {
    return beneficiaryBankCode;
  }


  @JsonProperty(JSON_PROPERTY_BENEFICIARY_BANK_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBeneficiaryBankCode(@javax.annotation.Nullable String beneficiaryBankCode) {
    this.beneficiaryBankCode = beneficiaryBankCode;
  }

  public BankAccountInquiryResponse beneficiaryBankShortName(@javax.annotation.Nullable String beneficiaryBankShortName) {
    
    this.beneficiaryBankShortName = beneficiaryBankShortName;
    return this;
  }

  /**
   * Beneficiary Bank short name
   * @return beneficiaryBankShortName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BENEFICIARY_BANK_SHORT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBeneficiaryBankShortName() {
    return beneficiaryBankShortName;
  }


  @JsonProperty(JSON_PROPERTY_BENEFICIARY_BANK_SHORT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBeneficiaryBankShortName(@javax.annotation.Nullable String beneficiaryBankShortName) {
    this.beneficiaryBankShortName = beneficiaryBankShortName;
  }

  public BankAccountInquiryResponse beneficiaryBankName(@javax.annotation.Nullable String beneficiaryBankName) {
    
    this.beneficiaryBankName = beneficiaryBankName;
    return this;
  }

  /**
   * Beneficiary Bank name
   * @return beneficiaryBankName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BENEFICIARY_BANK_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBeneficiaryBankName() {
    return beneficiaryBankName;
  }


  @JsonProperty(JSON_PROPERTY_BENEFICIARY_BANK_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBeneficiaryBankName(@javax.annotation.Nullable String beneficiaryBankName) {
    this.beneficiaryBankName = beneficiaryBankName;
  }

  public BankAccountInquiryResponse amount(@javax.annotation.Nonnull Money amount) {
    
    this.amount = amount;
    return this;
  }

  /**
   * Amount. Contains two sub-fields:<br> 1. Value: Transaction amount, including the cents<br> 2. Currency: Currency code based on ISO 
   * @return amount
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Money getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@javax.annotation.Nonnull Money amount) {
    this.amount = amount;
  }

  public BankAccountInquiryResponse additionalInfo(@javax.annotation.Nullable BankAccountInquiryResponseAdditionalInfo additionalInfo) {
    
    this.additionalInfo = additionalInfo;
    return this;
  }

  /**
   * Get additionalInfo
   * @return additionalInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BankAccountInquiryResponseAdditionalInfo getAdditionalInfo() {
    return additionalInfo;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalInfo(@javax.annotation.Nullable BankAccountInquiryResponseAdditionalInfo additionalInfo) {
    this.additionalInfo = additionalInfo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankAccountInquiryResponse bankAccountInquiryResponse = (BankAccountInquiryResponse) o;
    return Objects.equals(this.responseCode, bankAccountInquiryResponse.responseCode) &&
        Objects.equals(this.responseMessage, bankAccountInquiryResponse.responseMessage) &&
        Objects.equals(this.referenceNo, bankAccountInquiryResponse.referenceNo) &&
        Objects.equals(this.partnerReferenceNo, bankAccountInquiryResponse.partnerReferenceNo) &&
        Objects.equals(this.accountType, bankAccountInquiryResponse.accountType) &&
        Objects.equals(this.beneficiaryAccountNumber, bankAccountInquiryResponse.beneficiaryAccountNumber) &&
        Objects.equals(this.beneficiaryAccountName, bankAccountInquiryResponse.beneficiaryAccountName) &&
        Objects.equals(this.beneficiaryBankCode, bankAccountInquiryResponse.beneficiaryBankCode) &&
        Objects.equals(this.beneficiaryBankShortName, bankAccountInquiryResponse.beneficiaryBankShortName) &&
        Objects.equals(this.beneficiaryBankName, bankAccountInquiryResponse.beneficiaryBankName) &&
        Objects.equals(this.amount, bankAccountInquiryResponse.amount) &&
        Objects.equals(this.additionalInfo, bankAccountInquiryResponse.additionalInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseCode, responseMessage, referenceNo, partnerReferenceNo, accountType, beneficiaryAccountNumber, beneficiaryAccountName, beneficiaryBankCode, beneficiaryBankShortName, beneficiaryBankName, amount, additionalInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankAccountInquiryResponse {\n");
    sb.append("    responseCode: ").append(toIndentedString(responseCode)).append("\n");
    sb.append("    responseMessage: ").append(toIndentedString(responseMessage)).append("\n");
    sb.append("    referenceNo: ").append(toIndentedString(referenceNo)).append("\n");
    sb.append("    partnerReferenceNo: ").append(toIndentedString(partnerReferenceNo)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    beneficiaryAccountNumber: ").append(toIndentedString(beneficiaryAccountNumber)).append("\n");
    sb.append("    beneficiaryAccountName: ").append(toIndentedString(beneficiaryAccountName)).append("\n");
    sb.append("    beneficiaryBankCode: ").append(toIndentedString(beneficiaryBankCode)).append("\n");
    sb.append("    beneficiaryBankShortName: ").append(toIndentedString(beneficiaryBankShortName)).append("\n");
    sb.append("    beneficiaryBankName: ").append(toIndentedString(beneficiaryBankName)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    additionalInfo: ").append(toIndentedString(additionalInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
