/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.disbursement.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.dana.disbursement.v1.model.Money;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Additional information
 */
@JsonPropertyOrder({
  BankAccountInquiryResponseAdditionalInfo.JSON_PROPERTY_FEE_AMOUNT
})
@JsonTypeName("BankAccountInquiryResponse_additionalInfo")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class BankAccountInquiryResponseAdditionalInfo {
  public static final String JSON_PROPERTY_FEE_AMOUNT = "feeAmount";
  @javax.annotation.Nonnull
  private Money feeAmount;

  public BankAccountInquiryResponseAdditionalInfo() {
  }

  public BankAccountInquiryResponseAdditionalInfo feeAmount(@javax.annotation.Nonnull Money feeAmount) {
    
    this.feeAmount = feeAmount;
    return this;
  }

  /**
   * Additional information of fee amount. Contains two sub-fields:<br> 1. Value: Amount, including the cents<br> 2. Currency: Currency code based on ISO 
   * @return feeAmount
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FEE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Money getFeeAmount() {
    return feeAmount;
  }


  @JsonProperty(JSON_PROPERTY_FEE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFeeAmount(@javax.annotation.Nonnull Money feeAmount) {
    this.feeAmount = feeAmount;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankAccountInquiryResponseAdditionalInfo bankAccountInquiryResponseAdditionalInfo = (BankAccountInquiryResponseAdditionalInfo) o;
    return Objects.equals(this.feeAmount, bankAccountInquiryResponseAdditionalInfo.feeAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(feeAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankAccountInquiryResponseAdditionalInfo {\n");
    sb.append("    feeAmount: ").append(toIndentedString(feeAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
