/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.disbursement.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.dana.disbursement.v1.model.Money;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * DanaAccountInquiryResponse
 */
@JsonPropertyOrder({
  DanaAccountInquiryResponse.JSON_PROPERTY_RESPONSE_CODE,
  DanaAccountInquiryResponse.JSON_PROPERTY_RESPONSE_MESSAGE,
  DanaAccountInquiryResponse.JSON_PROPERTY_REFERENCE_NO,
  DanaAccountInquiryResponse.JSON_PROPERTY_PARTNER_REFERENCE_NO,
  DanaAccountInquiryResponse.JSON_PROPERTY_SESSION_ID,
  DanaAccountInquiryResponse.JSON_PROPERTY_CUSTOMER_NUMBER,
  DanaAccountInquiryResponse.JSON_PROPERTY_CUSTOMER_NAME,
  DanaAccountInquiryResponse.JSON_PROPERTY_CUSTOMER_MONTHLY_IN_LIMIT,
  DanaAccountInquiryResponse.JSON_PROPERTY_MIN_AMOUNT,
  DanaAccountInquiryResponse.JSON_PROPERTY_MAX_AMOUNT,
  DanaAccountInquiryResponse.JSON_PROPERTY_AMOUNT,
  DanaAccountInquiryResponse.JSON_PROPERTY_FEE_AMOUNT,
  DanaAccountInquiryResponse.JSON_PROPERTY_FEE_TYPE,
  DanaAccountInquiryResponse.JSON_PROPERTY_ADDITIONAL_INFO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class DanaAccountInquiryResponse {
  public static final String JSON_PROPERTY_RESPONSE_CODE = "responseCode";
  @javax.annotation.Nonnull
  private String responseCode;

  public static final String JSON_PROPERTY_RESPONSE_MESSAGE = "responseMessage";
  @javax.annotation.Nonnull
  private String responseMessage;

  public static final String JSON_PROPERTY_REFERENCE_NO = "referenceNo";
  @javax.annotation.Nullable
  private String referenceNo;

  public static final String JSON_PROPERTY_PARTNER_REFERENCE_NO = "partnerReferenceNo";
  @javax.annotation.Nullable
  private String partnerReferenceNo;

  public static final String JSON_PROPERTY_SESSION_ID = "sessionId";
  @javax.annotation.Nullable
  private String sessionId;

  public static final String JSON_PROPERTY_CUSTOMER_NUMBER = "customerNumber";
  @javax.annotation.Nullable
  private String customerNumber;

  public static final String JSON_PROPERTY_CUSTOMER_NAME = "customerName";
  @javax.annotation.Nonnull
  private String customerName;

  public static final String JSON_PROPERTY_CUSTOMER_MONTHLY_IN_LIMIT = "customerMonthlyInLimit";
  @javax.annotation.Nullable
  private String customerMonthlyInLimit;

  public static final String JSON_PROPERTY_MIN_AMOUNT = "minAmount";
  @javax.annotation.Nonnull
  private Money minAmount;

  public static final String JSON_PROPERTY_MAX_AMOUNT = "maxAmount";
  @javax.annotation.Nonnull
  private Money maxAmount;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @javax.annotation.Nonnull
  private Money amount;

  public static final String JSON_PROPERTY_FEE_AMOUNT = "feeAmount";
  @javax.annotation.Nonnull
  private Money feeAmount;

  public static final String JSON_PROPERTY_FEE_TYPE = "feeType";
  @javax.annotation.Nullable
  private String feeType;

  public static final String JSON_PROPERTY_ADDITIONAL_INFO = "additionalInfo";
  @javax.annotation.Nullable
  private Object additionalInfo;

  public DanaAccountInquiryResponse() {
  }

  public DanaAccountInquiryResponse responseCode(@javax.annotation.Nonnull String responseCode) {
    
    this.responseCode = responseCode;
    return this;
  }

  /**
   * Refer to response code list
   * @return responseCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESPONSE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getResponseCode() {
    return responseCode;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResponseCode(@javax.annotation.Nonnull String responseCode) {
    this.responseCode = responseCode;
  }

  public DanaAccountInquiryResponse responseMessage(@javax.annotation.Nonnull String responseMessage) {
    
    this.responseMessage = responseMessage;
    return this;
  }

  /**
   * Refer to response code list
   * @return responseMessage
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESPONSE_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getResponseMessage() {
    return responseMessage;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResponseMessage(@javax.annotation.Nonnull String responseMessage) {
    this.responseMessage = responseMessage;
  }

  public DanaAccountInquiryResponse referenceNo(@javax.annotation.Nullable String referenceNo) {
    
    this.referenceNo = referenceNo;
    return this;
  }

  /**
   * Transaction identifier on DANA system
   * @return referenceNo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReferenceNo() {
    return referenceNo;
  }


  @JsonProperty(JSON_PROPERTY_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReferenceNo(@javax.annotation.Nullable String referenceNo) {
    this.referenceNo = referenceNo;
  }

  public DanaAccountInquiryResponse partnerReferenceNo(@javax.annotation.Nullable String partnerReferenceNo) {
    
    this.partnerReferenceNo = partnerReferenceNo;
    return this;
  }

  /**
   * Unique transaction identifier on partner system which assigned to each transaction<br> Notes:<br> If the partner receives a timeout or an unexpected response from DANA and partner expects to perform retry request to DANA, please use the partnerReferenceNo that is the same as the one used in the transaction request process before 
   * @return partnerReferenceNo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARTNER_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPartnerReferenceNo() {
    return partnerReferenceNo;
  }


  @JsonProperty(JSON_PROPERTY_PARTNER_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPartnerReferenceNo(@javax.annotation.Nullable String partnerReferenceNo) {
    this.partnerReferenceNo = partnerReferenceNo;
  }

  public DanaAccountInquiryResponse sessionId(@javax.annotation.Nullable String sessionId) {
    
    this.sessionId = sessionId;
    return this;
  }

  /**
   * Session identifier
   * @return sessionId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SESSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSessionId() {
    return sessionId;
  }


  @JsonProperty(JSON_PROPERTY_SESSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSessionId(@javax.annotation.Nullable String sessionId) {
    this.sessionId = sessionId;
  }

  public DanaAccountInquiryResponse customerNumber(@javax.annotation.Nullable String customerNumber) {
    
    this.customerNumber = customerNumber;
    return this;
  }

  /**
   * Customer account number, in format 628xxx
   * @return customerNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOMER_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCustomerNumber() {
    return customerNumber;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOMER_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomerNumber(@javax.annotation.Nullable String customerNumber) {
    this.customerNumber = customerNumber;
  }

  public DanaAccountInquiryResponse customerName(@javax.annotation.Nonnull String customerName) {
    
    this.customerName = customerName;
    return this;
  }

  /**
   * Customer account name
   * @return customerName
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CUSTOMER_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCustomerName() {
    return customerName;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOMER_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCustomerName(@javax.annotation.Nonnull String customerName) {
    this.customerName = customerName;
  }

  public DanaAccountInquiryResponse customerMonthlyInLimit(@javax.annotation.Nullable String customerMonthlyInLimit) {
    
    this.customerMonthlyInLimit = customerMonthlyInLimit;
    return this;
  }

  /**
   * Limitation of transfer to DANA balance for customer per month
   * @return customerMonthlyInLimit
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOMER_MONTHLY_IN_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCustomerMonthlyInLimit() {
    return customerMonthlyInLimit;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOMER_MONTHLY_IN_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomerMonthlyInLimit(@javax.annotation.Nullable String customerMonthlyInLimit) {
    this.customerMonthlyInLimit = customerMonthlyInLimit;
  }

  public DanaAccountInquiryResponse minAmount(@javax.annotation.Nonnull Money minAmount) {
    
    this.minAmount = minAmount;
    return this;
  }

  /**
   * Minimal amount. Contains two sub-fields:<br> 1. Value: Amount, including the cents<br> 2. Currency: Currency code based on ISO 
   * @return minAmount
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MIN_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Money getMinAmount() {
    return minAmount;
  }


  @JsonProperty(JSON_PROPERTY_MIN_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMinAmount(@javax.annotation.Nonnull Money minAmount) {
    this.minAmount = minAmount;
  }

  public DanaAccountInquiryResponse maxAmount(@javax.annotation.Nonnull Money maxAmount) {
    
    this.maxAmount = maxAmount;
    return this;
  }

  /**
   * Maximal amount. Contains two sub-fields:<br> 1. Value: Amount, including the cents<br> 2. Currency: Currency code based on ISO 
   * @return maxAmount
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MAX_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Money getMaxAmount() {
    return maxAmount;
  }


  @JsonProperty(JSON_PROPERTY_MAX_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMaxAmount(@javax.annotation.Nonnull Money maxAmount) {
    this.maxAmount = maxAmount;
  }

  public DanaAccountInquiryResponse amount(@javax.annotation.Nonnull Money amount) {
    
    this.amount = amount;
    return this;
  }

  /**
   * Amount. Contains two sub-fields:<br> 1. Value: Transaction amount, including the cents<br> 2. Currency: Currency code based on ISO 
   * @return amount
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Money getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@javax.annotation.Nonnull Money amount) {
    this.amount = amount;
  }

  public DanaAccountInquiryResponse feeAmount(@javax.annotation.Nonnull Money feeAmount) {
    
    this.feeAmount = feeAmount;
    return this;
  }

  /**
   * Fee amount. Contains two sub-fields:<br> 1. Value: Amount, including the cents<br> 2. Currency: Currency code based on ISO 
   * @return feeAmount
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FEE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Money getFeeAmount() {
    return feeAmount;
  }


  @JsonProperty(JSON_PROPERTY_FEE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFeeAmount(@javax.annotation.Nonnull Money feeAmount) {
    this.feeAmount = feeAmount;
  }

  public DanaAccountInquiryResponse feeType(@javax.annotation.Nullable String feeType) {
    
    this.feeType = feeType;
    return this;
  }

  /**
   * Type of fee for each transfer to DANA transaction. Such as admin fee
   * @return feeType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FEE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFeeType() {
    return feeType;
  }


  @JsonProperty(JSON_PROPERTY_FEE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFeeType(@javax.annotation.Nullable String feeType) {
    this.feeType = feeType;
  }

  public DanaAccountInquiryResponse additionalInfo(@javax.annotation.Nullable Object additionalInfo) {
    
    this.additionalInfo = additionalInfo;
    return this;
  }

  /**
   * Additional information
   * @return additionalInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getAdditionalInfo() {
    return additionalInfo;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalInfo(@javax.annotation.Nullable Object additionalInfo) {
    this.additionalInfo = additionalInfo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DanaAccountInquiryResponse danaAccountInquiryResponse = (DanaAccountInquiryResponse) o;
    return Objects.equals(this.responseCode, danaAccountInquiryResponse.responseCode) &&
        Objects.equals(this.responseMessage, danaAccountInquiryResponse.responseMessage) &&
        Objects.equals(this.referenceNo, danaAccountInquiryResponse.referenceNo) &&
        Objects.equals(this.partnerReferenceNo, danaAccountInquiryResponse.partnerReferenceNo) &&
        Objects.equals(this.sessionId, danaAccountInquiryResponse.sessionId) &&
        Objects.equals(this.customerNumber, danaAccountInquiryResponse.customerNumber) &&
        Objects.equals(this.customerName, danaAccountInquiryResponse.customerName) &&
        Objects.equals(this.customerMonthlyInLimit, danaAccountInquiryResponse.customerMonthlyInLimit) &&
        Objects.equals(this.minAmount, danaAccountInquiryResponse.minAmount) &&
        Objects.equals(this.maxAmount, danaAccountInquiryResponse.maxAmount) &&
        Objects.equals(this.amount, danaAccountInquiryResponse.amount) &&
        Objects.equals(this.feeAmount, danaAccountInquiryResponse.feeAmount) &&
        Objects.equals(this.feeType, danaAccountInquiryResponse.feeType) &&
        Objects.equals(this.additionalInfo, danaAccountInquiryResponse.additionalInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseCode, responseMessage, referenceNo, partnerReferenceNo, sessionId, customerNumber, customerName, customerMonthlyInLimit, minAmount, maxAmount, amount, feeAmount, feeType, additionalInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DanaAccountInquiryResponse {\n");
    sb.append("    responseCode: ").append(toIndentedString(responseCode)).append("\n");
    sb.append("    responseMessage: ").append(toIndentedString(responseMessage)).append("\n");
    sb.append("    referenceNo: ").append(toIndentedString(referenceNo)).append("\n");
    sb.append("    partnerReferenceNo: ").append(toIndentedString(partnerReferenceNo)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    customerNumber: ").append(toIndentedString(customerNumber)).append("\n");
    sb.append("    customerName: ").append(toIndentedString(customerName)).append("\n");
    sb.append("    customerMonthlyInLimit: ").append(toIndentedString(customerMonthlyInLimit)).append("\n");
    sb.append("    minAmount: ").append(toIndentedString(minAmount)).append("\n");
    sb.append("    maxAmount: ").append(toIndentedString(maxAmount)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    feeAmount: ").append(toIndentedString(feeAmount)).append("\n");
    sb.append("    feeType: ").append(toIndentedString(feeType)).append("\n");
    sb.append("    additionalInfo: ").append(toIndentedString(additionalInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
