/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */


package id.dana.disbursement.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.dana.disbursement.v1.model.Money;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TransferToDanaResponse
 */
@JsonPropertyOrder({
  TransferToDanaResponse.JSON_PROPERTY_RESPONSE_CODE,
  TransferToDanaResponse.JSON_PROPERTY_RESPONSE_MESSAGE,
  TransferToDanaResponse.JSON_PROPERTY_REFERENCE_NO,
  TransferToDanaResponse.JSON_PROPERTY_PARTNER_REFERENCE_NO,
  TransferToDanaResponse.JSON_PROPERTY_SESSION_ID,
  TransferToDanaResponse.JSON_PROPERTY_CUSTOMER_NUMBER,
  TransferToDanaResponse.JSON_PROPERTY_CUSTOMER_NAME,
  TransferToDanaResponse.JSON_PROPERTY_AMOUNT,
  TransferToDanaResponse.JSON_PROPERTY_ADDITIONAL_INFO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class TransferToDanaResponse {
  public static final String JSON_PROPERTY_RESPONSE_CODE = "responseCode";
  @javax.annotation.Nonnull
  private String responseCode;

  public static final String JSON_PROPERTY_RESPONSE_MESSAGE = "responseMessage";
  @javax.annotation.Nonnull
  private String responseMessage;

  public static final String JSON_PROPERTY_REFERENCE_NO = "referenceNo";
  @javax.annotation.Nullable
  private String referenceNo;

  public static final String JSON_PROPERTY_PARTNER_REFERENCE_NO = "partnerReferenceNo";
  @javax.annotation.Nonnull
  private String partnerReferenceNo;

  public static final String JSON_PROPERTY_SESSION_ID = "sessionId";
  @javax.annotation.Nullable
  private String sessionId;

  public static final String JSON_PROPERTY_CUSTOMER_NUMBER = "customerNumber";
  @javax.annotation.Nullable
  private String customerNumber;

  public static final String JSON_PROPERTY_CUSTOMER_NAME = "customerName";
  @javax.annotation.Nullable
  private String customerName;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @javax.annotation.Nonnull
  private Money amount;

  public static final String JSON_PROPERTY_ADDITIONAL_INFO = "additionalInfo";
  @javax.annotation.Nullable
  private Object additionalInfo;

  public TransferToDanaResponse() {
  }

  public TransferToDanaResponse responseCode(@javax.annotation.Nonnull String responseCode) {
    
    this.responseCode = responseCode;
    return this;
  }

  /**
   * Refer to response code list
   * @return responseCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESPONSE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getResponseCode() {
    return responseCode;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResponseCode(@javax.annotation.Nonnull String responseCode) {
    this.responseCode = responseCode;
  }

  public TransferToDanaResponse responseMessage(@javax.annotation.Nonnull String responseMessage) {
    
    this.responseMessage = responseMessage;
    return this;
  }

  /**
   * Refer to response code list
   * @return responseMessage
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESPONSE_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getResponseMessage() {
    return responseMessage;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResponseMessage(@javax.annotation.Nonnull String responseMessage) {
    this.responseMessage = responseMessage;
  }

  public TransferToDanaResponse referenceNo(@javax.annotation.Nullable String referenceNo) {
    
    this.referenceNo = referenceNo;
    return this;
  }

  /**
   * Transaction identifier on DANA system
   * @return referenceNo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReferenceNo() {
    return referenceNo;
  }


  @JsonProperty(JSON_PROPERTY_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReferenceNo(@javax.annotation.Nullable String referenceNo) {
    this.referenceNo = referenceNo;
  }

  public TransferToDanaResponse partnerReferenceNo(@javax.annotation.Nonnull String partnerReferenceNo) {
    
    this.partnerReferenceNo = partnerReferenceNo;
    return this;
  }

  /**
   * Unique transaction identifier on partner system which assigned to each transaction<br> Notes:<br> If the partner receives a timeout or an unexpected response from DANA and partner expects to perform retry request to DANA, please use the partnerReferenceNo that is the same as the one used in the transaction request process before 
   * @return partnerReferenceNo
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PARTNER_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPartnerReferenceNo() {
    return partnerReferenceNo;
  }


  @JsonProperty(JSON_PROPERTY_PARTNER_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPartnerReferenceNo(@javax.annotation.Nonnull String partnerReferenceNo) {
    this.partnerReferenceNo = partnerReferenceNo;
  }

  public TransferToDanaResponse sessionId(@javax.annotation.Nullable String sessionId) {
    
    this.sessionId = sessionId;
    return this;
  }

  /**
   * Session identifier
   * @return sessionId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SESSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSessionId() {
    return sessionId;
  }


  @JsonProperty(JSON_PROPERTY_SESSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSessionId(@javax.annotation.Nullable String sessionId) {
    this.sessionId = sessionId;
  }

  public TransferToDanaResponse customerNumber(@javax.annotation.Nullable String customerNumber) {
    
    this.customerNumber = customerNumber;
    return this;
  }

  /**
   * Customer account number, in format 628xxx
   * @return customerNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOMER_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCustomerNumber() {
    return customerNumber;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOMER_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomerNumber(@javax.annotation.Nullable String customerNumber) {
    this.customerNumber = customerNumber;
  }

  public TransferToDanaResponse customerName(@javax.annotation.Nullable String customerName) {
    
    this.customerName = customerName;
    return this;
  }

  /**
   * Customer account name
   * @return customerName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOMER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCustomerName() {
    return customerName;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOMER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomerName(@javax.annotation.Nullable String customerName) {
    this.customerName = customerName;
  }

  public TransferToDanaResponse amount(@javax.annotation.Nonnull Money amount) {
    
    this.amount = amount;
    return this;
  }

  /**
   * Amount. Contains two sub-fields:<br> 1. Value: Transaction amount, including the cents<br> 2. Currency: Currency code based on ISO 
   * @return amount
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Money getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@javax.annotation.Nonnull Money amount) {
    this.amount = amount;
  }

  public TransferToDanaResponse additionalInfo(@javax.annotation.Nullable Object additionalInfo) {
    
    this.additionalInfo = additionalInfo;
    return this;
  }

  /**
   * Additional information
   * @return additionalInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getAdditionalInfo() {
    return additionalInfo;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalInfo(@javax.annotation.Nullable Object additionalInfo) {
    this.additionalInfo = additionalInfo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferToDanaResponse transferToDanaResponse = (TransferToDanaResponse) o;
    return Objects.equals(this.responseCode, transferToDanaResponse.responseCode) &&
        Objects.equals(this.responseMessage, transferToDanaResponse.responseMessage) &&
        Objects.equals(this.referenceNo, transferToDanaResponse.referenceNo) &&
        Objects.equals(this.partnerReferenceNo, transferToDanaResponse.partnerReferenceNo) &&
        Objects.equals(this.sessionId, transferToDanaResponse.sessionId) &&
        Objects.equals(this.customerNumber, transferToDanaResponse.customerNumber) &&
        Objects.equals(this.customerName, transferToDanaResponse.customerName) &&
        Objects.equals(this.amount, transferToDanaResponse.amount) &&
        Objects.equals(this.additionalInfo, transferToDanaResponse.additionalInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseCode, responseMessage, referenceNo, partnerReferenceNo, sessionId, customerNumber, customerName, amount, additionalInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferToDanaResponse {\n");
    sb.append("    responseCode: ").append(toIndentedString(responseCode)).append("\n");
    sb.append("    responseMessage: ").append(toIndentedString(responseMessage)).append("\n");
    sb.append("    referenceNo: ").append(toIndentedString(referenceNo)).append("\n");
    sb.append("    partnerReferenceNo: ").append(toIndentedString(partnerReferenceNo)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    customerNumber: ").append(toIndentedString(customerNumber)).append("\n");
    sb.append("    customerName: ").append(toIndentedString(customerName)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    additionalInfo: ").append(toIndentedString(additionalInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
